ARCH        = rs6000-64
#
#
#CPPFLAGS      = -WF,-DSYS_AIX,-DVAR_MFDS,-D'INSTALL_WRKMEM=53000000',-D'INSTALL_BASDIR="/kemi/andreas/prog/dalton/basis/"',-DIMPLICIT_NONE
F90           = xlf
F77           = xlf
CC            = xlc
RM            = rm -f
OPTFLAGS        = -O3 -qstrict -q64 -qtune=pwr4 -qmaxmem=-1 -qextname
CPP_FLAGS        =  -I../include -DSYS_AIX -D_LARGE_FILES -qlonglong -O3 -q64
INCLUDES      = -I../include 
LLIBS          = -lessl 
AR            = ar
ARFLAGS       = rvs
