ARCH        = core2
#
#
F90         = gfortran
CC          = gcc
# For optimal running 
OPTFLAGS    =   -w -march=core2 -mtune=core2 -malign-double -O3 -ffast-math -mcmodel=medium
#OPTFLAGS     =  -w -O3   
#OPTFLAGS     =  -w -O3 -g -pg 
#LLIBS     = -L/home/jeppe/prog/atlas/ATLAS/lib/Linux_P4SSE2
#MATHLIBS  = -llapack -lcblas -lf77blas -latlas -lsvml -Vaxlib
#MATHLIBS  = -llapack -lcblas -lf77blas -latlas 
MATHLABS= 
#
