ARCH        = i786-pc-linux-gnu
#
#
F90         = ifort -cm -w90 -w95
CC          = cc
#OPTFLAGS    = -O2 -prefetch -vec -tpp7 -xiMKW
OPTFLAGS    = -g -O0
LLIBS     = -L/home/andreas/prog/ATLAS/lib/Linux_P4SSE2
MATHLIBS  = -llapack -lcblas -lf77blas -latlas -lsvml -Vaxlib
#
