#
# $Id$
#

 OBJ_OPTIMIZE = \
            	vdw-DF.o \
            	vdw_DF_kernel.o \
		vdw_DF_get_qmesh_filename.o
#            vdirac.o \

	  OBJ = 

      LIBRARY = libpspw.a

    USES_BLAS = vdw-DF.F


  LIB_DEFINES = 


include ../../../../../config/makefile.h
include ../../../../../config/makelib.h

