
# $Id$
#
 OBJ_OPTIMIZE = \
		paw_Grsm_list.o \
		paw_lmbfgs.o



	  OBJ = 



      LIBRARY = libpaw.a

    USES_BLAS =  paw_Grsm_list.F paw_lmbfgs.F

  LIB_DEFINES =


include ../../../config/makefile.h
include ../../../config/makelib.h
include ../makefile.h
