#
# $Id: GNUmakefile,v 1.5 2001-12-14 20:02:47 bylaska Exp $
#
# intf and aux break on IBM SP xlhpf with optimization ... why? 

 OBJ_OPTIMIZE = \
			check.o \
            psi.o \
            psi_spin2.o \
            geodesic.o \
            Grassman.o \
            psi_read.o \
            psi_write.o \
			v_psi_read.o \
            v_psi_write.o \
            psi_new.o \
            v_psi_new.o 



	  OBJ = 

      LIBRARY = libpspw.a

    USES_BLAS = psi.F geodesic.F Grassman.F

  LIB_DEFINES = 


include ../../../../config/makefile.h
include ../../../../config/makelib.h

