#
# $Id: GNUmakefile,v 1.1 2001-08-30 00:33:15 edo Exp $
#
# intf and aux break on IBM SP xlhpf with optimization ... why? 

 OBJ_OPTIMIZE = \
			check.o \
            psi.o \
            psi_spin2.o \
            geodesic.o \
            Grassman.o \
            psi_get_ne.o \
            psi_get_header.o \
            psi_read.o \
            psi_write.o \
			v_psi_read.o \
            v_psi_write.o 



	  OBJ = 

      LIBRARY = libpspw.a

    USES_BLAS = psi.F geodesic.F Grassman.F

  LIB_DEFINES = 


include ../../../../config/makefile.h
include ../../../../config/makelib.h

