site_name: NWChem
site_description: NWChem Website
repo_url: https://github.com/nwchemgit/nwchem-wiki
site_url: https://nwchemgit.github.io
edit_uri: blob/master/
theme:
  name: readthedocs
  highlightjs: false
  prev_next_buttons_location: both
use_directory_urls: false
markdown_extensions:
    - smarty
    - toc:
        permalink: True
    - tables
#    - markdown_katex:
#         no_inline_svg: True
#         insert_fonts_css: True
#         macro-file: macros.tex
#    - pymdownx.arithmatex
#extra_javascript:
#  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
    - mdx_math:
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML
plugins:
  - search
  - alternate-link
nav:
      - 'User Documentation': Home.md
      - Download: Download.md
      - Quantum-Mechanical-Methods.md
      - Quantum-Molecular-Dynamics.md
      - Other-Capabilities.md
      - Examples.md
      - Supplementary-Information.md
      - Compiling-NWChem.md
      - Benchmarks.md
      - Known-Bugs.md
      - 'FAQ': FAQ.md
      - Tutorials.md
      - Forum.md
      - Archived Forum: Archived-Forum.md
