#
# $Id: GNUmakefile,v 1.13 1998-10-02 21:25:34 windus Exp $
#

 SUBDIRS = analytic/dft

 OBJ = scf_hessian.o rhf_hessian.o hess_blas.o
 
 OBJ_OPTIMIZE =  

   USES_BLAS = hess_blas.F 

   LIBRARY = libhessian.a

include ../config/makefile.h

include ../config/makelib.h

