#
# $Id: GNUmakefile,v 1.14 1999-05-06 17:29:34 windus Exp $
#

 SUBDIRS = analytic/dft analytic

 OBJ = scf_hessian.o rhf_hessian.o hess_blas.o
 
 OBJ_OPTIMIZE =  

   USES_BLAS = hess_blas.F 

   LIBRARY = libhessian.a

include ../config/makefile.h

include ../config/makelib.h

