#
# $Id$
#

 SUBDIRS = analytic

 OBJ = hess_blas.o hess_input.o
 
 OBJ_OPTIMIZE =  

   USES_BLAS = hess_blas.F 

   LIBRARY = libhessian.a

include ../config/makefile.h

include ../config/makelib.h

