#
# $Id: GNUmakefile,v 1.1 2001-12-17 23:31:14 bylaska Exp $
#

 OBJ_OPTIMIZE = \
            nwpw_timing.o

	  OBJ = 

      LIBRARY = libnwpwlib.a

    USES_BLAS = nwpw_timing.F

  	LIB_DEFINES = 
	LIB_INCLUDES = -I../include


include ../../../config/makefile.h
include ../../../config/makelib.h

