#
# $Id: GNUmakefile,v 1.10 2005-06-24 19:24:17 bylaska Exp $
#

 OBJ_OPTIMIZE = \
		lattice.o \
		mask_init.o \
		pack.o \
		cloak.o \
		cram.o \
		balance.o \
		G_init.o \
		c_G_init.o \
		strfac.o \
		cstrfac.o 


	  OBJ = 

      LIBRARY = libnwpwlib.a

    USES_BLAS = lattice.f pack.F G_init.F cram.F c_G_init.F

  LIB_DEFINES = 



include ../../../config/makefile.h
include ../../../config/makelib.h

