#
# $Id: GNUmakefile,v 1.2 2003-04-07 21:25:38 windus Exp $
#
 OBJ_OPTIMIZE = \
            c_coulomb.o

	  OBJ = 

      LIBRARY = libband.a

    USES_BLAS = c_coulomb.F

  LIB_DEFINES = 


include ../../../../config/makefile.h
include ../../../../config/makelib.h

