#
# $Id$
#

LIBRARY = liboptim.a

OBJ_OPTIMIZE = mepgs_input.o 

OBJ = mepgs_drv.o 

USES_BLAS = mepgs_drv.F 

include ../../config/makefile.h
include ../../config/makelib.h

#FFLAGS  = -qsource -qxref=full -bloadmap:load.map 
