#
# $Id: GNUmakefile,v 1.2 2001-08-30 16:58:34 bylaska Exp $
#
      SUBDIRS = Parallel io pseudopotential
                

          OBJ = 
                

      LIBRARY =	libnwpwlib.a

   USES_BLAS = 

  LIB_INCLUDES = 

  LIB_DEFINES = 




include ../../config/makefile.h
include ../../config/makelib.h









