#
# $Id: GNUmakefile,v 1.8 2001-11-11 01:29:05 bylaska Exp $
#
      SUBDIRS = Parallel D3dB control lattice io ion psp pseudopotential utilities unitcell fractional miscellaneous
                

          OBJ = 
                

   USES_BLAS = 

  LIB_INCLUDES = 

  LIB_DEFINES = 




include ../../config/makefile.h
include ../../config/makelib.h









