#
# $Id: GNUmakefile,v 1.19 2008-06-03 17:31:27 d3p708 Exp $
#
      SUBDIRS = Parallel D1dB D3dB Pneb K1dB C3dB DMatrix CMatrix control lattice io ion pseudopotential utilities unitcell brillouin_zone fractional linesearch timing ewald thermostats
                

          OBJ = 
                

   USES_BLAS = 

  LIB_INCLUDES = 

  LIB_DEFINES = 




include ../../config/makefile.h
include ../../config/makelib.h









