#
# $Id$
#
 OBJ_OPTIMIZE = \
		band_structure.o \
		band_interpolate_structure.o \
		band_kp_structure.o \
		band_fft_structure.o
                
	  OBJ = 



      LIBRARY = libband.a

    USES_BLAS = band_structure.F band_interpolate_structure.F  band_kp_structure.F band_fft_structure.F
                

  LIB_DEFINES =


include ../../../config/makefile.h
include ../../../config/makelib.h

