#$Id: GNUmakefile,v 1.28 2000-03-27 19:17:45 edo Exp $
# makefile,v 1.8 1994/12/05 20:37:08 og845 Exp

   OBJ = nwdft.o

   LIBRARY = libnwdft.a

# LIB_DEFINES = -DDFT_TIMER
 LIB_DEFINES =

   SUBDIRS = input_dft scf_dft coulomb xc util grid
LIB_INCLUDES = -I./include -I./grid


include ../config/makefile.h
include ../config/makelib.h


