#$Id$

SUBDIRS = 

OBJ = socrates_input.o \
      socrates_driver.o \
      socrates_scf_ga.o

OBJ_OPTIMIZE = socrates_util.o

LIBRARY = libsocrates.a

USES_BLAS = 

LIB_DEFINES += -DDEBUG_PRINT -DDETAILED_FREE

HEADERS =

include ../config/makefile.h
include ../config/makelib.h

