#
# $Id: GNUmakefile,v 1.1 2003-02-11 01:32:49 edo Exp $
#

          OBJ = paw_energy_kin_atom.o paw_matrix_kin.o
          HEADERS = paw_energy_kin_atom.fh paw_matrix_kin_data.fh


      LIBRARY =	libpaw.a

   USES_BLAS = 

  LIB_INCLUDES = -I../include/

  LIB_DEFINES = 




include ../../../config/makefile.h
include ../../../config/makelib.h
include ../makefile.h


