# $Id: GNUmakefile,v 1.6 1994-12-07 05:51:23 d3e129 Exp $
        OBJ = gradients.o force.o grad1.o grad2.o scf_gradient.o get_dens.o

   USES_BLAS = force.F

   LIBRARY = libgradients.a

include ../config/makefile.h
include ../config/makelib.h
