#
# $Id: GNUmakefile,v 1.5 2004-03-04 15:12:24 bylaska Exp $
#

          OBJ_OPTIMIZE =  paw_xc.o paw_vosko.o paw_dirac_x.o
          HEADERS = paw_xc.fh


      LIBRARY =	libpaw.a

   USES_BLAS = 

  LIB_INCLUDES =

  LIB_DEFINES = 




include ../../../config/makefile.h
include ../../../config/makelib.h


