#
# $Id$
#

          OBJ_OPTIMIZE =  paw_xc.o paw_vosko.o paw_dirac_x.o paw_gga.o
          HEADERS = paw_xc.fh


      LIBRARY =	libpaw.a

   USES_BLAS =  paw_xc.F

  LIB_INCLUDES =

  LIB_DEFINES = 




include ../../../config/makefile.h
include ../../../config/makelib.h


