#
# $Id: GNUmakefile,v 1.1 2001-08-30 16:58:34 bylaska Exp $
#
# intf and aux break on IBM SP xlhpf with optimization ... why? 
 OBJ_OPTIMIZE = \
                psp_generator_input.o \
                pspsolve.o \
                get_word.o name.o\
                loggrid.o pred_cor.o spline.o grids.o atom.o  \
                schrodin.o \
                pauli.o \
                dft.o \
                hartree.o \
                dirac_exchange.o \
                perdew_wang.o perdew_zunger.o vosko.o \
                pbe_exchange.o pbe_correlation.o \
                hamann.o \
                troullier.o xpansion.o gaussj.o \
                vanderbilt.o xpansion2.o \
                psp1d.o generate_rho_semicore.o
       

	  OBJ = 

      LIBRARY = libpspw.a

    USES_BLAS = 

  LIB_DEFINES = 


include ../../../config/makefile.h
include ../../../config/makelib.h

