#
# $Id: GNUmakefile 24267 2013-05-23 07:45:28Z bylaska $
#

 OBJ_OPTIMIZE = \
            	nwxc_vdw3a_sh.o \
            	nwxc_vdw3b_sh.o \
            	nwxc_vdw3c_sh.o 

	  OBJ = nwxc_vdw3d_sh.o 

      LIBRARY = libnwpwlib.a

    USES_BLAS =

  LIB_DEFINES = 


include ../../../../config/makefile.h
include ../../../../config/makelib.h

