#
# $Id$
#

LIBRARY = liboptim.a

OBJ_OPTIMIZE = tropt_input.o 

OBJ = tropt_drv.o 

USES_BLAS = tropt_drv.F 

include ../../config/makefile.h
include ../../config/makelib.h

#FFLAGS  = -qsource -qxref=full -bloadmap:load.map 
