# $Id: GNUmakefile,v 1.5 2004-09-21 19:12:04 marat Exp $
  LIBRARY = libcons.a
  
  OBJ = cons_input.o cons.o cons_utils.o cons_springs.o cons_rtdb.o cons_data.o
 
 


include ../config/makefile.h
include ../config/makelib.h

