# $Id$
  LIBRARY = libcons.a
  
  OBJ = cons_input.o cons.o cons_utils.o cons_springs.o cons_rtdb.o cons_data.o
 
  USES_BLAS = cons_data.F
 


include ../config/makefile.h
include ../config/makelib.h

