#
# $Id: GNUmakefile,v 1.2 2001-11-16 22:53:12 bylaska Exp $
#

 OBJ_OPTIMIZE = \
            C3dB-new.o


	  OBJ = 

      LIBRARY = libnwpwlib.a

    USES_BLAS = C3dB-new.F

  LIB_DEFINES = 


include ../../../config/makefile.h
include ../../../config/makelib.h

