#
# $Id$
#

          OBJ = task_smd_energy.o smd_init_energy.o

      LIBRARY = libsmd.a

#  LIB_DEFINES = -DMPI -I$(MPI_INCLUDE)



include ../../config/makefile.h
include ../../config/makelib.h









