#
#	$Id: MakeFile,v 1.2 2000-07-18 18:10:15 edo Exp $	
#

!MESSAGE *** Unresolved issues in this nmake file ***

SUBDIRS = double


LIBRARY = blas.lib

!INCLUDE ..\config\NTmakefile.h
!INCLUDE ..\config\NTmakelib.h
