#
# $Id: GNUmakefile,v 1.4 1999-02-01 16:58:49 d3j191 Exp $
#
 OBJ_OPTIMIZE = ana_data.o\
                ana_finish.o\
                ana_init.o\
                ana_inirms.o\
                ana_initx.o\
                ana_input.o\
                ana_pltgrd.o\
                ana_rdhdr.o\
                ana_rdfram.o\
                ana_rdref.o\
                ana_rmsdev.o\
                ana_rtdbin.o\
                ana_select.o\
                ana_sizref.o\
                ana_super.o\
                ana_task.o\
                ana_trajct.o\
                ana_wtfram.o\
                ana_wthdr.o\
                analyz.o\
                super.o

LIBRARY=libnwargos.a

HEADERS=

USES_BLAS=

include ../config/makefile.h
include ../config/makelib.h
