#
# $Id$
#
 OBJ_OPTIMIZE = ana_angle.o\
                ana_atrad.o\
                ana_bond.o\
                ana_chgdst.o\
                ana_data.o\
                ana_define.o\
                ana_diel.o\
                ana_esppt.o\
                ana_finish.o\
                ana_groups.o\
                ana_hbond.o\
                ana_index.o\
                ana_init.o\
                ana_inirms.o\
                ana_initx.o\
                ana_input.o\
                ana_pltgrd.o\
                ana_rama.o\
                ana_rdhdr.o\
                ana_rdf.o\
                ana_rdfram.o\
                ana_rdref.o\
                ana_rdtop.o\
                ana_report.o\
                ana_rmsdev.o\
                ana_rtdbin.o\
                ana_select.o\
                ana_sizref.o\
                ana_tag.o\
                ana_task.o\
                ana_torsion.o\
                ana_wtfram.o\
                ana_wthdr.o\
                ana_wrtpdb.o\
                ana_wrtxyz.o\
                ana_xaver.o\
                ana_covar.o\
                analyz.o

LIBRARY=libanalyze.a

HEADERS=

USES_BLAS=

include ../config/makefile.h
include ../config/makelib.h
