#
# $Id: GNUmakefile,v 1.1 1998-12-29 18:01:05 d3j191 Exp $
#
 OBJ_OPTIMIZE = ana_data.o\
                ana_finish.o\
                ana_init.o\
                ana_inirms.o\
                ana_initx.o\
                ana_input.o\
                ana_rmsdev.o\
                ana_rtdbin.o\
                ana_super.o\
                analyz.o

LIBRARY=libnwargos.a

HEADERS=

USES_BLAS=

include ../config/makefile.h
include ../config/makelib.h
