#
# $Id$
#

 OBJ_OPTIMIZE = \
		brillouin_zone_input.o \
		brillioun.o

	  OBJ = 

      LIBRARY = libnwpwlib.a

    USES_BLAS = 

  LIB_DEFINES = 


include ../../../config/makefile.h
include ../../../config/makelib.h

