#
# $Id: GNUmakefile,v 1.1 2001-11-26 21:34:21 bylaska Exp $
#

 OBJ_OPTIMIZE = \
			brillouin_zone_input.o

	  OBJ = 

      LIBRARY = libnwpwlib.a

    USES_BLAS = 

  LIB_DEFINES = 


include ../../../config/makefile.h
include ../../../config/makelib.h

