#
# $Id: GNUmakefile,v 1.2 2006-04-08 00:25:47 bylaska Exp $
#

 OBJ_OPTIMIZE = \
		brillouin_zone_input.o \
		brillioun.o

	  OBJ = 

      LIBRARY = libnwpwlib.a

    USES_BLAS = 

  LIB_DEFINES = 


include ../../../config/makefile.h
include ../../../config/makelib.h

