#
# $Id: GNUmakefile,v 1.2 2002-02-13 20:02:06 edo Exp $
#
# intf and aux break on IBM SP xlhpf with optimization ... why? 
 OBJ_OPTIMIZE = \
	      	compressed_io.o \
            nwpw_message.o \
            second.o


	  OBJ = 

      LIBRARY = libnwpwlib.a

    USES_BLAS =

  LIB_DEFINES = 


include ../../../config/makefile.h
include ../../../config/makelib.h

