#
# $Id: GNUmakefile,v 1.1 2001-12-21 01:49:30 bylaska Exp $
#

 OBJ_OPTIMIZE = \
            pspw_Grsm_list.o \
			pspw_lmbfgs.o



	  OBJ = 

      LIBRARY = libpspw.a

    USES_BLAS = 

  LIB_DEFINES = 


include ../../../../config/makefile.h
include ../../../../config/makelib.h

