#
# $Id: GNUmakefile,v 1.6 2004-03-09 21:25:58 bylaska Exp $
#

 OBJ_OPTIMIZE = \
		pspw_Grsm_list.o \
		pspw_lmbfgs.o \
		pspw_lmbfgs2.o \
		pspw_lmbfgs3.o \
		pspw_diis.o



	  OBJ = 

      LIBRARY = libpspw.a

    USES_BLAS = pspw_lmbfgs.F pspw_lmbfgs2.F pspw_diis.F pspw_Grsm_list.F

  LIB_DEFINES = 


include ../../../../config/makefile.h
include ../../../../config/makelib.h

