#
# $Id: GNUmakefile,v 1.5 2003-10-20 16:47:02 bylaska Exp $
#

 OBJ_OPTIMIZE = \
		pspw_Grsm_list.o \
		pspw_lmbfgs.o \
		pspw_lmbfgs3.o \
		pspw_diis.o



	  OBJ = 

      LIBRARY = libpspw.a

    USES_BLAS = pspw_diis.F pspw_Grsm_list.F

  LIB_DEFINES = 


include ../../../../config/makefile.h
include ../../../../config/makelib.h

