
# $Id: GNUmakefile,v 1.13 2002-04-26 22:15:43 bert Exp $

     OBJ_OPTIMIZE = bas_create_uncont.o ga_extra.o int_1edk_ga.o \
                    dk_input.o dkdiv_energy.o int_pxvp_ga.o \
                    rel_input.o int_1edkso_ga.o

     LIBRARY = libnwints.a

USES_BLAS = int_1edk_ga.F 

include ../../config/makefile.h
include ../../config/makelib.h

