#
# $Id: GNUmakefile,v 1.4 2001-11-11 01:29:05 bylaska Exp $
#

 OBJ_OPTIMIZE = \
            control.o \
			psi_get_header.o


	  OBJ = 

      LIBRARY = libnwpwlib.a

    USES_BLAS = 

  LIB_DEFINES = 


include ../../../config/makefile.h
include ../../../config/makelib.h

