#
# $Id: GNUmakefile,v 1.3 2001-08-30 18:42:34 bylaska Exp $
#

 OBJ_OPTIMIZE = \
            control.o


	  OBJ = 

      LIBRARY = libpspw.a

    USES_BLAS = 

  LIB_DEFINES = 


include ../../../config/makefile.h
include ../../../config/makelib.h

