#
# $Id: GNUmakefile,v 1.6 2001-12-20 00:30:52 bylaska Exp $
#

 OBJ_OPTIMIZE = \
            control.o \
			psi_get_ne.o \
			psi_get_version.o \
			psi_get_header.o


	  OBJ = 

      LIBRARY = libnwpwlib.a

    USES_BLAS = 

  LIB_DEFINES = 


include ../../../config/makefile.h
include ../../../config/makelib.h

