#
# $Id: GNUmakefile,v 1.5 2006-06-05 17:34:26 edo Exp $
#

          OBJ_OPTIMIZE =  paw_density.o


      LIBRARY =	libpaw.a

   USES_BLAS =  paw_density.F

  LIB_INCLUDES =

  LIB_DEFINES = 




include ../../../config/makefile.h
include ../../../config/makelib.h


