#
# $Id: GNUmakefile,v 1.3 2004-03-04 15:12:22 bylaska Exp $
#

          OBJ_OPTIMIZE =  paw_density.o
          HEADERS = paw_density_data.fh


      LIBRARY =	libpaw.a

   USES_BLAS = 

  LIB_INCLUDES =

  LIB_DEFINES = 




include ../../../config/makefile.h
include ../../../config/makelib.h


