#
# $Id$
#

          OBJ_OPTIMIZE =  paw_density.o


      LIBRARY =	libpaw.a

   USES_BLAS =  paw_density.F

  LIB_INCLUDES =

  LIB_DEFINES = 




include ../../../config/makefile.h
include ../../../config/makelib.h


