#
# $Id$
#
 OBJ_OPTIMIZE = \
                lcao_wvfnc.o \
                wvfnc_new_lcao_density.o \
                lcao_write_matrix.o \
				lcao_generate_smatrix.o \
				lcao_generate_kematrix.o \
				lcao_generate_vlmatrix.o \
				lcao_generate_vnlmatrix.o \
				lcao_generate_vhxcmatrix.o \
				lcao_init_dn.o \
				lcao_new_dn.o \
				lcao_make_psi.o \
				lcao_write_psi.o \
				lcaov1.o


	  OBJ = 

      LIBRARY = libpspw.a

    USES_BLAS = lcao_diis_dn.F lcao_init_dn.F lcao_new_dn.F lcao_new_mix_dn.F lcao_generate_vhxcmatrix.F lcao_diis.F lcaov1.F wvfnc_new_lcao_density.F

  LIB_DEFINES = 


include ../../../config/makefile.h
include ../../../config/makelib.h

