#
# $Id: GNUmakefile,v 1.6 2002-02-11 19:34:40 edo Exp $
#
 OBJ_OPTIMIZE = \
                lcao_wvfnc.o \
                lcao_write_matrix.o \
				lcao_generate_smatrix.o \
				lcao_generate_kematrix.o \
				lcao_generate_vlmatrix.o \
				lcao_generate_vnlmatrix.o \
				lcao_generate_vhxcmatrix.o \
				lcao_init_dn.o \
				lcao_new_dn.o \
				lcao_make_psi.o \
				lcao_write_psi.o 


	  OBJ = 

      LIBRARY = libpspw.a

    USES_BLAS = lcao_diis_dn.F lcao_init_dn.F lcao_new_dn.F lcao_new_mix_dn.F

  LIB_DEFINES = 


include ../../../config/makefile.h
include ../../../config/makelib.h

