#!/bin/csh

# $Id: catsrc,v 1.3 1995-02-02 23:26:44 d3g681 Exp $

cd ..

foreach dir ( $* )

   echo 'module ' $dir

   find $dir \( -name "*.F" -o \
                -name "*.f" -o \
                -name "*.c" -o \
                -name "*.fh" -o \
                -name "*.h" -o \
                -name "makefile" \) -exec grep '$Id' "{}" ";"

end
