#!/bin/csh

# $Id: catsrc,v 1.2 1995-02-02 18:09:17 d3g681 Exp $

cd ..

foreach dir ( $* )

   echo 'module ' $dir

   find $dir \( -name "*.F" -o \
                -name "*.f" -o \
                -name "*.c" -o \
                -name "*.fh" -o \
                -name "*.h" -o \
                -name "makefile" \) -exec cat "{}" ";"

end
