#!/usr/local/bin/perl5
#
# $Id: toplsf.pl,v 1.1 2002-10-30 22:02:12 edo Exp $
#

# UNDER LSF DETERMINE THE TIME LEFT TO A BATCH JOB

# PRINT THE TIME LEFT IN SEC ON STDOUT AND EXIT(0)
# ON FAILURE EXIT(1) AND PRINT NON-INTEGER MESSAGE.

