#
# $Id: GNUmakefile,v 1.5 2006-12-27 19:47:52 bylaska Exp $
#

 OBJ_OPTIMIZE = \
            	shake_chain.o \
		shake_analysis.o \
		molecular.o \
		pspw_molecule.o \
		pspw_atom.o \
		pspw_bond.o

	  OBJ = 

      LIBRARY = libnwpwlib.a

    USES_BLAS = 

  LIB_DEFINES = 


include ../../../../config/makefile.h
include ../../../../config/makelib.h

