#
# $Id: GNUmakefile,v 1.3 2001-08-30 18:42:35 bylaska Exp $
#

 OBJ_OPTIMIZE = \
            shake_chain.o \
			molecular.o \
			pspw_molecule.o \
			pspw_atom.o \
			pspw_bond.o

	  OBJ = 

      LIBRARY = libpspw.a

    USES_BLAS = 

  LIB_DEFINES = 


include ../../../../config/makefile.h
include ../../../../config/makelib.h

