#$Id: GNUmakefile,v 1.3 2006-09-25 21:11:53 windus Exp $
   OBJ_OPTIMIZE = gibbs.o

   OBJ = dntmc_input.o dntmc_setgeom.o

   LIBRARY = libdntmc.a
 USES_BLAS = gibbs.F

include ../config/makefile.h
include ../config/makelib.h


