#$Id: GNUmakefile,v 1.4 2008-03-04 17:55:12 windus Exp $
   OBJ_OPTIMIZE = gibbs.o

   OBJ = dntmc_input.o dntmc_setgeom.o

   LIBRARY = libdntmc.a
 USES_BLAS = gibbs.F

include ../config/makefile.h
include ../config/makelib.h
