#
# $Id: GNUmakefile 21430 2011-11-07 21:59:54Z d3p852 $
#
     SUBDIRS =


 OBJ_OPTIMIZE = \
		band_analysis.o \
                orb_pop_borb.o 


      LIBRARY = libband.a

    USES_BLAS =  band_analysis.F orb_pop_borb.F


  LIB_DEFINES = 


include ../../../config/makefile.h
include ../../../config/makelib.h

