# $Id: GNUmakefile,v 1.63 2007-10-12 00:05:41 niri Exp $
#
	OBJ_OPTIMIZE = \
	dft_zora_utils.o\
	dft_zora_utils_so.o\
	dft_zora_rhos.o\
	dft_zora_rhos_so.o\
	grid_zoracorr.o\
	grid_zoracorr_FA.o\
	gridQpqPotential.o\
	zora_getv.o\
	zora_getv_sf.o\
	zora_getv_so.o\
	calc_zora_sf.o\
	calc_zora_so.o

     LIBRARY = libnwdft.a

 LIB_DEFINES =

LIB_INCLUDES = -I../include -I../grid

   USES_BLAS =

HEADERS = 

include ../../config/makefile.h
include ../../config/makelib.h
