#
# $Id: GNUmakefile,v 1.1 2004-11-05 23:15:01 bylaska Exp $
#
 SUBDIRS = 

 OBJ_OPTIMIZE = \
            pspw_hfx.o 


	  OBJ = 

      LIBRARY = libpspw.a

    USES_BLAS = pspw_hfx.F

  LIB_DEFINES = 


include ../../../../config/makefile.h
include ../../../../config/makelib.h

