#
# $Id: GNUmakefile,v 1.2 2009-03-27 23:47:15 bylaska Exp $
#
 SUBDIRS = 

 OBJ_OPTIMIZE = pspw_hfx.o  butter.o

	  OBJ = 

      LIBRARY = libpspw.a

    USES_BLAS = pspw_hfx.F butter.F

  LIB_DEFINES = 


include ../../../../config/makefile.h
include ../../../../config/makelib.h

