# $Id: GNUmakefile,v 1.3 2001-01-19 17:43:10 windus Exp $
       HEADERS = 
  OBJ_OPTIMIZE = 
           OBJ = atsym.o drdy.o drdy_input.o Input_for_drdy.o drdy_synch.o \
                 read_drdy_rtdb.o rgener.o ratoms.o rstat.o rpath.o \
                 rgeom.o rgsad.o rphwrt.o sort.o react.o potset_nwchem.o \
                 trans.o tranf.o center.o rotx.o moiten.o pot2.o nwc_s2.o \
                 rotmat.o rotg.o rotf.o restor.o drdy_nwc_get.o react2.o \
                 saddle.o setpth.o diagf.o pmlqsp.o mxlneq.o pmclqa.o \
                 path.o path2.o pot1.o nwc_s1.o euler.o pmlqa.o dsdt.o \
                 rsp.o pmcube.o fdiag.o potsp.o projct.o pythag.o \
                 getstr.o io.o sumout.o wfiles.o

       LIBRARY = libdrdy.a
   LIB_TARGETS = 

     USES_BLAS = nwc_s1.F nwc_s2.F

include ../config/makefile.h
include ../config/makelib.h





