#
# $Id: GNUmakefile,v 1.4 2003-02-21 03:13:11 bylaska Exp $
#

          OBJ =  paw_mult.o paw_mult_interaction.o
          HEADERS = 


      LIBRARY =	libpaw.a

   USES_BLAS = 

  LIB_INCLUDES =

  LIB_DEFINES = 




include ../../../config/makefile.h
include ../../../config/makelib.h
include ../makefile.h


