#
# $Id$
#

          OBJ_OPTIMIZE =  paw_mult.o paw_mult_interaction.o paw_mult_energy.o
          HEADERS = paw_mult_data.fh


      LIBRARY =	libpaw.a

   USES_BLAS = paw_mult.F paw_mult_interaction.F paw_mult_energy.F

  LIB_INCLUDES =

  LIB_DEFINES = 


include ../../../config/makefile.h
include ../../../config/makelib.h
include ../makefile.h


