#
# $Id: GNUmakefile,v 1.3 2003-02-21 03:01:48 bylaska Exp $
#

          #OBJ =  paw_mult.o paw_mult_interaction.o
          OBJ =  paw_mult.o 
          HEADERS = 


      LIBRARY =	libpaw.a

   USES_BLAS = 

  LIB_INCLUDES =

  LIB_DEFINES = 




include ../../../config/makefile.h
include ../../../config/makelib.h
include ../makefile.h


