#
# $Id: GNUmakefile,v 1.8 1999-02-01 15:59:19 d3j191 Exp $
#

 OBJ_OPTIMIZE =  esp.o\
                 esp_dalloc.o\
                 esp_denmat.o\
                 esp_elemom.o\
                 esp_esp.o\
                 esp_fit.o\
		 esp_getden.o\
		 esp_getg.o\
                 esp_getx.o\
                 esp_grdcnt.o\
                 esp_grid.o\
                 esp_input.o\
                 esp_jacobi.o\
                 esp_malloc.o\
                 esp_matinv.o\
                 esp_out.o\
                 esp_plt.o\
                 esp_rms.o\
                 esp_rtdbin.o\
                 esp_swatch.o\
                 esp_wrtinp.o

LIBRARY=libesp.a

HEADERS=

USES_BLAS=esp_esp.F esp_denmat.F

include ../config/makefile.h

include ../config/makelib.h
