#
# $Id: GNUmakefile,v 1.1 1997-10-06 23:00:38 d3j191 Exp $
#

 OBJ_OPTIMIZE =  esp.o\
                 esp_dalloc.o\
                 esp_denmat.o\
                 esp_elemom.o\
                 esp_esp.o\
                 esp_fit.o\
                 esp_getx.o\
                 esp_grid.o\
                 esp_input.o\
                 esp_malloc.o\
                 esp_matinv.o\
                 esp_out.o\
                 esp_rtdbin.o\
                 esp_wrtinp.o

LIBRARY=libesp.a

HEADERS=

USES_BLAS=esp_esp.F

include ../config/makefile.h

include ../config/makelib.h
