#
# $Id: GNUmakefile,v 1.7 2002-01-16 20:51:13 bylaska Exp $
#
      SUBDIRS = lib kbpp makepsi cpsd cgsd analysis \
                cell_optimize qmmm charge dplot lcao


          OBJ = task_pspw.o


      LIBRARY =	libpspw.a

   USES_BLAS = 

  LIB_INCLUDES = 

  LIB_DEFINES = 




include ../../config/makefile.h
include ../../config/makelib.h









