#
# $Id: GNUmakefile,v 1.2 2001-08-30 16:58:40 bylaska Exp $
#
      SUBDIRS = lib kbpp makepsi cpsd cgsd fractional analysis \
                cell_optimize water_pseudopotential dplot


          OBJ = task_pspw.o \
                pspw_input.o \
                simulation_cell_input.o


      LIBRARY =	libpspw.a

   USES_BLAS = 

  LIB_INCLUDES = 

  LIB_DEFINES = 




include ../../config/makefile.h
include ../../config/makelib.h









