#
# $Id: GNUmakefile,v 1.4 2001-10-26 02:28:24 bylaska Exp $
#
      SUBDIRS = lib kbpp makepsi cpsd cgsd fractional analysis \
                cell_optimize qmmm dplot


          OBJ = task_pspw.o \
                pspw_input.o 


      LIBRARY =	libpspw.a

   USES_BLAS = 

  LIB_INCLUDES = 

  LIB_DEFINES = 




include ../../config/makefile.h
include ../../config/makelib.h









