#
# $Id: GNUmakefile,v 1.2 2002-01-14 17:33:58 bylaska Exp $
#

 OBJ_OPTIMIZE = \
			simulation_cell_input.o

	  OBJ = 

      LIBRARY = libnwpwlib.a

    USES_BLAS = 

  LIB_DEFINES = 


include ../../../config/makefile.h
include ../../../config/makelib.h

