
        OBJ = int_dip_ga.o cphf_int_debug.o

# cphf_poliz.o mjdtest.o

    LIBRARY = libcphf.a

  USES_BLAS = 

 LIB_DEFINES =



include ../config/makefile.h
include ../config/makelib.h

















