#
# $Id: GNUmakefile,v 1.17 1998-04-03 17:01:12 d3e129 Exp $
#

        OBJ = cphf.o \
              cphf_poliz.o \
	      cphf_solve.o 



    LIBRARY = libcphf.a


include ../config/makefile.h
include ../config/makelib.h


