#
# $Id: GNUmakefile,v 1.16 1998-04-01 18:32:40 d3e129 Exp $
#

        OBJ = cphf.o \
              cphf_poliz.o \
	      cphf_solve.o 
	      
	      

    LIBRARY = libcphf.a


include ../config/makefile.h
include ../config/makelib.h


