
# $Id: GNUmakefile,v 1.2 2001-11-11 01:29:08 bylaska Exp $
#
# intf and aux break on IBM SP xlhpf with optimization ... why? 
 OBJ_OPTIMIZE = \
				cpsd_input.o \
				cpmd_input.o \
                cpsdv5.o \
                cpmdv5.o \
                inner_loop.o \
                inner_loop_md.o \
                psi_lmbda.o 



	  OBJ = 



      LIBRARY = libpspw.a

    USES_BLAS = psi_lmbda.f \
                inner_loop.F inner_loop_md.F cpsdv5.F cpmdv5.F
                

  LIB_DEFINES =


include ../../../config/makefile.h
include ../../../config/makelib.h

