
# $Id: GNUmakefile,v 1.5 2004-01-29 02:27:53 bylaska Exp $
#
 OBJ_OPTIMIZE = \
		cpsd_input.o \
		cpmd_input.o \
                cpsdv5.o \
                cpmdv5.o \
                inner_loop.o \
                inner_loop_md.o \
                psi_lmbda.o psi_lmbda_sic.o \
		fei_output.o



	  OBJ = 



      LIBRARY = libpspw.a

    USES_BLAS = psi_lmbda.f psi_lmbda_sic.f \
                inner_loop.F inner_loop_md.F cpsdv5.F cpmdv5.F
                

  LIB_DEFINES =


include ../../../config/makefile.h
include ../../../config/makelib.h

