#
# $Id: GNUmakefile,v 1.2 2007-06-21 02:08:06 bylaska Exp $
#
      SUBDIRS = minimizer cpsd lib

	OBJ_OPTIMIZE = 	ofpw_energy.o task_ofpw.o
	
        #OBJ = ofpw_input.o


      LIBRARY =	libofpw.a

   USES_BLAS = 

  LIB_INCLUDES = 

  LIB_DEFINES = 




include ../../config/makefile.h
include ../../config/makelib.h









