#
# $Id: GNUmakefile,v 1.1 2007-06-19 23:31:57 bylaska Exp $
#
      SUBDIRS = minimizer

	OBJ_OPTIMIZE = 	ofpw_energy.o 
	
        #OBJ = ofpw_input.o


      LIBRARY =	libofpw.a

   USES_BLAS = 

  LIB_INCLUDES = 

  LIB_DEFINES = 




include ../../config/makefile.h
include ../../config/makelib.h









