#
# $Id$
#
 SUBDIRS = 

 OBJ_OPTIMIZE = \
            pspw_sic.o 


	  OBJ = 

      LIBRARY = libpspw.a

    USES_BLAS = pspw_sic.F

  LIB_DEFINES = 


include ../../../../config/makefile.h
include ../../../../config/makelib.h

