#
# $Id: GNUmakefile,v 1.2 2002-02-11 19:18:07 edo Exp $
#
# intf and aux break on IBM SP xlhpf with optimization ... why? 
 SUBDIRS = 

 OBJ_OPTIMIZE = \
            pspw_sic.o 


	  OBJ = 

      LIBRARY = libpspw.a

    USES_BLAS = pspw_sic.F

  LIB_DEFINES = 


include ../../../../config/makefile.h
include ../../../../config/makelib.h

