#
# $Id: GNUmakefile,v 1.1 2001-08-30 00:35:12 edo Exp $
#
# intf and aux break on IBM SP xlhpf with optimization ... why? 
 SUBDIRS = 

 OBJ_OPTIMIZE = \
            pspw_sic.o 


	  OBJ = 

      LIBRARY = libpspw.a

    USES_BLAS = 

  LIB_DEFINES = 


include ../../../../config/makefile.h
include ../../../../config/makelib.h

