#
# $Id: GNUmakefile 19708 2010-10-29 18:04:21Z d3y133 $
#

OBJ_OPTIMIZE =  string.o string_input.o

LIBRARY=liboptim.a

HEADERS=

USES_BLAS= 

include ../../config/makefile.h

include ../../config/makelib.h

showobj:
	echo "obj $(OBJ) "
	echo "obj_opt $(OBJ_OPTIMIZE)"
