#
# $Id: GNUmakefile,v 1.4 2007-09-29 00:33:12 bylaska Exp $
#
 SUBDIRS =

 OBJ_OPTIMIZE = \
            MOTION.o \
            psp.o \
	    paw.o \
            psp_stress.o \
	    semicore.o \
	    semicore_force.o


	  OBJ = 

      LIBRARY = libpspw.a

    USES_BLAS = psp.F paw.F semicore.F semicore_force.F psp_stress.F semicore_force_a.F semicore_force_b.F

  LIB_DEFINES = 


include ../../../../config/makefile.h
include ../../../../config/makelib.h

