#
# $Id: GNUmakefile,v 1.1 2002-01-14 21:06:28 bylaska Exp $
#
 SUBDIRS =

 OBJ_OPTIMIZE = \
            MOTION.o \
            psp.o \
            psp_stress.o \
			semicore.o \
			semicore_force.o


	  OBJ = 

      LIBRARY = libpspw.a

    USES_BLAS = psp.F semicore.F semicore_force.F

  LIB_DEFINES = 


include ../../../../config/makefile.h
include ../../../../config/makelib.h

