#
# $Id$
#
 SUBDIRS =

 OBJ_OPTIMIZE = \
            MOTION.o \
            psp.o \
            psp_olddebug.o \
	    psp_cmp_dE_Qlm.o \
	    paw.o \
            psp_stress.o \
	    semicore.o \
	    semicore_force.o \
            psp_U.o \
            psp_ld.o 


	  OBJ = 

      LIBRARY = libpspw.a

    USES_BLAS = psp.F psp_olddebug.F paw.F semicore.F semicore_force.F psp_stress.F semicore_force_a.F semicore_force_b.F psp_U.F psp_ld.F

  LIB_DEFINES = 


include ../../../../config/makefile.h
include ../../../../config/makelib.h

