
# $Id: GNUmakefile,v 1.3 2002-02-11 18:27:12 edo Exp $
#
 OBJ_OPTIMIZE = \
				cell_optimize_input.o \
                cell_optimize.o \
                update_unitcell.o



	  OBJ = 



      LIBRARY = libpspw.a

    USES_BLAS =update_unitcell.F
                
  LIB_DEFINES =


include ../../../config/makefile.h
include ../../../config/makelib.h

