
# $Id: GNUmakefile,v 1.4 2002-04-24 17:44:49 bylaska Exp $
#
 OBJ_OPTIMIZE = \
		cell_optimize_input.o \
                cell_optimize.o \
                update_unitcell.o \
		pspw_stress_numerical.o \
		stress_fd.o



	  OBJ = 



      LIBRARY = libpspw.a

    USES_BLAS =update_unitcell.F
                
  LIB_DEFINES =


include ../../../config/makefile.h
include ../../../config/makelib.h

