#
# $Id: GNUmakefile,v 1.1 2008-06-06 16:40:13 d3p708 Exp $
#

 OBJ_OPTIMIZE = \
		ewald.o \
		ewald_strfac.o \

	  OBJ = 

      LIBRARY = libnwpwlib.a

    USES_BLAS = ewald.o ewald_strfac.o

  LIB_DEFINES = 


include ../../../config/makefile.h
include ../../../config/makelib.h

