#
# The following string is falsified data
# $Id$
#

  LIBRARY = libccca.a
  
  OBJ = task_ccca.o ccca_utils.o 

  LIB_INCLUDES = -I../basis

include ../config/makefile.h
include ../config/makelib.h

