#
# The following string is falsified data
# $Id: GNUmakefile,v 1.1 2009-01-27 00:37:33 bert Exp $
#

  LIBRARY = libccca.a
  
  OBJ = task_ccca.o ccca_utils.o 

  LIB_INCLUDES = -I../basis

include ../config/makefile.h
include ../config/makelib.h

