# $Id: GNUmakefile,v 1.5 1994-11-14 23:51:21 gg502 Exp $

      OBJ_OPTIMIZE = \
	bsolve.o	\
	dft.o		\
	diis.o		\
	diisdriver.o			   gacond.o	\
	gasbld.o			   gafact.o	\
	hamwght.o	\
	refvec.o			   scfban.o	\
	scfcvg.o			   scfdriver.o	\

     LIBRARY = libnwdft.a

   USES_BLAS = gasbld.F bsolve.F

include ../../config/makefile.h
include ../../config/makelib.h



