#
# $Id$
#
 SUBDIRS =

 OBJ_OPTIMIZE = \
            aorbs.o 

	  OBJ = 

      LIBRARY = libpspw.a

    USES_BLAS = aorbs.F

  LIB_DEFINES = 


include ../../../../config/makefile.h
include ../../../../config/makelib.h

