#
# $Id: GNUmakefile,v 1.1 2006-12-10 01:03:20 d3j191 Exp $
#
 OBJ_OPTIMIZE = dia_alloc.o\
                dia_angle.o\
                dia_atrad.o\
                dia_bond.o\
                dia_chgdst.o\
                dia_data.o\
                dia_define.o\
                dia_diel.o\
                dia_esppt.o\
                dia_finish.o\
                dia_groups.o\
                dia_hbond.o\
                dia_index.o\
                dia_init.o\
                dia_inirms.o\
                dia_initx.o\
                dia_input.o\
                dia_pltgrd.o\
                dia_rama.o\
                dia_rdhdr.o\
                dia_rdf.o\
                dia_rdfram.o\
                dia_rdref.o\
                dia_rdtop.o\
                dia_report.o\
                dia_rmsdev.o\
                dia_rtdbin.o\
                dia_select.o\
                dia_sizref.o\
                dia_tag.o\
                dia_task.o\
                dia_torsion.o\
                dia_wtfram.o\
                dia_wthdr.o\
                dia_wrtpdb.o\
                dia_wrtxyz.o\
                dia_xaver.o\
                dia_covar.o\
                diana.o

LIBRARY=libdiana.a

HEADERS=

USES_BLAS=

include ../config/makefile.h
include ../config/makelib.h
