#
# $Id: GNUmakefile,v 1.2 2001-11-11 01:29:08 bylaska Exp $
#
 OBJ_OPTIMIZE = \
                psp_formatter_input.o \
                psp_formatter.o \
                psp_stress_formatter.o \
	      		kbppv3.o \
	      		kbppv3-stress.o \
                setup_kbpp.o \
                integrate_kbppv3.o \
                integrate_stress.o


	  OBJ = 

      LIBRARY = libnwpwlib.a

    USES_BLAS = setup_kbpp.f integrate_kbppv3.f

  LIB_DEFINES = 


include ../../../config/makefile.h
include ../../../config/makelib.h

