# $Id$
#
	OBJ_OPTIMIZE = \
	deloc_driver.o \
	deloc.o \
	deloc_utils.o       

	LIBRARY = liboptim.a

	LIB_DEFINES =

	LIB_INCLUDES =

	USES_BLAS =

	HEADERS = 

include ../../config/makefile.h
include ../../config/makelib.h
