#
# $Id: GNUmakefile,v 1.1 2001-10-31 02:07:51 edo Exp $
#
 OBJ_OPTIMIZE = nwpw_library.o nwpw_libfile.o


	  OBJ = 

      LIBRARY = libnwpwlib.a

    USES_BLAS = 

  LIB_DEFINES =  -DNWPW_LIBRARY="'$(SRCDIR)/nwpw/library'"

  LIB_INCLUDES = 

include ../../config/makefile.h
include ../../config/makelib.h









