#
# $Id: GNUmakefile,v 1.3 2002-01-09 01:19:42 edo Exp $
#
 OBJ_OPTIMIZE = nwpw_library.o nwpw_libfile.o


	  OBJ = 

      LIBRARY = libnwpwlib.a

    USES_BLAS = 

  LIB_DEFINES =  -DNWPW_LIBRARY="'$(SRCDIR)/nwpw/libraryps/'"

  LIB_INCLUDES = 

include ../../config/makefile.h
include ../../config/makelib.h









