#
# $Id: GNUmakefile,v 1.2 2001-11-29 18:39:16 bylaska Exp $
#
 OBJ_OPTIMIZE = nwpw_library.o nwpw_libfile.o


	  OBJ = 

      LIBRARY = libnwpwlib.a

    USES_BLAS = 

  LIB_DEFINES =  -DNWPW_LIBRARY="'$(SRCDIR)/nwpw/libraryps'"

  LIB_INCLUDES = 

include ../../config/makefile.h
include ../../config/makelib.h









