#
# $Id$
#

          OBJ = smd_data.o 

      LIBRARY = libsmddb.a
LIB_INCLUDES = -I../include


#  LIB_DEFINES = -DMPI -I$(MPI_INCLUDE)



include ../../config/makefile.h
include ../../config/makelib.h







