#
# $Id: GNUmakefile,v 1.14 2008/05/20 16:59:46 marat Exp $
#

          OBJ = smd_data.o 

      LIBRARY = libsmddb.a
LIB_INCLUDES = -I../include


#  LIB_DEFINES = -DMPI -I$(MPI_INCLUDE)



include ../../config/makefile.h
include ../../config/makelib.h







