#$Id$

OBJ_OPTIMIZE = c1_c1.o  c2_c2.o  cr_eomccsd_t.o cr_eomccsd_t_gr.o t2t12.o  \
               nr0.o c1excit2.o c2excit2.o q3rexpt2.o cr_s_m3.o \
cr_eomccsd_t_n2.o\
cr_eomccsd_t_n2_1.o\
cr_eomccsd_t_n2_1_1.o\
offset_cr_eomccsd_t_n2_1_1.o\
cr_eomccsd_t_n2_1_1_1.o\
offset_cr_eomccsd_t_n2_1_1_1.o\
cr_eomccsd_t_n2_1_1_2.o\
cr_eomccsd_t_n2_1_1_2_1.o\
offset_cr_eomccsd_t_n2_1_1_2_1.o\
cr_eomccsd_t_n2_1_1_2_2.o\
cr_eomccsd_t_n2_1_1_3.o\
cr_eomccsd_t_n2_1_2.o\
cr_eomccsd_t_n2_1_3.o\
cr_eomccsd_t_n2_1_3_1.o\
offset_cr_eomccsd_t_n2_1_3_1.o\
cr_eomccsd_t_n2_1_3_2.o\
cr_eomccsd_t_n2_1_3_2_1.o\
offset_cr_eomccsd_t_n2_1_3_2_1.o\
cr_eomccsd_t_n2_1_3_3.o\
cr_eomccsd_t_n2_1_4.o\
cr_eomccsd_t_n2_1_4_1.o\
offset_cr_eomccsd_t_n2_1_4_1.o\
cr_eomccsd_t_n2_1_5.o\
cr_eomccsd_t_n2_1_5_1.o\
offset_cr_eomccsd_t_n2_1_5_1.o\
cr_eomccsd_t_n2_1_6.o\
cr_eomccsd_t_n2_1_6_1.o\
offset_cr_eomccsd_t_n2_1_6_1.o\
cr_eomccsd_t_n2_1_7.o\
cr_eomccsd_t_n2_1_7_1.o\
offset_cr_eomccsd_t_n2_1_7_1.o\
cr_eomccsd_t_n2_1_7_2.o\
cr_eomccsd_t_n2_1_8.o\
cr_eomccsd_t_n2_1_8_1.o\
offset_cr_eomccsd_t_n2_1_8_1.o\
cr_eomccsd_t_n2_1_8_2.o\
cr_eomccsd_t_n2_1_9.o\
cr_eomccsd_t_n2_2.o\
cr_eomccsd_t_n2_2_1.o\
offset_cr_eomccsd_t_n2_2_1.o\
cr_eomccsd_t_n2_2_1_1.o\
offset_cr_eomccsd_t_n2_2_1_1.o\
cr_eomccsd_t_n2_2_1_2.o\
cr_eomccsd_t_n2_2_1_3.o\
cr_eomccsd_t_n2_2_1_4.o\
cr_eomccsd_t_n2_3.o\
cr_eomccsd_t_n2_3_1.o\
offset_cr_eomccsd_t_n2_3_1.o\
cr_eomccsd_t_n2_3_2.o\
cr_eomccsd_t_n2_3_2_1.o\
offset_cr_eomccsd_t_n2_3_2_1.o\
cr_eomccsd_t_n2_3_3.o\
cr_eomccsd_t_n2_3_3_1.o\
offset_cr_eomccsd_t_n2_3_3_1.o\
cr_eomccsd_t_n2_3_3_2.o\
cr_eomccsd_t_n2_3_4.o\
cr_eomccsd_t_n2_4.o\
cr_eomccsd_t_n2_4_1.o\
offset_cr_eomccsd_t_n2_4_1.o\
cr_eomccsd_t_n2_4_1_1.o\
offset_cr_eomccsd_t_n2_4_1_1.o\
cr_eomccsd_t_n2_4_1_2.o\
cr_eomccsd_t_n2_4_1_2_1.o\
offset_cr_eomccsd_t_n2_4_1_2_1.o\
cr_eomccsd_t_n2_4_1_3.o\
cr_eomccsd_t_n2_4_1_3_1.o\
offset_cr_eomccsd_t_n2_4_1_3_1.o\
cr_eomccsd_t_n2_4_1_4.o\
cr_eomccsd_t_n2_4_2.o\
cr_eomccsd_t_n2_4_2_1.o\
offset_cr_eomccsd_t_n2_4_2_1.o\
cr_eomccsd_t_n2_4_2_2.o\
cr_eomccsd_t_n2_4_2_2_1.o\
offset_cr_eomccsd_t_n2_4_2_2_1.o\
cr_eomccsd_t_n2_4_2_2_2.o\
cr_eomccsd_t_n2_4_2_3.o\
cr_eomccsd_t_n2_4_2_4.o\
cr_eomccsd_t_n2_5.o\
cr_eomccsd_t_n2_5_1.o\
offset_cr_eomccsd_t_n2_5_1.o\
cr_eomccsd_t_n2_5_2.o\
cr_eomccsd_t_n2_5_2_1.o\
offset_cr_eomccsd_t_n2_5_2_1.o\
cr_eomccsd_t_n2_5_2_2.o\
cr_eomccsd_t_n2_5_2_2_1.o\
offset_cr_eomccsd_t_n2_5_2_2_1.o\
cr_eomccsd_t_n2_5_2_2_2.o\
cr_eomccsd_t_n2_5_2_3.o\
cr_eomccsd_t_n2_5_3.o\
cr_eomccsd_t_n2_5_3_1.o\
offset_cr_eomccsd_t_n2_5_3_1.o\
cr_eomccsd_t_n2_5_3_2.o\
cr_eomccsd_t_n2_5_4.o\
cr_eomccsd_t_n2_5_4_1.o\
offset_cr_eomccsd_t_n2_5_4_1.o\
cr_eomccsd_t_n2_5_4_2.o\
cr_eomccsd_t_n2_5_5.o\
cr_eomccsd_t_n2_5_5_1.o\
offset_cr_eomccsd_t_n2_5_5_1.o\
cr_eomccsd_t_n2_5_5_2.o\
cr_eomccsd_t_n2_5_6.o\
cr_eomccsd_t_n2_6.o\
cr_eomccsd_t_n2_6_1.o\
offset_cr_eomccsd_t_n2_6_1.o\
cr_eomccsd_t_n2_6_2.o\
cr_eomccsd_t_n2_6_3.o\
cr_eomccsd_t_n2_6_3_1.o\
offset_cr_eomccsd_t_n2_6_3_1.o\
cr_eomccsd_t_n2_6_3_2.o\
cr_eomccsd_t_n2_6_4.o\
creomccsd_t_n2_mem.o\
q3rexpt2_6dts.o\
creomccsd_t_n2_mem_6dts.o\
cr_eomccsd_t_6dts.o\
cr_ccsd_t_N_6dts.o\
cr_ccsd_t_E_6dts.o\
cr_eomccsd_t_6dts_d4d5_parallel.o

LIB_INCLUDES = -I../include

LIBRARY = libtce.a

USES_BLAS = c1_c1.F c2_c2.F\
c2excit2.F \
cr_eomccsd_t_n2_1_1_2_2.F \
cr_eomccsd_t_n2_1_1_2.F \
cr_eomccsd_t_n2_1_1_3.F \
cr_eomccsd_t_n2_1_1.F \
cr_eomccsd_t_n2_1_2.F \
cr_eomccsd_t_n2_1_3_1.F \
cr_eomccsd_t_n2_1_3_2_1.F \
cr_eomccsd_t_n2_1_3_2.F \
cr_eomccsd_t_n2_1_3_3.F \
cr_eomccsd_t_n2_1_3.F \
cr_eomccsd_t_n2_1_4_1.F \
cr_eomccsd_t_n2_1_4.F \
cr_eomccsd_t_n2_1_5_1.F \
cr_eomccsd_t_n2_1_5.F \
cr_eomccsd_t_n2_1_6_1.F \
cr_eomccsd_t_n2_1_6.F \
cr_eomccsd_t_n2_1_7_2.F \
cr_eomccsd_t_n2_1_7.F \
cr_eomccsd_t_n2_1_8_2.F \
cr_eomccsd_t_n2_1_8.F \
cr_eomccsd_t_n2_1_9.F \
cr_eomccsd_t_n2_1.F \
cr_eomccsd_t_n2_2_1_2.F \
cr_eomccsd_t_n2_2_1_3.F \
cr_eomccsd_t_n2_2_1_4.F \
cr_eomccsd_t_n2_2_1.F \
cr_eomccsd_t_n2_2.F \
cr_eomccsd_t_n2_3_1.F \
cr_eomccsd_t_n2_3_2_1.F \
cr_eomccsd_t_n2_3_2.F \
cr_eomccsd_t_n2_3_3_2.F \
cr_eomccsd_t_n2_3_3.F \
cr_eomccsd_t_n2_3_4.F \
cr_eomccsd_t_n2_3.F \
cr_eomccsd_t_n2_4_1_1.F \
cr_eomccsd_t_n2_4_1_2_1.F \
cr_eomccsd_t_n2_4_1_2.F \
cr_eomccsd_t_n2_4_1_3_1.F \
cr_eomccsd_t_n2_4_1_3.F \
cr_eomccsd_t_n2_4_1_4.F \
cr_eomccsd_t_n2_4_1.F \
cr_eomccsd_t_n2_4_2_2_2.F \
cr_eomccsd_t_n2_4_2_2.F \
cr_eomccsd_t_n2_4_2_3.F \
cr_eomccsd_t_n2_4_2_4.F \
cr_eomccsd_t_n2_4_2.F \
cr_eomccsd_t_n2_4.F \
cr_eomccsd_t_n2_5_2_2_2.F \
cr_eomccsd_t_n2_5_2_2.F \
cr_eomccsd_t_n2_5_2_3.F \
cr_eomccsd_t_n2_5_2.F \
cr_eomccsd_t_n2_5_3_2.F \
cr_eomccsd_t_n2_5_3.F \
cr_eomccsd_t_n2_5_4_2.F \
cr_eomccsd_t_n2_5_4.F \
cr_eomccsd_t_n2_5_5_2.F \
cr_eomccsd_t_n2_5_5.F \
cr_eomccsd_t_n2_5_6.F \
cr_eomccsd_t_n2_5.F \
cr_eomccsd_t_n2_6_2.F \
cr_eomccsd_t_n2_6_3_2.F \
cr_eomccsd_t_n2_6_3.F \
cr_eomccsd_t_n2_6_4.F \
cr_eomccsd_t_n2_6.F \
cr_s_m3.F \
nr0.F \
q3rexpt2.F \
t2t12.F \
creomccsd_t_n2_mem.F \
cr_eomccsd_t.F\
q3rexpt2_6dts.F\
creomccsd_t_n2_mem_6dts.F\
cr_eomccsd_t_6dts.F\
cr_ccsd_t_N_6dts.F\
cr_ccsd_t_E_6dts.F\
cr_eomccsd_t_6dts_d4d5_parallel.F


LIB_DEFINES = -DDEBUG_PRINT
#
# Possible #defines
#
#              -DDEBUG_PRINT          /* Debug printing routines */
#	       -DNOCOMMS              /* Turn off ALL communication calls */
#              -DBLOCK_TRANSF         /* Use block-transfer for comms calls */
#              -DOLD_AOBLOCK          /* Recover original AO blocking scheme */
#

HEADERS = 

include ../../config/makefile.h
include ../../config/makelib.h

