# $Id: GNUmakefile 26876 2015-02-24 06:32:05Z edo $

include ../../config/makefile.h

ifdef USE_SIMINT
    SUBDIRS = libsimint_source
endif
    SUBDIRS += module source



include ../../config/makelib.h



