#
# $Id: GNUmakefile,v 1.25 2004-10-02 02:58:02 d3j191 Exp $
#

  LIBRARY = libnwctask.a
  
  OBJ = task_energy.o task_gradient.o task_optimize.o task_freq.o \
	task_hessian.o task_dynamics.o task_thermo.o task_et.o\
        task_save_state.o task.o task_input.o task_num_grad.o \
        task_vscf.o nxtask.o

USES_BLAS = task_num_grad.F

include ../config/makefile.h
include ../config/makelib.h

