#
# $Id: GNUmakefile,v 1.19 1999-06-04 04:45:19 d3e129 Exp $
#

  LIBRARY = libnwctask.a
  
  OBJ = task_energy.o task_gradient.o task_optimize.o task_freq.o \
	task_hessian.o task_dynamics.o task_thermo.o\
        task_save_state.o task.o task_input.o task_num_grad.o

USES_BLAS = task_num_grad.F

include ../config/makefile.h
include ../config/makelib.h

