#$Id: GNUmakefile,v 1.37 1999-05-24 23:42:47 d3g681 Exp $

 LIBRARY = libutil.a

  OBJ_OPTIMIZE = geom_hnd.o

     OBJ = geom.o geom_input.o geom_input2.o geom_3d.o geom_2d.o geom_1d.o geom_numcore.o \
           geom_checksum.o geom_print_ecce.o

 HEADERS = geom.fh geomP.fh

 USES_BLAS = geom.F geom_input.F geom_print_ecce.F geom_hnd.F

include ../config/makefile.h
include ../config/makelib.h


