#
#        $Id: MakeFile,v 1.5 2003-02-20 22:53:36 edo Exp $
#


OBJ =          $(OBJDIR)\geom.obj \
               $(OBJDIR)\geom_input.obj \
               $(OBJDIR)\geom_input2.obj \
               $(OBJDIR)\geom_3d.obj \
               $(OBJDIR)\geom_2d.obj \
               $(OBJDIR)\geom_1d.obj \
               $(OBJDIR)\geom_hnd.obj \
               $(OBJDIR)\geom_numcore.obj \
               $(OBJDIR)\geom_checksum.obj \
               $(OBJDIR)\geom_freeze.obj \
               $(OBJDIR)\geom_print_ecce.obj

HEADERS =      geom.fh \
               geomP.fh

LIBRARY = nwcutil.lib

!INCLUDE ..\config\NTmakefile.h
!INCLUDE ..\config\NTmakelib.h
