#
# $Id: GNUmakefile,v 1.1 2006-08-13 01:03:24 bylaska Exp $
#

 OBJ_OPTIMIZE = D1dB.o Dne.o Dnex.o
 OBJ = 


      LIBRARY = libnwpwlib.a

    USES_BLAS =

  LIB_DEFINES = 


include ../../../config/makefile.h
include ../../../config/makelib.h



