#$Id$

OBJ = rt_tddft_sodft.o rt_tddft_utils.o rt_tddft_fock_sodft.o xc_exso_mod.o rt_tddft_input.o

OBJ_OPTIMIZE = 

LIBRARY = libnwdft.a

USES_BLAS =

LIB_DEFINES = -DDEBUG_PRINT
LIB_INCLUDES = -I../include -I../../ddscf

HEADERS = 

include ../../config/makefile.h
include ../../config/makelib.h
