#$Id: GNUmakefile,v 1.7 2008-10-10 19:35:05 niri Exp $

OBJ = ehrenfest_sodft.o ehrenfest_utils.o fock_build_utils_so.o xc_exso_mod.o rt_tddft_input.o

OBJ_OPTIMIZE = 

LIBRARY = libnwdft.a

USES_BLAS =

LIB_DEFINES = -DDEBUG_PRINT
LIB_INCLUDES = -I../include -I../../ddscf

HEADERS = 

include ../../config/makefile.h
include ../../config/makelib.h
