#
# $Id: GNUmakefile,v 1.2 2001-11-11 01:29:07 bylaska Exp $
#
     SUBDIRS = APC


 OBJ_OPTIMIZE = \
				analysis_input.o \
				analysis_expansion_coef.o \
				analysis.o \
                orb_pop.o \
                orb.o \
                pspw_Lubin_water_analysis.o 


      LIBRARY = libpspw.a

    USES_BLAS = 

  LIB_DEFINES = 


include ../../../config/makefile.h
include ../../../config/makelib.h

