#
# $Id: GNUmakefile,v 1.5 2004-03-01 05:14:32 bylaska Exp $
#
     SUBDIRS = APC


 OBJ_OPTIMIZE = \
		analysis_input.o \
		analysis_expansion_coef.o \
		analysis.o \
                orb_pop.o \
                orb_pop_kawai.o \
                orb_pop_aorb.o \
                orb.o \
                pspw_Lubin_water_analysis.o 


      LIBRARY = libpspw.a

    USES_BLAS =  pspw_Lubin_water_analysis.F

  LIB_DEFINES = 


include ../../../config/makefile.h
include ../../../config/makelib.h

