#
# $Id: GNUmakefile,v 1.4 2002-10-15 21:24:00 bylaska Exp $
#
     SUBDIRS = APC


 OBJ_OPTIMIZE = \
		analysis_input.o \
		analysis_expansion_coef.o \
		analysis.o \
                orb_pop.o \
                orb.o \
                pspw_Lubin_water_analysis.o 


      LIBRARY = libpspw.a

    USES_BLAS =  pspw_Lubin_water_analysis.F

  LIB_DEFINES = 


include ../../../config/makefile.h
include ../../../config/makelib.h

