#
# $Id: GNUmakefile,v 1.2 2001-11-17 01:01:16 bylaska Exp $
#
      SUBDIRS = minimizer

		OBJ_OPTIMIZE = 	band_energy.o \
						band_gradient.o

          OBJ = band_input.o


      LIBRARY =	libband.a

   USES_BLAS = 

  LIB_INCLUDES = 

  LIB_DEFINES = 




include ../../config/makefile.h
include ../../config/makelib.h









