#
# $Id$
#
      SUBDIRS = minimizer structure cpsd cell_optimize kbpp makepsi lib dplot analysis

		OBJ_OPTIMIZE = 	task_band.o \
				band_energy.o \
				band_noit_energy.o \
				band_gradient.o \
				band_stress.o 

          OBJ = band_input.o


      LIBRARY =	libband.a

   USES_BLAS = 

  LIB_INCLUDES = 

  LIB_DEFINES = 




include ../../config/makefile.h
include ../../config/makelib.h









