#
# $Id$
#

OBJ_CLASS = nwchem.class nwchem_Main.class nwchem_Filter.class \
	nwchem_Task.class nwchem_Job.class nwchem_MD.class \
	nwchem_MD_energy.class nwchem_MD_optimize.class \
	nwchem_MD_dynamics.class nwchem_MD_thermo.class \
        nwchem_Free.class nwchem_Analysis.class nwchem_RMS.class\
	nwchem_Synch.class nwchem_Input.class nwchem_Times.class\
	nwchem_MD_control.class nwchem_Property.class nwchem_Rasmol.class\
        nwchem_NWChem.class nwchem_Socket.class\
        nwchem_Prepare_topology.class nwchem_Prepare_restart.class\
        nwchem_Prepare.class \
	IntegerField.class DoubleField.class Graph.class

CLASS_PATH = .:"$(PTPLOT)"

.SUFFIXES: .f .o .java .class

.java.class:
	javac -classpath $(CLASS_PATH) $<

all:
	$(MAKE) javacheck
	$(MAKE) classes

CLASSDIR = $(NWCHEM_TOP_WIN32)\lib\classes

classes: "$(CLASSDIR)"
	$(MAKE) $(OBJ_CLASS)
	-mv *.class $(CLASSDIR)

javacheck: whichjava.class
	java whichjava || exit 911

"$(CLASSDIR)" :
	@if not exist "$(CLASSDIR)/$(NULL)" mkdir "$(CLASSDIR)"
