#
# $Id: GNUmakefile,v 1.5 2003-01-27 23:50:12 bylaska Exp $
#

 OBJ_OPTIMIZE = \
            coulomb.o \
			coulomb2.o \
			coulomb_screened.o 



	  OBJ = 

      LIBRARY = libpspw.a

    USES_BLAS = coulomb.F coulomb2.F coulomb_screened.F 

  LIB_DEFINES = 


include ../../../../config/makefile.h
include ../../../../config/makelib.h

