#
# $Id$
#

 OBJ_OPTIMIZE = \
            coulomb.o \
			coulomb2.o \
			coulomb_screened.o \
			coulomb_screened_small.o \
			coulomb_filter.o 



	  OBJ = 

      LIBRARY = libpspw.a

    USES_BLAS = coulomb.F coulomb2.F coulomb_screened.F coulomb_screened_small.F

  LIB_DEFINES = 


include ../../../../config/makefile.h
include ../../../../config/makelib.h

