#
# $Id: GNUmakefile,v 1.4 2002-05-07 18:33:05 edo Exp $
#

 OBJ_OPTIMIZE = \
            coulomb.o \
			coulomb2.o \
			coulomb_screened.o



	  OBJ = 

      LIBRARY = libpspw.a

    USES_BLAS = coulomb.F coulomb2.F coulomb_screened.F

  LIB_DEFINES = 


include ../../../../config/makefile.h
include ../../../../config/makelib.h

