# $Id: GNUmakefile,v 1.5 2005-11-09 21:39:31 edo Exp $
  LIBRARY = lib64to32.a
  
  OBJ_OPTIMIZE = yscal.o ycopy.o ydot.o ygemm.o ygemv.o \
                 iyamax.o ygesv.o ygesvd.o yaxpy.o yspsvx.o \
                 yposv.o ysyev.o yger.o yrot.o ylaset.o yswap.o\
                 ygebak.o ygebal.o ynrm2.o ylacpy.o ylascl.o\
                 ylange.o ytrevc.o yhseqr.o yorghr.o ygehrd.o\
                 ysterf.o ylarnv.o ylagtf.o ylagts.o yasum.o \
                 ifily.o\
                 xscal.o xaxpy.o xgemm.o xheev.o


include ../config/makefile.h
include ../config/makelib.h

