# $Id$
  LIBRARY = lib64to32.a
  
  OBJ_OPTIMIZE = yscal.o ycopy.o ydot.o ygemm.o ygemv.o \
                 iyamax.o ygesv.o ygesvd.o yaxpy.o yspsvx.o \
                 yposv.o ysyev.o ysyevd.o yger.o yrot.o ylaset.o yswap.o\
                 ygebak.o ygebal.o ynrm2.o ylacpy.o ylascl.o\
                 ylange.o ytrevc.o yhseqr.o yorghr.o ygehrd.o\
                 ysterf.o ylarnv.o ylagtf.o ylagts.o yasum.o \
                 ypotri.o ypotrf.o ysygv.o ygeev.o ygeevx.o \
                 ygels.o ygelss.o ygtsv.o\
                 ypftrf.o ypftri.o ytfsm.o \
                 ygetrf.o ygetri.o ygetrs.o \
                 ifily.o\
                 jscal.o jaxpy.o jgemm.o jheev.o jcopy.o jdotc.o \
                 ijamax.o jgesvd.o jgeev.o jgetrs.o jgetrf.o \
                 jlacpy.o \
                 ysfrk.o ysysv.o ysytrf.o ysytrs.o ysymm.o ysymv.o \
                 ysyr2k.o ytrmm.o ytrtri.o jlacp2.o \
		 ysyrk.o jsyrk.o jsysv.o jsytrf.o


include ../config/makefile.h
include ../config/makelib.h

sngl_to_dbl dbl_to_sngl 64_to_32 32_to_64:
	@echo No blas conversion done here
