#
# $Id: GNUmakefile,v 1.1 2002-01-12 07:00:36 zzhang Exp $
#


LIBRARY = libcckohn.a 

BLAS     = 
OBJ = cckohn.o cckohn_input.o\

OBJ_OPTIMIZE = 

USES_BLAS = 

SUBDIRS = bessel

include ../config/makefile.h
include ../config/makelib.h

