#
# $Id$
#

LIBRARY = libcckohn.a 

BLAS     = 
OBJ = cckohn.o cckohn_input.o cknew.o obftrans.o hbftrans.o \
	bforthog.o fforth1.o fforth2.o denom.o top.o
OBJ_OPTIMIZE = 

USES_BLAS = 

SUBDIRS = bessel

include ../config/makefile.h
include ../config/makelib.h
