#$Id: GNUmakefile,v 1.9 1999-08-20 18:44:41 d3e129 Exp $
# makefile,v 1.8 1994/12/05 20:37:08 og845 Exp

   OBJ = dplot.o get_grid.o create_contour.o dmat.o errmem.o \
         get_dens.o rhogen.o dplot_input.o get_charges.o 

   LIBRARY = libdplot.a
 USES_BLAS = dplot.F dmat.F create_contour.F rhogen.F get_charges.F 


include ../config/makefile.h
include ../config/makelib.h


