#
# $Id: GNUmakefile,v 1.10 2004-05-06 21:11:50 edo Exp $
#

 OBJ_OPTIMIZE =  task_chelp.o
       SUBDIRS = grid

LIBRARY=libchelp.a

HEADERS=

include ../config/makefile.h

include ../config/makelib.h
