
# $Id: GNUmakefile,v 1.3 2003-09-25 02:10:05 bylaska Exp $
#
 OBJ_OPTIMIZE = \
		paw_psi.o \
		paw_psi_new.o \
		paw_psi_H.o



	  OBJ = 



      LIBRARY = libpaw.a

    USES_BLAS = 

  LIB_DEFINES =


include ../../../config/makefile.h
include ../../../config/makelib.h
include ../makefile.h
