
# $Id$
#
 OBJ_OPTIMIZE = \
		paw_psi.o \
		paw_psi2.o \
		paw_psi_new.o \
		paw_psi_H.o \
		paw_electron.o \
		paw_geodesic.o



	  OBJ = 



      LIBRARY = libpaw.a

    USES_BLAS =  paw_psi.F  paw_geodesic.F paw_electron.F paw_psi2.F

  LIB_DEFINES =


include ../../../config/makefile.h
include ../../../config/makelib.h
include ../makefile.h
