
# $Id: GNUmakefile,v 1.1 2003-02-11 20:48:33 bylaska Exp $
#
 OBJ_OPTIMIZE = \
		paw_psi.o 



	  OBJ = 



      LIBRARY = libpaw.a

    USES_BLAS = 

  LIB_DEFINES =


include ../../../config/makefile.h
include ../../../config/makelib.h
include ../makefile.h
