
# $Id: GNUmakefile,v 1.2 2001-10-31 17:33:35 bylaska Exp $
#
# intf and aux break on IBM SP xlhpf with optimization ... why? 
 OBJ_OPTIMIZE = \
                model_potential.o 

	  OBJ = 


      LIBRARY = libpspw.a

    USES_BLAS = model_potential.F
                
  LIB_DEFINES =


include ../../../../config/makefile.h
include ../../../../config/makelib.h

