#
# $Id$
#
 OBJ_OPTIMIZE = \
                model_potential.o 

	  OBJ = 


      LIBRARY = libpspw.a

    USES_BLAS = model_potential.F
                
  LIB_DEFINES =


include ../../../../config/makefile.h
include ../../../../config/makelib.h

