# $Id$
  LIBRARY = libbq.a
  
  OBJ = bq_input.o bq_data.o bq_rtdb.o bq_main.o bq_force.o bq_checksum.o

  USES_BLAS = bq_input.F
 
 

HEADERS = bq.fh bq_params.fh

include ../config/makefile.h
include ../config/makelib.h

