# $Id: GNUmakefile,v 1.5 2008-04-22 21:59:58 niri Exp $
  LIBRARY = libbq.a
  
  OBJ = bq_input.o bq_data.o bq_rtdb.o bq_main.o

  USES_BLAS = bq_input.F
 
 

HEADERS = bq.fh bq_params.fh

include ../config/makefile.h
include ../config/makelib.h

