# $Id: GNUmakefile,v 1.3 2005-03-31 03:20:30 marat Exp $
  LIBRARY = libbq.a
  
  OBJ = bq_input.o bq_data.o bq_rtdb.o bq_main.o
 
 

HEADERS = bq.fh

include ../config/makefile.h
include ../config/makelib.h

