#$Id$

   LIBRARY = libnwdft.a

   OBJ = dft_cscf.o \
         dft_cg_answer.o \
         dft_cg_info.o \
         dft_cg_guess.o \
         dft_cg_solve.o \
         dft_get_conv_info.o \
         dft_roks_energy.o \
         dft_roks_fock.o \
         dft_roks_hessv_2e.o \
         dft_roks_hessv.o \
         dft_roks_hessv_xx.o \
         dft_roks_nr_solve.o \
         dft_roks_search_precond.o \
         dft_roks_step_energy.o \
         dft_uks_energy.o \
         dft_uks_hessv_2e.o \
         dft_uks_hessv.o \
         dft_uks_nr_solve.o \
         dft_uks_search_precond.o \
         dft_uks_step_energy.o 

 LIB_DEFINES =

   SUBDIRS = 
LIB_INCLUDES = -I../include -I../grid

HEADERS = ../../ddscf/cosmo.fh ../../ddscf/frozemb.fh

include ../../config/makefile.h
include ../../config/makelib.h
