#$Id: GNUmakefile,v 1.1 2003-09-16 21:54:01 sohirata Exp $

OBJ_OPTIMIZE = cisdtq_e.o cisdtq_c1.o cisdtq_c2.o cisdtq_c3.o \
cisdtq_c4.o\
cisdtq_c4_1.o\
cisdtq_c4_2.o\
cisdtq_c4_3.o\
cisdtq_c4_4.o\
cisdtq_c4_5.o\
cisdtq_c4_6.o\
cisdtq_c4_7.o\
cisdtq_c4_8.o\
cisdtq_c4_9.o\
cisdtq_c4_10.o

LIB_INCLUDES = -I../include

LIBRARY = libtce.a

USES_BLAS = 

LIB_DEFINES = -DDEBUG_PRINT
#
# Possible #defines
#
#              -DDEBUG_PRINT          /* Debug printing routines */
#	       -DNOCOMMS              /* Turn off ALL communication calls */
#              -DBLOCK_TRANSF         /* Use block-transfer for comms calls */
#              -DOLD_AOBLOCK          /* Recover original AO blocking scheme */
#

HEADERS = 

include ../../config/makefile.h
include ../../config/makelib.h

