#$Id: GNUmakefile 25209 2014-02-02 18:41:05Z niri $
# makefile,v 1.8 1994/12/05 20:37:08 og845 Exp

   OBJ = wfn1.o \
         wfn1_allocate_drv.o \
         wfn1_allocate_mat.o \
         wfn1_allocate_wfn.o \
         wfn1_configuration.o \
         wfn1_dnrm2.o \
         wfn1_e_g.o \
         wfn1_exp.o \
         wfn1_gen_mat.o \
         wfn1_guess_corr.o \
         wfn1_lindep.o \
         wfn1_linesearch.o \
         wfn1_size.o \
         wfn1_trace.o

   LIBRARY = librdmft.a

 LIB_DEFINES =

   SUBDIRS = 
LIB_INCLUDES = 

HEADERS = 

include ../config/makefile.h
include ../config/makelib.h
