#
# $Id: GNUmakefile,v 1.2 2001-08-30 17:57:13 bylaska Exp $
#
 SUBDIRS = shake

 OBJ_OPTIMIZE = \
            center.o \
			ion_FixIon.o \
            incell1.o \
            incell3.o \
			xyz.o \
            ion.o \
            fcoord.o \
			ewald.o


	  OBJ = 

      LIBRARY = libnwpwlib.a

    USES_BLAS = ion.F fcoord.f ewald.F

  LIB_DEFINES = 


include ../../../config/makefile.h
include ../../../config/makelib.h

