#
# $Id: GNUmakefile,v 1.8 2001-12-13 03:49:53 bylaska Exp $
#
 SUBDIRS = shake

 OBJ_OPTIMIZE = \
            center.o \
			ion_FixIon.o \
            incell1.o \
            incell3.o \
			xyz.o \
            ion.o \
			katm_list.o \
            fcoord.o \
			ewald.o \
			seperate_molpsp.o \
			seperate_pointcharge.o


	  OBJ = 

      LIBRARY = libnwpwlib.a

    USES_BLAS = ion.F fcoord.f ewald.F

  LIB_DEFINES = 


include ../../../config/makefile.h
include ../../../config/makelib.h

