#
# $Id: GNUmakefile,v 1.20 1999-11-02 18:27:45 d3j191 Exp $
#

include ../config/makefile.h

OBJ_OPTIMIZE=prepar.o\
             pre_align.o\
             pre_ang.o\
             pre_atmscn.o\
             pre_atnam.o\
             pre_atnum.o\
             pre_atrad.o\
             pre_atype.o\
             pre_bnd.o\
             pre_boxsiz.o\
             pre_center.o\
             pre_charge.o\
             pre_check.o\
             pre_dih.o\
             pre_dihimp.o\
             pre_dihsel.o\
             pre_dimens.o\
             pre_disres.o\
             pre_excl.o\
             pre_ffield.o\
             pre_fix.o\
             pre_frgsiz.o\
             pre_frgrd.o\
             pre_gensgm.o\
             pre_hnames.o\
             pre_imp.o\
             pre_impctr.o\
             pre_input.o\
             pre_links.o\
             pre_misfit.o\
             pre_mkfrg.o\
             pre_mklist.o\
             pre_mknoe.o\
             pre_mkrst.o\
             pre_mkseq.o\
             pre_mksgm.o\
             pre_mktop.o\
             pre_modify.o\
             pre_namiup.o\
             pre_natyps.o\
             pre_nonbon.o\
             pre_nucleic.o\
             pre_orient.o\
             pre_params.o\
             pre_parcnv.o\
             pre_pdbseq.o\
             pre_pdbsiz.o\
             pre_protein.o\
             pre_rdgeom.o\
             pre_rdpdb.o\
             pre_rdrst.o\
             pre_rdseq.o\
             pre_rdsgm.o\
             pre_rename.o\
             pre_repeat.o\
             pre_rotate.o\
             pre_rstsiz.o\
             pre_rtdbin.o\
             pre_rtdbsq.o\
             pre_select.o\
             pre_seqsiz.o\
             pre_sgmfil.o\
             pre_sgmndx.o\
             pre_sgmnum.o\
             pre_sgmsiz.o\
             pre_short.o\
             pre_slvnum.o\
             pre_slvrd.o\
             pre_slvsiz.o\
             pre_solvat.o\
             pre_task.o\
             pre_term.o\
             pre_third.o\
             pre_toprd.o\
             pre_topsiz.o\
             pre_torang.o\
             pre_wrtnam.o\
             pre_wrtnoe.o\
             pre_wrtpdb.o\
             pre_wrtpmf.o\
             pre_wrtrst.o\
             pre_wrtseq.o\
             pre_wrtsgm.o\
             pre_wrttop.o\
             pre_wrtxyz.o

LIBRARY=libprepar.a

HEADERS=

USES_BLAS=

include ../config/makelib.h

# DO NOT DELETE







