 OBJ_OPTIMIZE = aoccsd2.o \
		ccsd_itm.o \
		ccsd_t2pm.o \
		ccsd_pampt3.o \
		ccsd_itf.o \
		ccsd.o \
		ccsd_aux.o \
		ccsd_driver.o \
		ccsd_fsig1.o \
		ccsd_fsig2.o \
		ccsd_get_param.o \
		ccsd_iterdrv2.o \
		ccsd_mktau.o \
		ccsd_mktask.o \
		ccsd_mkt2.o \
		ccsd_pampt2.o \
		ccsd_pdiis.o \
		ccsd_sortmo.o \
		ccsd_rdtrpo.o \
		ccsd_tengy.o \
		ccsd_trpdrv.o \
		moints_trp.o \
		qstat.o \
		cputime.o \
		rddcom.o \
		ccsd_input.o

    LIBRARY = libccsd.a

  USES_BLAS = \
	      ccsd_itm.F \
	      ccsd_t2pm.F \
	      ccsd_fsig1.f \
	      ccsd_fsig2.f \
	      ccsd_iterdrv2.f \
	      ccsd_pampt2.F \
	      ccsd_pampt3.F \
	      ccsd_pdiis.f \
	      ccsd_sortmo.F \
	      ccsd_trpdrv.f \
	      moints_trp.F



LIB_DEFINES = 

#
#


include ../config/makefile.h
include ../config/makelib.h
