#
# $Id: GNUmakefile,v 1.1 2004-11-29 16:05:18 bylaska Exp $
#
 OBJ_OPTIMIZE = \
				paw_stress_numerical.o \
				paw_stress_fd.o \
				paw_cell_optimize.o \
				paw_update_unitcell.o
                
	  OBJ = 


      LIBRARY = libpaw.a

    USES_BLAS = 
                

  LIB_DEFINES =


include ../../../config/makefile.h
include ../../../config/makelib.h

