#
# $Id: GNUmakefile,v 1.2 2006-06-05 17:34:23 edo Exp $
#
 OBJ_OPTIMIZE = \
				paw_stress_numerical.o \
				paw_stress_fd.o \
				paw_cell_optimize.o \
				paw_update_unitcell.o
                
	  OBJ = 


      LIBRARY = libpaw.a

    USES_BLAS = paw_stress_fd.F
                

  LIB_DEFINES =


include ../../../config/makefile.h
include ../../../config/makelib.h

