#
# $Id: GNUmakefile,v 1.1 2007-07-24 01:42:50 bylaska Exp $
#

 OBJ_OPTIMIZE = \
            v_thomasfermi.o



	  OBJ = 

      LIBRARY = libofpw.a

    USES_BLAS = v_thomasfermi.F

  LIB_DEFINES = 


include ../../../../config/makefile.h
include ../../../../config/makelib.h

