#
# $Id: GNUmakefile,v 1.1 2001-08-30 00:35:12 edo Exp $
#
# intf and aux break on IBM SP xlhpf with optimization ... why? 

 OBJ_OPTIMIZE = \
            ke.o



	  OBJ = 

      LIBRARY = libpspw.a

    USES_BLAS = ke.F

  LIB_DEFINES = 


include ../../../../config/makefile.h
include ../../../../config/makelib.h

