#
# $Id$
#

 OBJ_OPTIMIZE = \
            	ke.o

	  OBJ = 

      LIBRARY = libpspw.a

    USES_BLAS = ke.F

  LIB_DEFINES = 


include ../../../../config/makefile.h
include ../../../../config/makelib.h

