#
# $Id: GNUmakefile,v 1.4 2004-05-14 16:39:49 edo Exp $
#

          OBJ_OPTIMIZE =  paw_energy_vloc_atom.o paw_matrix_vloc.o paw_vloc.o
          HEADERS = paw_energy_vloc_atom.fh



      LIBRARY =	libpaw.a

   USES_BLAS =  paw_vloc.F

  LIB_INCLUDES =

  LIB_DEFINES = 




include ../../../config/makefile.h
include ../../../config/makelib.h


