#
# $Id: GNUmakefile,v 1.1 2003-02-11 22:42:14 marat Exp $
#

          OBJ =  paw_energy_vloc_atom.o paw_matrix_vloc.o
          HEADERS = paw_energy_vloc_atom.fh



      LIBRARY =	libpaw.a

   USES_BLAS = 

  LIB_INCLUDES =

  LIB_DEFINES = 




include ../../../config/makefile.h
include ../../../config/makelib.h


