#!/bin/csh 
@ count = 1
while ($count)
  if ($count < 10) then
     if (-e prog.00${count}) then
        echo "mv prog.00${count} prog.00${count}.ps"
        mv prog.00${count} prog.00${count}.ps
        @ count++
     else
        @ count = 0
     endif
  else if ($count < 100) then
     if (-e prog.0${count}) then
        echo "mv prog.0${count} prog.0${count}.ps"
        mv prog.0${count} prog.0${count}.ps
        @ count++
     else
        @ count = 0
     endif
  else if ($count < 1000) then
     if (-e prog.${count}) then
        echo "mv prog.${count} prog.${count}.ps"
        mv prog.${count} prog.${count}.ps
        @ count++
     else
        @ count = 0
     endif
  else
    echo "count value of $count requires a fix in progpsfix"
    exit 911
  endif
end
