# $Id: GNUmakefile,v 1.3 1994-06-09 05:31:17 d3g681 Exp $

      OBJ = atcond.o    denat.o        hamild.o    outpud.o    teigd.o \
            atomd.o     denmad.o       jacod.o     pdfded.o    tracd.o \
            cmergd.o    densid.o       oeigd.o     shalfd.o    trafsd.o \
            creded.o    orderd.o       square.o    tramad.o \
            datoms.o    guess_mem.o    starcd.o    writel.o

  USES_BLAS = atomd.F


  LIBRARY = libguess.a


include ../config/makefile.h
include ../config/makelib.h

$(OBJ):	cguess.fh
