#
# $Id$
#

 OBJ_OPTIMIZE =  chelp_grid.o\
                 chelp_atom_rad.o\
                 chelp_grid_data.o

USES_BLAS = chelp_grid.F chelp_grid_data.F

LIBRARY=libchelp.a

HEADERS=

include ../../config/makefile.h

include ../../config/makelib.h
