#
# $Id: GNUmakefile,v 1.10 2004-05-06 21:11:50 edo Exp $
#

 OBJ_OPTIMIZE =  chelp_grid.o\
                 chelp_atom_rad.o\
                 chelp_grid_data.o

LIBRARY=libchelp.a

HEADERS=

include ../../config/makefile.h

include ../../config/makelib.h
