#
# $Id$
#

OBJ = gg.o outward.o sjymec.o cckohn_spline.o splinec.o ubesplg.o\
	zero.o

OBJ_OPTIMIZE = 

LIBRARY = libcckohn.a

USES_BLAS = 

include ../../config/makefile.h
include ../../config/makelib.h

