#
# $Id: GNUmakefile,v 1.3 2002-01-14 07:45:05 edo Exp $
#

OBJ = gg.o outward.o sjymec.o spline.o splinec.o ubesplg.o\
	zero.o

OBJ_OPTIMIZE = 

LIBRARY = libcckohn.a

USES_BLAS = 

include ../../config/makefile.h
include ../../config/makelib.h

