#
# $Id: GNUmakefile,v 1.4 2003-04-08 00:21:34 windus Exp $
#

OBJ = gg.o outward.o sjymec.o cckohn_spline.o splinec.o ubesplg.o\
	zero.o

OBJ_OPTIMIZE = 

LIBRARY = libcckohn.a

USES_BLAS = 

include ../../config/makefile.h
include ../../config/makelib.h

