# $Id: GNUmakefile,v 1.3 2015/04/06 05:38:33 D3Y133 Exp D3Y133 $

         LIBRARY = libwfn1.a

    OBJ_OPTIMIZE = \
		   wfn1_d_matfunc.o wfn1_engrad.o wfn1_1el.o wfn1_2el.o wfn1_entropy.o \
                   wfn1_l1.o wfn1_l2.o wfn1_l3.o wfn1_norm.o wfn1_1el_ints.o \
                   wfn1_1el_orb.o wfn1_2el_ints.o wfn1_2el_orb.o \
                   wfn1_energy_doit.o wfn1_energy_num_doit.o wfn1_exp.o \
                   wfn1_energy.o wfn1_update.o wfn1_occ_natorb.o wfn1_occ.o \
                   wfn1_engradocc.o wfn1_energyocc_num_doit.o wfn1_s2.o  wfn1_mat_power.o \
                   wfn1_order.o wfn1_factorial.o wfn1_permutation_table.o \
                   wfn1_calc_sign.o wfn1_overlap.o wfn1_ovlp_2_states.o \
		   wfn1_swap.o wfn1_swap_vectors.o wfn1_unitarize.o \
		   wfn1_f0df0f1.o wfn1_f1f2f3.o wfn1_linesearch.o \
		   wfn1_insert.o wfn1_closest_three.o wfn1_idmin.o \
		   wfn1_xc.o wfn1_engrad_ana.o wfn1_overlap_ldr.o \
		   wfn1_add_dmat.o wfn1_LR2d.o wfn1_match_occ.o  \
		   wfn1_2el_orb_self.o \
                   wfn1_nxt_energy.o wfn1_nxt_energy_gradient.o \
                   wfn1_nxt_min_energy.o wfn1_nxt_init_state.o \
                   wfn1_nxt_init_occ.o wfn1_nxt_linesearch.o \
                   wfn1_nxt_dot.o wfn1_nxt_1el_eg.o wfn1_nxt_2el_C_eg.o \
                   wfn1_nxt_2el_X_eg.o wfn1_nxt_gradient_to_search.o \
                   wfn1_nxt_Ln_eg.o wfn1_nxt_Lo_eg.o wfn1_nxt_print_state.o \
		   wfn1_nxt_Pn_eg.o wfn1_nxt_Po_eg.o wfn1_nxt_prep_grad.o \
                   wfn1_nxt2_1el_ef.o wfn1_nxt2_2el_C_ef.o wfn1_nxt2_2el_X_ef.o \
                   wfn1_nxt2_fg.o wfn1_nxt2_sym_2_skw.o wfn1_nxt2_energy.o \
                   wfn1_nxt2_energy_gradient.o wfn1_nxt2_linesearch_e.o \
                   wfn1_nxt2_min_energy.o wfn1_nxt2_step.o wfn1_nxt2_ov12.o \
		   wfn1_d_dlaisnan.o wfn1_nxt_print_occ.o wfn1_nxt_print_overlap.o \
		   wfn1_nxt2_min_gradient.o wfn1_nxt2_linesearch_g.o \
		   wfn1_nxt2_canon_occ.o wfn1_nxt2_sort_columns.o \
		   wfn1_nxt2_sort_diag.o wfn1_nxt2_init_state.o \
		   wfn1_nxt2_print_state.o wfn1_nxt2_min_excit.o \
		   wfn1_nxt2_step_g.o wfn1_nxt2_residual.o \
		   wfn1_nxt2_step_r.o wfn1_nxt2_gershgorin.o \
		   wfn1_nxt2_step_excit.o wfn1_nxt2_sort_overlap.o \
		   dsyev_nsrt.o dsterf_nsrt.o dsteqr_nsrt.o \
		   wfn1_nxt2_1el_n_ef.o wfn1_nxt2_2el_n_C_ef.o \
		   wfn1_nxt2_2el_n_X_ef.o wfn1_nxt2_n_fg.o wfn1_nxt_fermi.o \
		   wfn1_nxt2_init_occ_fermi.o wfn1_nxt_init_occ_one.o \
		   wfn1_nxt2_hf_fock.o wfn1_nxt2_enumerate.o \
		   wfn1_nxt2_print_occ.o

             OBJ = 

         HEADERS =

     LIB_TARGETS = 

       TEST_LIBS = $(LIBRARY) $(LIBS) 

       USES_BLAS =  

include ../config/makefile.h
include ../config/makelib.h
