#
# $Id: GNUmakefile 24447 2013-07-27 00:39:06Z bylaska $
#

  OBJ_OPTIMIZE = wgc.o
  OBJ =

      LIBRARY = libofpw.a

    USES_BLAS = wgc.F

  LIB_DEFINES = 


include ../../../../config/makefile.h
include ../../../../config/makelib.h

