#
# $Id: GNUmakefile,v 1.2 2002-02-16 01:03:08 bylaska Exp $
#

 OBJ_OPTIMIZE = \
            psi_H.o \
            psi_Hv4.o \
            electron.o



	  OBJ = 

      LIBRARY = libpspw.a

    USES_BLAS = electron.F psi_H.F

  LIB_DEFINES = 


include ../../../../config/makefile.h
include ../../../../config/makelib.h

