#
# $Id: GNUmakefile,v 1.1 2001-08-30 00:33:39 edo Exp $
#
# intf and aux break on IBM SP xlhpf with optimization ... why? 

 OBJ_OPTIMIZE = \
            psi_H.o \
            psi_Hv4.o \
            electron.o



	  OBJ = 

      LIBRARY = libpspw.a

    USES_BLAS = electron.F psi_H.F

  LIB_DEFINES = 


include ../../../../config/makefile.h
include ../../../../config/makelib.h

