#
# $Id$
#

 OBJ_OPTIMIZE = \
            psi_H.o \
            psi_Hv4.o \
            electron.o



	  OBJ = 

      LIBRARY = libpspw.a

    USES_BLAS = electron.F psi_H.F psi_Hv4.F

  LIB_DEFINES = 


include ../../../../config/makefile.h
include ../../../../config/makelib.h

