#
# $Id: GNUmakefile,v 1.13 2003-02-11 22:45:34 bylaska Exp $
#
      SUBDIRS = paw_geometry  paw_ma paw_utils paw_basis paw_proj paw_matrix paw_ovlp \
                paw_comp_charge paw_special_functions paw_gaunt paw_kinetic paw_vloc \
                paw_ion_potential paw_core cpsd

          OBJ = task_paw.o


      LIBRARY =	libpaw.a

   USES_BLAS = 

  LIB_INCLUDES =

  LIB_DEFINES = 




include ../../config/makefile.h
include ../../config/makelib.h
include makefile.h










