#
# $Id: GNUmakefile,v 1.4 2002-08-01 01:18:27 bylaska Exp $
#
      SUBDIRS = cpsd paw_basis paw_utils paw_matrix paw_proj

          OBJ = task_paw.o


      LIBRARY =	libpaw.a

   USES_BLAS = 

  LIB_INCLUDES = -I./include

  LIB_DEFINES = 




include ../../config/makefile.h
include ../../config/makelib.h
include makefile.h









