#
# $Id: GNUmakefile,v 1.9 2003-02-11 00:24:22 marat Exp $
#
      SUBDIRS = paw_geometry  paw_ma cpsd paw_basis paw_utils paw_proj paw_matrix paw_ovlp \
                paw_comp_charge paw_special_functions paw_gaunt paw_kinetic

          OBJ = task_paw.o


      LIBRARY =	libpaw.a

   USES_BLAS = 

  LIB_INCLUDES =

  LIB_DEFINES = 




include ../../config/makefile.h
include ../../config/makelib.h
include makefile.h










