#
# $Id$
#

 OBJ_OPTIMIZE = \
            	nwpwxc_vdw3a.o \
            	nwpwxc_vdw3b.o \
            	nwpwxc_vdw3c.o 

	  OBJ = nwpwxc_vdw3d.o 

      LIBRARY = libnwpwlib.a

    USES_BLAS = nwpwxc_vdw3a.F nwpwxc_vdw3c.F

  LIB_DEFINES = 


include ../../../config/makefile.h
include ../../../config/makelib.h

