#
# $Id$
#
 OBJ_OPTIMIZE = \
				c_wvfnc_new.o \
				c_wvfnc_expander.o \
				c_wvfnc_adjust.o \
				c_v_wvfnc_new.o \
				pspw_reformat_c_wvfnc.o
                

    LIBRARY = libband.a

    USES_BLAS = pspw_reformat_c_wvfnc.F c_wvfnc_new.F c_wvfnc_expander.F c_v_wvfnc_new.F c_wvfnc_adjust.F
                

  LIB_DEFINES =


include ../../../config/makefile.h
include ../../../config/makelib.h

