#
# $Id: GNUmakefile,v 1.3 2002-02-11 18:27:11 edo Exp $
#
 OBJ_OPTIMIZE = \
				c_wvfnc_new.o \
				pspw_reformat_c_wvfnc.o
                

    LIBRARY = libband.a

    USES_BLAS = pspw_reformat_c_wvfnc.F
                

  LIB_DEFINES =


include ../../../config/makefile.h
include ../../../config/makelib.h

