#
# $Id: GNUmakefile 25011 2013-12-19 17:45:25Z d3y133 $
#

 OBJ_OPTIMIZE =

	  OBJ =  feff6Lib.o

      LIBRARY = libnwpwlib.a

    USES_BLAS = 

  LIB_DEFINES = 


include ../../../../config/makefile.h
include ../../../../config/makelib.h

