#$Id$

OBJ_OPTIMIZE = ccsdt_e.o ccsdt_t1.o ccsdt_t2.o ccsdt_t3.o \
               ccsdt_t1a.o ccsdt_t2a.o ccsdt_t3a.o \
ccsdt_t3_1.o\
ccsdt_t3_1_1.o\
OFFSET_ccsdt_t3_1_1.o\
ccsdt_t3_1_2.o\
ccsdt_t3_1_2_1.o\
OFFSET_ccsdt_t3_1_2_1.o\
ccsdt_t3_1_2_2.o\
ccsdt_t3_1_2_2_1.o\
OFFSET_ccsdt_t3_1_2_2_1.o\
ccsdt_t3_1_2_2_2.o\
ccsdt_t3_1_2_3.o\
ccsdt_t3_1_3.o\
ccsdt_t3_1_3_1.o\
OFFSET_ccsdt_t3_1_3_1.o\
ccsdt_t3_1_3_2.o\
ccsdt_t3_1_4.o\
ccsdt_t3_1_4_1.o\
OFFSET_ccsdt_t3_1_4_1.o\
ccsdt_t3_1_4_2.o\
ccsdt_t3_1_5.o\
ccsdt_t3_1_5_1.o\
OFFSET_ccsdt_t3_1_5_1.o\
ccsdt_t3_1_5_2.o\
ccsdt_t3_1_6.o\
ccsdt_t3_1_7.o\
ccsdt_t3_2.o\
ccsdt_t3_2_1.o\
OFFSET_ccsdt_t3_2_1.o\
ccsdt_t3_2_2.o\
ccsdt_t3_2_3.o\
ccsdt_t3_2_3_1.o\
OFFSET_ccsdt_t3_2_3_1.o\
ccsdt_t3_2_3_2.o\
ccsdt_t3_2_4.o\
ccsdt_t3_2_5.o\
ccsdt_t3_3.o\
ccsdt_t3_3_1.o\
OFFSET_ccsdt_t3_3_1.o\
ccsdt_t3_3_2.o\
ccsdt_t3_3_2_1.o\
OFFSET_ccsdt_t3_3_2_1.o\
ccsdt_t3_3_2_2.o\
ccsdt_t3_3_3.o\
ccsdt_t3_3_4.o\
ccsdt_t3_4.o\
ccsdt_t3_4_1.o\
OFFSET_ccsdt_t3_4_1.o\
ccsdt_t3_4_2.o\
ccsdt_t3_4_3.o\
ccsdt_t3_5.o\
ccsdt_t3_5_1.o\
OFFSET_ccsdt_t3_5_1.o\
ccsdt_t3_5_2.o\
ccsdt_t3_5_2_1.o\
OFFSET_ccsdt_t3_5_2_1.o\
ccsdt_t3_5_2_2.o\
ccsdt_t3_5_3.o\
ccsdt_t3_6.o\
ccsdt_t3_6_1.o\
OFFSET_ccsdt_t3_6_1.o\
ccsdt_t3_6_2.o\
ccsdt_t3_6_3.o\
ccsdt_t3_7.o\
ccsdt_t3_8.o\
ccsdt_t3_8_1.o\
OFFSET_ccsdt_t3_8_1.o\
ccsdt_t3_8_1_1.o\
OFFSET_ccsdt_t3_8_1_1.o\
ccsdt_t3_8_1_2.o\
ccsdt_t3_8_1_2_1.o\
OFFSET_ccsdt_t3_8_1_2_1.o\
ccsdt_t3_8_1_2_2.o\
ccsdt_t3_8_1_3.o\
ccsdt_t3_8_1_4.o\
ccsdt_t3_8_2.o\
ccsdt_t3_8_2_1.o\
OFFSET_ccsdt_t3_8_2_1.o\
ccsdt_t3_8_2_2.o\
ccsdt_t3_8_3.o\
ccsdt_t3_8_3_1.o\
OFFSET_ccsdt_t3_8_3_1.o\
ccsdt_t3_8_3_2.o\
ccsdt_t3_8_4.o\
ccsdt_t3_8_5.o\
ccsdt_t3_8_5_1.o\
OFFSET_ccsdt_t3_8_5_1.o\
ccsdt_t3_9.o\
ccsdt_t3_9_1.o\
OFFSET_ccsdt_t3_9_1.o\
ccsdt_t3a_1.o\
ccsdt_t3a_1_1.o\
OFFSET_ccsdt_t3a_1_1.o\
ccsdt_t3a_1_2.o\
ccsdt_t3a_1_2_1.o\
OFFSET_ccsdt_t3a_1_2_1.o\
ccsdt_t3a_1_2_2.o\
ccsdt_t3a_1_2_2_1.o\
OFFSET_ccsdt_t3a_1_2_2_1.o\
ccsdt_t3a_1_2_2_2.o\
ccsdt_t3a_1_2_3.o\
ccsdt_t3a_1_3.o\
ccsdt_t3a_1_3_1.o\
OFFSET_ccsdt_t3a_1_3_1.o\
ccsdt_t3a_1_3_2.o\
ccsdt_t3a_1_4.o\
ccsdt_t3a_1_4_1.o\
OFFSET_ccsdt_t3a_1_4_1.o\
ccsdt_t3a_1_4_2.o\
ccsdt_t3a_1_5.o\
ccsdt_t3a_1_5_1.o\
OFFSET_ccsdt_t3a_1_5_1.o\
ccsdt_t3a_1_5_2.o\
ccsdt_t3a_1_6.o\
ccsdt_t3a_1_7.o\
ccsdt_t3a_2.o\
ccsdt_t3a_2_1.o\
OFFSET_ccsdt_t3a_2_1.o\
ccsdt_t3a_2_2.o\
ccsdt_t3a_2_3.o\
ccsdt_t3a_2_3_1.o\
OFFSET_ccsdt_t3a_2_3_1.o\
ccsdt_t3a_2_3_2.o\
ccsdt_t3a_2_4.o\
ccsdt_t3a_2_5.o\
ccsdt_t3a_3.o\
ccsdt_t3a_3_1.o\
OFFSET_ccsdt_t3a_3_1.o\
ccsdt_t3a_3_2.o\
ccsdt_t3a_3_2_1.o\
OFFSET_ccsdt_t3a_3_2_1.o\
ccsdt_t3a_3_2_2.o\
ccsdt_t3a_3_3.o\
ccsdt_t3a_3_4.o\
ccsdt_t3a_4.o\
ccsdt_t3a_4_1.o\
OFFSET_ccsdt_t3a_4_1.o\
ccsdt_t3a_4_2.o\
ccsdt_t3a_4_3.o\
ccsdt_t3a_5.o\
ccsdt_t3a_5_1.o\
OFFSET_ccsdt_t3a_5_1.o\
ccsdt_t3a_5_2.o\
ccsdt_t3a_5_2_1.o\
OFFSET_ccsdt_t3a_5_2_1.o\
ccsdt_t3a_5_2_2.o\
ccsdt_t3a_5_3.o\
ccsdt_t3a_6.o\
ccsdt_t3a_6_1.o\
OFFSET_ccsdt_t3a_6_1.o\
ccsdt_t3a_6_2.o\
ccsdt_t3a_6_3.o\
ccsdt_t3a_7.o\
ccsdt_t3a_8.o\
ccsdt_t3a_8_1.o\
OFFSET_ccsdt_t3a_8_1.o\
ccsdt_t3a_8_1_1.o\
OFFSET_ccsdt_t3a_8_1_1.o\
ccsdt_t3a_8_1_2.o\
ccsdt_t3a_8_1_2_1.o\
OFFSET_ccsdt_t3a_8_1_2_1.o\
ccsdt_t3a_8_1_2_2.o\
ccsdt_t3a_8_1_3.o\
ccsdt_t3a_8_1_4.o\
ccsdt_t3a_8_2.o\
ccsdt_t3a_8_2_1.o\
OFFSET_ccsdt_t3a_8_2_1.o\
ccsdt_t3a_8_2_2.o\
ccsdt_t3a_8_3.o\
ccsdt_t3a_8_3_1.o\
OFFSET_ccsdt_t3a_8_3_1.o\
ccsdt_t3a_8_3_2.o\
ccsdt_t3a_8_4.o\
ccsdt_t3a_8_5.o\
ccsdt_t3a_8_5_1.o\
OFFSET_ccsdt_t3a_8_5_1.o\
ccsdt_t3a_9.o\
ccsdt_t3a_9_1.o\
OFFSET_ccsdt_t3a_9_1.o\
acolo.o\
acolo_o.o\
acolo_o_1p.o\
acolo_o_2p.o\
acolo_1p_2h.o\
acolo_2h.o\
acolo_1h.o\
acolo_1p_1h.o\
acolo_2p_1h.o\
acolo_1p.o\
acolo_1a_2h.o

LIB_INCLUDES = -I../include

LIBRARY = libtce.a

USES_BLAS = ccsdt_e.F \
ccsdt_t1a.F \
ccsdt_t1.F \
ccsdt_t2a.F \
ccsdt_t2.F \
ccsdt_t3_1_2_2_2.F \
ccsdt_t3_1_2_2.F \
ccsdt_t3_1_2_3.F \
ccsdt_t3_1_2.F \
ccsdt_t3_1_3_2.F \
ccsdt_t3_1_3.F \
ccsdt_t3_1_4_2.F \
ccsdt_t3_1_4.F \
ccsdt_t3_1_5_2.F \
ccsdt_t3_1_5.F \
ccsdt_t3_1_6.F \
ccsdt_t3_1_7.F \
ccsdt_t3_1.F \
ccsdt_t3_2_2.F \
ccsdt_t3_2_3_2.F \
ccsdt_t3_2_3.F \
ccsdt_t3_2_4.F \
ccsdt_t3_2_5.F \
ccsdt_t3_2.F \
ccsdt_t3_3_2_2.F \
ccsdt_t3_3_2.F \
ccsdt_t3_3_3.F \
ccsdt_t3_3_4.F \
ccsdt_t3_3.F \
ccsdt_t3_4_2.F \
ccsdt_t3_4_3.F \
ccsdt_t3_4.F \
ccsdt_t3_5_2_2.F \
ccsdt_t3_5_2.F \
ccsdt_t3_5_3.F \
ccsdt_t3_5.F \
ccsdt_t3_6_2.F \
ccsdt_t3_6_3.F \
ccsdt_t3_6.F \
ccsdt_t3_7.F \
ccsdt_t3_8_1_2_2.F \
ccsdt_t3_8_1_2.F \
ccsdt_t3_8_1_3.F \
ccsdt_t3_8_1_4.F \
ccsdt_t3_8_1.F \
ccsdt_t3_8_2_2.F \
ccsdt_t3_8_2.F \
ccsdt_t3_8_3_2.F \
ccsdt_t3_8_3.F \
ccsdt_t3_8_4.F \
ccsdt_t3_8_5_1.F \
ccsdt_t3_8_5.F \
ccsdt_t3_8.F \
ccsdt_t3_9_1.F \
ccsdt_t3_9.F \
ccsdt_t3a_1_2_2_2.F \
ccsdt_t3a_1_2_2.F \
ccsdt_t3a_1_2_3.F \
ccsdt_t3a_1_2.F \
ccsdt_t3a_1_3_2.F \
ccsdt_t3a_1_3.F \
ccsdt_t3a_1_4_2.F \
ccsdt_t3a_1_4.F \
ccsdt_t3a_1_5_2.F \
ccsdt_t3a_1_5.F \
ccsdt_t3a_1_6.F \
ccsdt_t3a_1_7.F \
ccsdt_t3a_1.F \
ccsdt_t3a_2_2.F \
ccsdt_t3a_2_3_2.F \
ccsdt_t3a_2_3.F \
ccsdt_t3a_2_4.F \
ccsdt_t3a_2_5.F \
ccsdt_t3a_2.F \
ccsdt_t3a_3_2_2.F \
ccsdt_t3a_3_2.F \
ccsdt_t3a_3_3.F \
ccsdt_t3a_3_4.F \
ccsdt_t3a_3.F \
ccsdt_t3a_4_2.F \
ccsdt_t3a_4_3.F \
ccsdt_t3a_4.F \
ccsdt_t3a_5_2_2.F \
ccsdt_t3a_5_2.F \
ccsdt_t3a_5_3.F \
ccsdt_t3a_5.F \
ccsdt_t3a_6_2.F \
ccsdt_t3a_6_3.F \
ccsdt_t3a_6.F \
ccsdt_t3a_7.F \
ccsdt_t3a_8_1_2_2.F \
ccsdt_t3a_8_1_2.F \
ccsdt_t3a_8_1_3.F \
ccsdt_t3a_8_1_4.F \
ccsdt_t3a_8_1.F \
ccsdt_t3a_8_2_2.F \
ccsdt_t3a_8_2.F \
ccsdt_t3a_8_3_2.F \
ccsdt_t3a_8_3.F \
ccsdt_t3a_8_4.F \
ccsdt_t3a_8_5_1.F \
ccsdt_t3a_8_5.F \
ccsdt_t3a_8.F \
ccsdt_t3a_9_1.F \
ccsdt_t3a_9.F


LIB_DEFINES = -DDEBUG_PRINT
#
# Possible #defines
#
#              -DDEBUG_PRINT          /* Debug printing routines */
#	       -DNOCOMMS              /* Turn off ALL communication calls */
#              -DBLOCK_TRANSF         /* Use block-transfer for comms calls */
#              -DOLD_AOBLOCK          /* Recover original AO blocking scheme */
#

HEADERS = 

include ../../config/makefile.h
include ../../config/makelib.h

