#
# $Id$
#
 OBJ_OPTIMIZE = \
                pspw_charge.o \
                pspw_efield.o

      OBJ =

      LIBRARY = libpspw.a

    USES_BLAS =  pspw_charge.F pspw_efield.F pspw_cosmo.F
  LIB_DEFINES =
  LIB_INCLUDES = 

include ../../../config/makefile.h
include ../../../config/makelib.h

