#
# $Id: GNUmakefile,v 1.3 2006-06-05 18:00:52 edo Exp $
#
 OBJ_OPTIMIZE = \
                pspw_charge.o

      OBJ =

      LIBRARY = libpspw.a

    USES_BLAS =  pspw_charge.F
  LIB_DEFINES =
  LIB_INCLUDES = 

include ../../../config/makefile.h
include ../../../config/makelib.h

