#
# $Id: GNUmakefile,v 1.14 1999-07-02 18:25:01 d3g681 Exp $
#

LIBRARY = libdriver.a

OBJ_OPTIMIZE= opt_drv.o driver_input.o

USES_BLAS = opt_drv.F

include ../config/makefile.h
include ../config/makelib.h

#FFLAGS  = -qsource -qxref=full -bloadmap:load.map 
