#
# $Id: GNUmakefile,v 1.11 1999-06-09 23:40:09 d3g681 Exp $
#

LIBRARY = libdriver.a

OBJ = opt_drv.o new.o driver_input.o
#sad_drv.o lst_drv.o 

USES_BLAS = opt_drv.F

include ../config/makefile.h
include ../config/makelib.h

#FFLAGS  = -qsource -qxref=full -bloadmap:load.map 
