#
# $Id: GNUmakefile,v 1.15 2007-06-19 23:31:52 bylaska Exp $
#

#      SUBDIRS = pspw band nwpwlib libraryps
       SUBDIRS = nwpwlib libraryps pspw paw band ofpw

          OBJ = nwpw_input.o \
                nwpw_default.o \
                nwpw_vectors_input.o


      LIBRARY = libnwpw.a


  LIB_DEFINES =




include ../config/makefile.h
include ../config/makelib.h









