#
# $Id: GNUmakefile,v 1.6 2001-11-29 02:02:57 edo Exp $
#


          OBJ = nwpw_input.o


      LIBRARY = libnwpw.a

  LIB_DEFINES =

      SUBDIRS = pspw band nwpwlib library
  LIB_INCLUDES = 



include ../config/makefile.h
include ../config/makelib.h









