# $Id$
       HEADERS = 
  OBJ_OPTIMIZE = stpr_partit.o 
           OBJ = stpr_cheker.o     stpr_chkhess.o    stpr_clnstp.o  \
                 stpr_cneed.o      stpr_cross.o      stpr_driver.o  \
                 stpr_fndmde.o     stpr_formup.o     stpr_gmass.o   \
                 stpr_hesupd.o     stpr_hmass.o      stpr_inihes.o  \
                 stpr_face.o       stpr_locate.o     stpr_matout.o  \
                 stpr_mgeom.o      stpr_mkstep.o     stpr_mktri.o   \
                 stpr_output.o     stpr_place.o   \
                 stpr_pmat.o       stpr_prntpd.o     stpr_projec.o  \
                 stpr_putbck.o     stpr_readsq.o     stpr_save.o    \
                 stpr_setmass.o    stpr_stepcor.o \
                 stpr_stepper.o    stpr_sumstc.o     stpr_tprntd.o  \
                 stpr_uprcase.o    stpr_wlkchk.o     stpr_wrtsq.o   \
                 stpr_walk.o       stpr_datestp.o \
                 distang.o         \
                 stpr_gh_at.o \
                 stpr_gen_aux.o    stpr_filenames.o  stepper_inp.o

       LIBRARY = libstepper.a
   LIB_TARGETS = 

   USES_BLAS = stpr_driver.F stpr_mkstep.F stpr_partit.F

include ../config/makefile.h
include ../config/makelib.h


