      SUBROUTINE stpr_locate(INPUT,TOKEN,IERROR)
c $Id$
C     ----- SEARCH THROUGH INPUT FILE FOR TOKEN TO LOCATE INPUT FOR
C           PROGRAM.  IERROR IS SET TO 0 IF NO ERRORS, 1 IF ANY ERROR
C           OCCURS.
C
      CHARACTER*10 TOKEN,TOKEN1,LINE
      TOKEN1=TOKEN
      CALL stpr_uprcase (TOKEN1)
      REWIND (UNIT=INPUT,ERR=99)
    1 CONTINUE
        READ (UNIT=INPUT,FMT='(A10)',END=99,ERR=99) LINE
        CALL stpr_uprcase (LINE)
      IF (LINE.NE.TOKEN1) GOTO 1
      IERROR=0
      RETURN
   99 CONTINUE
      IERROR=1
      RETURN
      END
