#
# $Id: GNUmakefile,v 1.2 2003-02-19 23:43:40 marat Exp $
#

          OBJ =  paw_gaunt.o
          HEADERS = paw_gaunt.fh 


      LIBRARY =	libpaw.a

   USES_BLAS = 

  LIB_INCLUDES = 

  LIB_DEFINES = 




include ../../../config/makefile.h
include ../../../config/makelib.h


