#
# $Id: GNUmakefile,v 1.1 2003-02-06 06:09:05 marat Exp $
#

          OBJ =  paw_gaunt.o
          HEADERS =  


      LIBRARY =	libpaw.a

   USES_BLAS = 

  LIB_INCLUDES = 

  LIB_DEFINES = 




include ../../../config/makefile.h
include ../../../config/makelib.h


