#!/usr/bin/env bash
#
# $Id$
#
#
# modified to use the perl version to change back to the sed scripts
#
if [[ -z "${NWCHEM_TOP}" ]]; then
    DIRUTIL=`dirname "$0"`
    MYPWD=`pwd`
    NWCHEM_TOP=`echo ${MYPWD}/${DIRUTIL} | sed -e 's/\/src.*//' `
fi
pythonexe=python
pythonscript=${NWCHEM_TOP}/src/config/64_to_32.py


 JOB_LIMIT=6

 njob=0

for file in "$@"
do
if [ -f "$file" ]; then
   echo converting "$file" to 32-bit integers for BLAS/LAPACK
      ($pythonexe $pythonscript $file) &	

   let njob++
   if [ $njob -gt $JOB_LIMIT ]; then
     wait
     let njob=0
   fi
fi
done

if [ $njob -gt  0 ] ; then
    wait
fi
