#!/usr/bin/env bash
#
# $Id$
#
#
# confirms file(s) that have blas/lapack calls now using the perl scripts
# reports all single precision routines
#
if [ -z "$NWCHEM_TOP" ]; then
   echo "the environement variable NWCHEM_TOP must first be set"
   echo "csh/tcsh:     setenv NWCHEM_TOP .../nwchem"
   echo "sh/bash/ksh:  NWCHEM_TOP=.../nwchem;export NWCHEM_TOP"
   echo "Usage: has_sblas file_1 [file_2 file_3 ...]"
   exit 1
fi
# assume perl is in your path (scarry)
      perlexe=perl
  perlscript=$NWCHEM_TOP/src/config/hassblas.pl

if [[ $# -eq 0 ]] ; then
   echo "Usage: has_sblas file_1 [file_2 file_3 ...]"
   exit 2
fi

$perlexe $perlscript "$@"

