#
# $Id: GNUmakefile,v 1.3 2002-02-11 19:10:01 edo Exp $
#
 OBJ_OPTIMIZE = \
				cpsp_formatter_auto.o \
				kbpp_band.o \
				setup_kbpp_band.o \
				integrate_kbpp_band_local.o \
				integrate_kbpp_band_nonlocal.o
                


	  OBJ = 



      LIBRARY = libband.a

    USES_BLAS = kbpp_band.F setup_kbpp_band.f integrate_kbpp_band_local.F integrate_kbpp_band_nonlocal.F
                

  LIB_DEFINES =


include ../../../config/makefile.h
include ../../../config/makelib.h

