#
# $Id: GNUmakefile,v 1.5 2007-01-02 18:36:49 bylaska Exp $
#
 OBJ_OPTIMIZE = \
		cpsp_formatter_auto.o \
		kbpp_band.o \
		setup_kbpp_band.o \
		integrate_kbpp_band_local.o \
		integrate_kbpp_band_nonlocal.o \
		cpsp_stress_formatter_auto.o \
		kbpp_band_stress.o \
		integrate_kbpp_band_stress_local.o \
		integrate_kbpp_band_stress_nonlocal.o \
		HGH_band_local.o \
		HGH_band_nonlocal.o \
		Tesseral_band.o \
		hghpp_band.o 


	  OBJ = 



      LIBRARY = libband.a

    USES_BLAS = kbpp_band.F setup_kbpp_band.f integrate_kbpp_band_local.F integrate_kbpp_band_nonlocal.F \
		kbpp_band_stress.F integrate_kbpp_band_stress_local.F \
                integrate_kbpp_band_stress_nonlocal.F \
		HGH_band_local.F HGH_band_nonlocal.F Tesseral_band.F hghpp_band.F
                

  LIB_DEFINES =


include ../../../config/makefile.h
include ../../../config/makelib.h

