# $Id: GNUmakefile,v 1.2 1996-07-02 23:02:13 d3e129 Exp $

OBJ = seetex.o

include ../../src/config/makefile.h

LIB_TARGETS = seetex $(OBJ)

target:
	$(MAKE) seetex
	seetex sample.th sample.F sample.tex
