#
# $Id$
#
 OBJ_OPTIMIZE = \
				pspw_dplot_input.o \
				pspw_dplot.o \
				pspw_dplot_iteration.o \
				ELF.o \
				Ursenbach_smoother.o


	  OBJ = 

      LIBRARY = libpspw.a

    USES_BLAS = pspw_dplot.F ELF.F

  LIB_DEFINES = 


include ../../../config/makefile.h
include ../../../config/makelib.h

