#
# $Id: GNUmakefile,v 1.3 2002-01-18 23:23:41 bylaska Exp $
#
 OBJ_OPTIMIZE = \
				pspw_dplot_input.o \
				pspw_dplot.o \
				pspw_dplot_iteration.o


	  OBJ = 

      LIBRARY = libpspw.a

    USES_BLAS = 

  LIB_DEFINES = 


include ../../../config/makefile.h
include ../../../config/makelib.h

