#
# $Id$
#

 OBJ_OPTIMIZE = \
            cke.o



	  OBJ = 

      LIBRARY = libband.a

    USES_BLAS = cke.F

  LIB_DEFINES = 



include ../../../../config/makefile.h
include ../../../../config/makelib.h

