#
#	$Id: MakeFile,v 1.2 2000-07-18 18:14:53 edo Exp $	
#

OBJ_OPTIMIZE = $(OBJDIR)\nwfft3d.obj

LIBRARY = pfft.lib
LIB_DEFINES = -DEMSLFFT

!INCLUDE ..\..\config\NTmakefile.h
!INCLUDE ..\..\config\NTmakelib.h
