#
# $Id: GNUmakefile 23627 2013-02-23 02:05:08Z bylaska $
#
      SUBDIRS = 

 OBJ_OPTIMIZE = \
		fmm.o

	  OBJ = 

      LIBRARY = libnwpwlib.a

    USES_BLAS = fmm.F

  LIB_DEFINES = 


include ../../../config/makefile.h
include ../../../config/makelib.h

