#
# $Id: GNUmakefile,v 1.2 2004-04-08 01:27:18 edo Exp $
#


   OBJ = nwnbo.o nbo_holler.o

   LIBRARY = libnbo.a
   LIB_DEFINES = 
   LIB_INCLUDES = -I../include

USES_BLAS = nwnbo.F 

include ../config/makefile.h
include ../config/makelib.h


