#
# $Id: GNUmakefile,v 1.5 2008-05-08 22:20:28 bert Exp $
#


   OBJ = nwnbo.o

   LIBRARY = libnbo.a
   LIB_DEFINES = 
   LIB_INCLUDES = -I../include

USES_BLAS = nwnbo.F

include ../config/makefile.h
include ../config/makelib.h
