#
# $Id$
#

          OBJ = 


      LIBRARY =	libpaw.a

   USES_BLAS = 

  LIB_INCLUDES = -I../include/

  LIB_DEFINES = 

  HEADERS = paw_geom.fh



include ../../../config/makefile.h
include ../../../config/makelib.h
include ../makefile.h












