#
# $Id: GNUmakefile,v 1.1 2003-01-30 00:07:22 marat Exp $
#

          OBJ = 


      LIBRARY =	libpaw.a

   USES_BLAS = 

  LIB_INCLUDES = -I../include/

  LIB_DEFINES = 

  HEADERS = paw_geom.fh



include ../../../config/makefile.h
include ../../../config/makelib.h
include ../makefile.h












