
# $Id$
#
 OBJ_OPTIMIZE = \
                pspw_Pair.o

	  OBJ = 


      LIBRARY = libpspw.a

    USES_BLAS = pspw_Pair.F
                
  LIB_DEFINES =


include ../../../../config/makefile.h
include ../../../../config/makelib.h

