#
# $Id: GNUmakefile,v 1.4 2001-11-14 17:48:32 edo Exp $
#

 OBJ_OPTIMIZE = \
            cpmd_properties.o \
 			pair_dist.o \
            auto_corr.o \
            dsum.o \
 			CIF_write.o


	  OBJ = 

      LIBRARY = libnwpwlib.a

    USES_BLAS = auto_corr.F

  LIB_DEFINES = 


include ../../../config/makefile.h
include ../../../config/makelib.h

