#
# $Id: GNUmakefile,v 1.10 2002-01-07 02:05:37 bylaska Exp $
#

 OBJ_OPTIMIZE = \
			nwpw_scratch.o \
            cpmd_properties.o \
 			pair_dist.o \
            auto_corr.o \
            dsum.o matrix.o simp.o \
			is_sORd.o \
			psi_filefind.o \
			v_psi_filefind.o \
			getfilling.o \
 			CIF_write.o


	  OBJ = 

      LIBRARY = libnwpwlib.a

    USES_BLAS = auto_corr.F izamax.f

  LIB_DEFINES = 


include ../../../config/makefile.h
include ../../../config/makelib.h

