#$Id$

OBJ_OPTIMIZE = ccsdt_lambda3.o ccsdt_density1.o \
ccsdt_lambda1.o\
ccsdt_lambda1_1.o\
ccsdt_lambda1_2.o\
ccsdt_lambda1_2_1.o\
OFFSET_ccsdt_lambda1_2_1.o\
ccsdt_lambda1_2_2.o\
ccsdt_lambda1_2_2_1.o\
OFFSET_ccsdt_lambda1_2_2_1.o\
ccsdt_lambda1_2_2_2.o\
ccsdt_lambda1_2_3.o\
ccsdt_lambda1_2_4.o\
ccsdt_lambda1_3.o\
ccsdt_lambda1_3_1.o\
OFFSET_ccsdt_lambda1_3_1.o\
ccsdt_lambda1_3_2.o\
ccsdt_lambda1_3_3.o\
ccsdt_lambda1_3_3_1.o\
OFFSET_ccsdt_lambda1_3_3_1.o\
ccsdt_lambda1_4.o\
ccsdt_lambda1_5.o\
ccsdt_lambda1_5_1.o\
OFFSET_ccsdt_lambda1_5_1.o\
ccsdt_lambda1_5_2.o\
ccsdt_lambda1_5_2_1.o\
OFFSET_ccsdt_lambda1_5_2_1.o\
ccsdt_lambda1_5_2_2.o\
ccsdt_lambda1_5_2_2_1.o\
OFFSET_ccsdt_lambda1_5_2_2_1.o\
ccsdt_lambda1_5_2_2_2.o\
ccsdt_lambda1_5_2_3.o\
ccsdt_lambda1_5_2_4.o\
ccsdt_lambda1_5_3.o\
ccsdt_lambda1_5_3_1.o\
OFFSET_ccsdt_lambda1_5_3_1.o\
ccsdt_lambda1_5_3_2.o\
ccsdt_lambda1_5_4.o\
ccsdt_lambda1_5_5.o\
ccsdt_lambda1_5_5_1.o\
OFFSET_ccsdt_lambda1_5_5_1.o\
ccsdt_lambda1_5_5_2.o\
ccsdt_lambda1_5_6.o\
ccsdt_lambda1_5_6_1.o\
OFFSET_ccsdt_lambda1_5_6_1.o\
ccsdt_lambda1_5_6_2.o\
ccsdt_lambda1_5_7.o\
ccsdt_lambda1_5_8.o\
ccsdt_lambda1_6.o\
ccsdt_lambda1_6_1.o\
OFFSET_ccsdt_lambda1_6_1.o\
ccsdt_lambda1_6_2.o\
ccsdt_lambda1_6_2_1.o\
OFFSET_ccsdt_lambda1_6_2_1.o\
ccsdt_lambda1_6_2_2.o\
ccsdt_lambda1_6_2_2_1.o\
OFFSET_ccsdt_lambda1_6_2_2_1.o\
ccsdt_lambda1_6_2_2_2.o\
ccsdt_lambda1_6_2_3.o\
ccsdt_lambda1_6_3.o\
ccsdt_lambda1_6_3_1.o\
OFFSET_ccsdt_lambda1_6_3_1.o\
ccsdt_lambda1_6_3_2.o\
ccsdt_lambda1_6_4.o\
ccsdt_lambda1_6_4_1.o\
OFFSET_ccsdt_lambda1_6_4_1.o\
ccsdt_lambda1_6_4_2.o\
ccsdt_lambda1_6_5.o\
ccsdt_lambda1_6_5_1.o\
OFFSET_ccsdt_lambda1_6_5_1.o\
ccsdt_lambda1_6_5_2.o\
ccsdt_lambda1_6_6.o\
ccsdt_lambda1_6_7.o\
ccsdt_lambda1_7.o\
ccsdt_lambda1_7_1.o\
OFFSET_ccsdt_lambda1_7_1.o\
ccsdt_lambda1_7_2.o\
ccsdt_lambda1_8.o\
ccsdt_lambda1_8_1.o\
OFFSET_ccsdt_lambda1_8_1.o\
ccsdt_lambda1_8_2.o\
ccsdt_lambda1_8_2_1.o\
OFFSET_ccsdt_lambda1_8_2_1.o\
ccsdt_lambda1_8_2_2.o\
ccsdt_lambda1_8_2_2_1.o\
OFFSET_ccsdt_lambda1_8_2_2_1.o\
ccsdt_lambda1_8_2_2_2.o\
ccsdt_lambda1_8_2_2_2_1.o\
OFFSET_ccsdt_lambda1_8_2_2_2_1.o\
ccsdt_lambda1_8_2_2_2_2.o\
ccsdt_lambda1_8_2_2_3.o\
ccsdt_lambda1_8_2_3.o\
ccsdt_lambda1_8_2_3_1.o\
OFFSET_ccsdt_lambda1_8_2_3_1.o\
ccsdt_lambda1_8_2_3_2.o\
ccsdt_lambda1_8_2_4.o\
ccsdt_lambda1_8_2_5.o\
ccsdt_lambda1_8_2_5_1.o\
OFFSET_ccsdt_lambda1_8_2_5_1.o\
ccsdt_lambda1_8_3.o\
ccsdt_lambda1_8_3_1.o\
OFFSET_ccsdt_lambda1_8_3_1.o\
ccsdt_lambda1_8_3_2.o\
ccsdt_lambda1_8_4.o\
ccsdt_lambda1_8_4_1.o\
OFFSET_ccsdt_lambda1_8_4_1.o\
ccsdt_lambda1_8_4_2.o\
ccsdt_lambda1_8_4_2_1.o\
OFFSET_ccsdt_lambda1_8_4_2_1.o\
ccsdt_lambda1_8_5.o\
ccsdt_lambda1_8_5_1.o\
OFFSET_ccsdt_lambda1_8_5_1.o\
ccsdt_lambda1_8_5_2.o\
ccsdt_lambda1_8_5_2_1.o\
OFFSET_ccsdt_lambda1_8_5_2_1.o\
ccsdt_lambda1_8_6.o\
ccsdt_lambda1_8_6_1.o\
OFFSET_ccsdt_lambda1_8_6_1.o\
ccsdt_lambda1_8_6_2.o\
ccsdt_lambda1_8_6_2_1.o\
OFFSET_ccsdt_lambda1_8_6_2_1.o\
ccsdt_lambda1_8_6_2_2.o\
ccsdt_lambda1_8_6_3.o\
ccsdt_lambda1_8_7.o\
ccsdt_lambda1_8_7_1.o\
OFFSET_ccsdt_lambda1_8_7_1.o\
ccsdt_lambda1_8_7_2.o\
ccsdt_lambda1_8_7_3.o\
ccsdt_lambda1_8_8.o\
ccsdt_lambda1_8_9.o\
ccsdt_lambda1_8_9_1.o\
OFFSET_ccsdt_lambda1_8_9_1.o\
ccsdt_lambda1_8_9_2.o\
ccsdt_lambda1_8_10.o\
ccsdt_lambda1_8_10_1.o\
OFFSET_ccsdt_lambda1_8_10_1.o\
ccsdt_lambda1_8_10_2.o\
ccsdt_lambda1_8_11.o\
ccsdt_lambda1_8_12.o\
ccsdt_lambda1_8_12_1.o\
OFFSET_ccsdt_lambda1_8_12_1.o\
ccsdt_lambda1_8_12_2.o\
ccsdt_lambda1_8_12_3.o\
ccsdt_lambda1_8_13.o\
ccsdt_lambda1_8_13_1.o\
OFFSET_ccsdt_lambda1_8_13_1.o\
ccsdt_lambda1_8_13_2.o\
ccsdt_lambda1_8_13_3.o\
ccsdt_lambda1_8_14.o\
ccsdt_lambda1_8_14_1.o\
OFFSET_ccsdt_lambda1_8_14_1.o\
ccsdt_lambda1_8_14_2.o\
ccsdt_lambda1_9.o\
ccsdt_lambda1_9_1.o\
OFFSET_ccsdt_lambda1_9_1.o\
ccsdt_lambda1_9_2.o\
ccsdt_lambda1_9_3.o\
ccsdt_lambda1_9_4.o\
ccsdt_lambda1_9_4_1.o\
OFFSET_ccsdt_lambda1_9_4_1.o\
ccsdt_lambda1_9_4_2.o\
ccsdt_lambda1_9_4_3.o\
ccsdt_lambda1_9_5.o\
ccsdt_lambda1_9_5_1.o\
OFFSET_ccsdt_lambda1_9_5_1.o\
ccsdt_lambda1_9_5_2.o\
ccsdt_lambda1_9_5_2_1.o\
OFFSET_ccsdt_lambda1_9_5_2_1.o\
ccsdt_lambda1_9_5_2_2.o\
ccsdt_lambda1_9_6.o\
ccsdt_lambda1_9_6_1.o\
OFFSET_ccsdt_lambda1_9_6_1.o\
ccsdt_lambda1_10.o\
ccsdt_lambda1_10_1.o\
OFFSET_ccsdt_lambda1_10_1.o\
ccsdt_lambda1_10_2.o\
ccsdt_lambda1_10_3.o\
ccsdt_lambda1_11.o\
ccsdt_lambda1_11_1.o\
OFFSET_ccsdt_lambda1_11_1.o\
ccsdt_lambda1_11_2.o\
ccsdt_lambda1_11_3.o\
ccsdt_lambda1_12.o\
ccsdt_lambda1_12_1.o\
OFFSET_ccsdt_lambda1_12_1.o\
ccsdt_lambda1_12_2.o\
ccsdt_lambda1_12_3.o\
ccsdt_lambda1_13.o\
ccsdt_lambda1_13_1.o\
OFFSET_ccsdt_lambda1_13_1.o\
ccsdt_lambda1_13_2.o\
ccsdt_lambda1_14.o\
ccsdt_lambda1_14_1.o\
OFFSET_ccsdt_lambda1_14_1.o\
ccsdt_lambda1_14_2.o\
ccsdt_lambda1_14_3.o\
ccsdt_lambda1_14_3_1.o\
OFFSET_ccsdt_lambda1_14_3_1.o\
ccsdt_lambda1_14_3_2.o\
ccsdt_lambda1_14_3_3.o\
ccsdt_lambda1_14_3_3_1.o\
OFFSET_ccsdt_lambda1_14_3_3_1.o\
ccsdt_lambda1_14_3_3_2.o\
ccsdt_lambda1_14_4.o\
ccsdt_lambda1_14_4_1.o\
OFFSET_ccsdt_lambda1_14_4_1.o\
ccsdt_lambda1_14_5.o\
ccsdt_lambda1_14_5_1.o\
OFFSET_ccsdt_lambda1_14_5_1.o\
ccsdt_lambda1_14_5_2.o\
ccsdt_lambda1_14_6.o\
ccsdt_lambda1_14_6_1.o\
OFFSET_ccsdt_lambda1_14_6_1.o\
ccsdt_lambda1_14_7.o\
ccsdt_lambda1_14_7_1.o\
OFFSET_ccsdt_lambda1_14_7_1.o\
ccsdt_lambda1_14_8.o\
ccsdt_lambda1_14_8_1.o\
OFFSET_ccsdt_lambda1_14_8_1.o\
ccsdt_lambda1_14_8_1_1.o\
OFFSET_ccsdt_lambda1_14_8_1_1.o\
ccsdt_lambda1_14_8_1_2.o\
ccsdt_lambda1_14_9.o\
ccsdt_lambda1_14_9_1.o\
OFFSET_ccsdt_lambda1_14_9_1.o\
ccsdt_lambda1_14_9_1_1.o\
OFFSET_ccsdt_lambda1_14_9_1_1.o\
ccsdt_lambda1_15.o\
ccsdt_lambda1_15_1.o\
OFFSET_ccsdt_lambda1_15_1.o\
ccsdt_lambda1_15_2.o\
ccsdt_lambda1_15_3.o\
ccsdt_lambda1_15_3_1.o\
OFFSET_ccsdt_lambda1_15_3_1.o\
ccsdt_lambda1_15_4.o\
ccsdt_lambda1_15_4_1.o\
OFFSET_ccsdt_lambda1_15_4_1.o\
ccsdt_lambda1_16.o\
ccsdt_lambda1_16_1.o\
OFFSET_ccsdt_lambda1_16_1.o\
ccsdt_lambda1_16_2.o\
ccsdt_lambda1_16_3.o\
ccsdt_lambda1_16_3_1.o\
OFFSET_ccsdt_lambda1_16_3_1.o\
ccsdt_lambda1_16_3_2.o\
ccsdt_lambda1_16_4.o\
ccsdt_lambda1_16_4_1.o\
OFFSET_ccsdt_lambda1_16_4_1.o\
ccsdt_lambda1_17.o\
ccsdt_lambda1_17_1.o\
OFFSET_ccsdt_lambda1_17_1.o\
ccsdt_lambda1_18.o\
ccsdt_lambda1_18_1.o\
OFFSET_ccsdt_lambda1_18_1.o\
ccsdt_lambda1_18_1_1.o\
OFFSET_ccsdt_lambda1_18_1_1.o\
ccsdt_lambda1_18_1_2.o\
ccsdt_lambda1_18_1_3.o\
ccsdt_lambda1_18_1_4.o\
ccsdt_lambda1_18_1_4_1.o\
OFFSET_ccsdt_lambda1_18_1_4_1.o\
ccsdt_lambda1_18_1_4_2.o\
ccsdt_lambda1_18_2.o\
ccsdt_lambda1_18_2_1.o\
OFFSET_ccsdt_lambda1_18_2_1.o\
ccsdt_lambda1_18_2_2.o\
ccsdt_lambda1_18_3.o\
ccsdt_lambda1_18_3_1.o\
OFFSET_ccsdt_lambda1_18_3_1.o\
ccsdt_lambda1_18_3_2.o\
ccsdt_lambda1_18_4.o\
ccsdt_lambda1_18_5.o\
ccsdt_lambda1_18_5_1.o\
OFFSET_ccsdt_lambda1_18_5_1.o\
ccsdt_lambda1_18_6.o\
ccsdt_lambda1_18_6_1.o\
OFFSET_ccsdt_lambda1_18_6_1.o\
ccsdt_lambda1_18_6_1_1.o\
OFFSET_ccsdt_lambda1_18_6_1_1.o\
ccsdt_lambda1_19.o\
ccsdt_lambda1_19_1.o\
OFFSET_ccsdt_lambda1_19_1.o\
ccsdt_lambda1_20.o\
ccsdt_lambda1_20_1.o\
OFFSET_ccsdt_lambda1_20_1.o\
ccsdt_lambda1_20_1_1.o\
OFFSET_ccsdt_lambda1_20_1_1.o\
ccsdt_lambda1_21.o\
ccsdt_lambda1_21_1.o\
OFFSET_ccsdt_lambda1_21_1.o\
ccsdt_lambda1_21_1_1.o\
OFFSET_ccsdt_lambda1_21_1_1.o\
ccsdt_lambda1_21_1_1_1.o\
OFFSET_ccsdt_lambda1_21_1_1_1.o\
ccsdt_lambda1_21_1_1_2.o\
ccsdt_lambda1_21_2.o\
ccsdt_lambda1_21_2_1.o\
OFFSET_ccsdt_lambda1_21_2_1.o\
ccsdt_lambda1_21_2_1_1.o\
OFFSET_ccsdt_lambda1_21_2_1_1.o\
ccsdt_lambda2.o\
ccsdt_lambda2_1.o\
ccsdt_lambda2_2.o\
ccsdt_lambda2_2_1.o\
OFFSET_ccsdt_lambda2_2_1.o\
ccsdt_lambda2_2_2.o\
ccsdt_lambda2_3.o\
ccsdt_lambda2_3_1.o\
OFFSET_ccsdt_lambda2_3_1.o\
ccsdt_lambda2_3_2.o\
ccsdt_lambda2_4.o\
ccsdt_lambda2_5.o\
ccsdt_lambda2_5_1.o\
OFFSET_ccsdt_lambda2_5_1.o\
ccsdt_lambda2_5_2.o\
ccsdt_lambda2_5_2_1.o\
OFFSET_ccsdt_lambda2_5_2_1.o\
ccsdt_lambda2_5_2_2.o\
ccsdt_lambda2_5_3.o\
ccsdt_lambda2_5_4.o\
ccsdt_lambda2_6.o\
ccsdt_lambda2_6_1.o\
OFFSET_ccsdt_lambda2_6_1.o\
ccsdt_lambda2_6_2.o\
ccsdt_lambda2_6_3.o\
ccsdt_lambda2_6_4.o\
ccsdt_lambda2_6_4_1.o\
OFFSET_ccsdt_lambda2_6_4_1.o\
ccsdt_lambda2_7.o\
ccsdt_lambda2_7_1.o\
OFFSET_ccsdt_lambda2_7_1.o\
ccsdt_lambda2_7_2.o\
ccsdt_lambda2_7_2_1.o\
OFFSET_ccsdt_lambda2_7_2_1.o\
ccsdt_lambda2_7_2_2.o\
ccsdt_lambda2_7_3.o\
ccsdt_lambda2_8.o\
ccsdt_lambda2_8_1.o\
OFFSET_ccsdt_lambda2_8_1.o\
ccsdt_lambda2_8_2.o\
ccsdt_lambda2_8_3.o\
ccsdt_lambda2_9.o\
ccsdt_lambda2_10.o\
ccsdt_lambda2_10_1.o\
OFFSET_ccsdt_lambda2_10_1.o\
ccsdt_lambda2_10_2.o\
ccsdt_lambda2_10_2_1.o\
OFFSET_ccsdt_lambda2_10_2_1.o\
ccsdt_lambda2_10_2_2.o\
ccsdt_lambda2_10_2_2_1.o\
OFFSET_ccsdt_lambda2_10_2_2_1.o\
ccsdt_lambda2_10_2_2_2.o\
ccsdt_lambda2_10_2_3.o\
ccsdt_lambda2_10_2_4.o\
ccsdt_lambda2_10_3.o\
ccsdt_lambda2_10_3_1.o\
OFFSET_ccsdt_lambda2_10_3_1.o\
ccsdt_lambda2_10_3_2.o\
ccsdt_lambda2_10_3_3.o\
ccsdt_lambda2_10_4.o\
ccsdt_lambda2_10_5.o\
ccsdt_lambda2_10_5_1.o\
OFFSET_ccsdt_lambda2_10_5_1.o\
ccsdt_lambda2_10_5_2.o\
ccsdt_lambda2_10_6.o\
ccsdt_lambda2_10_7.o\
ccsdt_lambda2_10_8.o\
ccsdt_lambda2_11.o\
ccsdt_lambda2_11_1.o\
OFFSET_ccsdt_lambda2_11_1.o\
ccsdt_lambda2_11_2.o\
ccsdt_lambda2_11_2_1.o\
OFFSET_ccsdt_lambda2_11_2_1.o\
ccsdt_lambda2_11_2_2.o\
ccsdt_lambda2_11_2_2_1.o\
OFFSET_ccsdt_lambda2_11_2_2_1.o\
ccsdt_lambda2_11_2_2_2.o\
ccsdt_lambda2_11_2_3.o\
ccsdt_lambda2_11_3.o\
ccsdt_lambda2_11_3_1.o\
OFFSET_ccsdt_lambda2_11_3_1.o\
ccsdt_lambda2_11_3_2.o\
ccsdt_lambda2_11_4.o\
ccsdt_lambda2_11_4_1.o\
OFFSET_ccsdt_lambda2_11_4_1.o\
ccsdt_lambda2_11_4_2.o\
ccsdt_lambda2_11_5.o\
ccsdt_lambda2_11_5_1.o\
OFFSET_ccsdt_lambda2_11_5_1.o\
ccsdt_lambda2_11_5_2.o\
ccsdt_lambda2_11_6.o\
ccsdt_lambda2_11_7.o\
ccsdt_lambda2_12.o\
ccsdt_lambda2_12_1.o\
OFFSET_ccsdt_lambda2_12_1.o\
ccsdt_lambda2_12_2.o\
ccsdt_lambda2_12_3.o\
ccsdt_lambda2_12_3_1.o\
OFFSET_ccsdt_lambda2_12_3_1.o\
ccsdt_lambda2_12_3_2.o\
ccsdt_lambda2_12_4.o\
ccsdt_lambda2_12_5.o\
ccsdt_lambda2_12_6.o\
ccsdt_lambda2_12_6_1.o\
OFFSET_ccsdt_lambda2_12_6_1.o\
ccsdt_lambda2_12_7.o\
ccsdt_lambda2_12_7_1.o\
OFFSET_ccsdt_lambda2_12_7_1.o\
ccsdt_lambda2_13.o\
ccsdt_lambda2_13_1.o\
OFFSET_ccsdt_lambda2_13_1.o\
ccsdt_lambda2_13_2.o\
ccsdt_lambda2_13_3.o\
ccsdt_lambda2_14.o\
ccsdt_lambda2_14_1.o\
OFFSET_ccsdt_lambda2_14_1.o\
ccsdt_lambda2_14_2.o\
ccsdt_lambda2_15.o\
ccsdt_lambda2_15_1.o\
OFFSET_ccsdt_lambda2_15_1.o\
ccsdt_lambda2_15_2.o\
ccsdt_lambda2_16.o\
ccsdt_lambda2_16_1.o\
OFFSET_ccsdt_lambda2_16_1.o\
ccsdt_lambda2_16_2.o\
ccsdt_lambda2_17.o\
ccsdt_lambda2_17_1.o\
OFFSET_ccsdt_lambda2_17_1.o\
ccsdt_lambda2_18.o\
ccsdt_lambda2_18_1.o\
OFFSET_ccsdt_lambda2_18_1.o\
ccsdt_lambda2_18_2.o\
ccsdt_lambda2_19.o\
ccsdt_lambda2_19_1.o\
OFFSET_ccsdt_lambda2_19_1.o\
ccsdt_lambda2_19_2.o\
ccsdt_lambda2_19_3.o\
ccsdt_lambda2_19_3_1.o\
OFFSET_ccsdt_lambda2_19_3_1.o\
ccsdt_lambda2_19_4.o\
ccsdt_lambda2_19_4_1.o\
OFFSET_ccsdt_lambda2_19_4_1.o\
ccsdt_lambda2_20.o\
ccsdt_lambda2_20_1.o\
OFFSET_ccsdt_lambda2_20_1.o\
ccsdt_lambda2_21.o\
ccsdt_lambda2_21_1.o\
OFFSET_ccsdt_lambda2_21_1.o\
ccsdt_lambda2_22.o\
ccsdt_lambda2_22_1.o\
OFFSET_ccsdt_lambda2_22_1.o\
ccsdt_lambda2_23.o\
ccsdt_lambda2_23_1.o\
OFFSET_ccsdt_lambda2_23_1.o\
ccsdt_lambda2_23_2.o\
ccsdt_lambda2_23_2_1.o\
OFFSET_ccsdt_lambda2_23_2_1.o\
ccsdt_lambda2_23_2_2.o\
ccsdt_lambda2_23_3.o\
ccsdt_lambda2_23_3_1.o\
OFFSET_ccsdt_lambda2_23_3_1.o\
ccsdt_lambda2_24.o\
ccsdt_lambda2_24_1.o\
OFFSET_ccsdt_lambda2_24_1.o\
ccsdt_lambda2_24_1_1.o\
OFFSET_ccsdt_lambda2_24_1_1.o\
ccsdt_lambda2_25.o\
ccsdt_lambda2_25_1.o\
OFFSET_ccsdt_lambda2_25_1.o\
ccsdt_lambda2_25_1_1.o\
OFFSET_ccsdt_lambda2_25_1_1.o\
ccsdt_lambda2_26.o\
ccsdt_lambda2_26_1.o\
OFFSET_ccsdt_lambda2_26_1.o\
ccsdt_lambda2_26_1_1.o\
OFFSET_ccsdt_lambda2_26_1_1.o\
ccsdt_lambda2_26_2.o\
ccsdt_lambda2_26_2_1.o\
OFFSET_ccsdt_lambda2_26_2_1.o\
ccsdt_lambda2_26_2_1_1.o\
OFFSET_ccsdt_lambda2_26_2_1_1.o

LIB_INCLUDES = -I../include

LIBRARY = libtce.a

USES_BLAS = ccsdt_density1.F \
ccsdt_lambda1_10_1.F \
ccsdt_lambda1_10_2.F \
ccsdt_lambda1_10_3.F \
ccsdt_lambda1_10.F \
ccsdt_lambda1_11_1.F \
ccsdt_lambda1_11_2.F \
ccsdt_lambda1_11_3.F \
ccsdt_lambda1_11.F \
ccsdt_lambda1_12_1.F \
ccsdt_lambda1_12_2.F \
ccsdt_lambda1_12_3.F \
ccsdt_lambda1_12.F \
ccsdt_lambda1_13_1.F \
ccsdt_lambda1_13_2.F \
ccsdt_lambda1_13.F \
ccsdt_lambda1_14_1.F \
ccsdt_lambda1_14_2.F \
ccsdt_lambda1_14_3_1.F \
ccsdt_lambda1_14_3_2.F \
ccsdt_lambda1_14_3_3_1.F \
ccsdt_lambda1_14_3_3_2.F \
ccsdt_lambda1_14_3_3.F \
ccsdt_lambda1_14_3.F \
ccsdt_lambda1_14_4_1.F \
ccsdt_lambda1_14_4.F \
ccsdt_lambda1_14_5_1.F \
ccsdt_lambda1_14_5_2.F \
ccsdt_lambda1_14_5.F \
ccsdt_lambda1_14_6_1.F \
ccsdt_lambda1_14_6.F \
ccsdt_lambda1_14_7_1.F \
ccsdt_lambda1_14_7.F \
ccsdt_lambda1_14_8_1.F \
ccsdt_lambda1_14_8.F \
ccsdt_lambda1_14_9_1_1.F \
ccsdt_lambda1_14_9_1.F \
ccsdt_lambda1_14_9.F \
ccsdt_lambda1_14.F \
ccsdt_lambda1_15_1.F \
ccsdt_lambda1_15_2.F \
ccsdt_lambda1_15_3_1.F \
ccsdt_lambda1_15_3.F \
ccsdt_lambda1_15_4_1.F \
ccsdt_lambda1_15_4.F \
ccsdt_lambda1_15.F \
ccsdt_lambda1_16_1.F \
ccsdt_lambda1_16_2.F \
ccsdt_lambda1_16_3_1.F \
ccsdt_lambda1_16_3_2.F \
ccsdt_lambda1_16_3.F \
ccsdt_lambda1_16_4_1.F \
ccsdt_lambda1_16_4.F \
ccsdt_lambda1_16.F \
ccsdt_lambda1_17_1.F \
ccsdt_lambda1_17.F \
ccsdt_lambda1_18_1_2.F \
ccsdt_lambda1_18_1_3.F \
ccsdt_lambda1_18_1_4.F \
ccsdt_lambda1_18_1.F \
ccsdt_lambda1_18_2_2.F \
ccsdt_lambda1_18_2.F \
ccsdt_lambda1_18_3_2.F \
ccsdt_lambda1_18_3.F \
ccsdt_lambda1_18_4.F \
ccsdt_lambda1_18_5_1.F \
ccsdt_lambda1_18_5.F \
ccsdt_lambda1_18_6_1_1.F \
ccsdt_lambda1_18_6_1.F \
ccsdt_lambda1_18_6.F \
ccsdt_lambda1_18.F \
ccsdt_lambda1_19_1.F \
ccsdt_lambda1_19.F \
ccsdt_lambda1_20_1_1.F \
ccsdt_lambda1_20_1.F \
ccsdt_lambda1_20.F \
ccsdt_lambda1_21_1_1.F \
ccsdt_lambda1_21_1.F \
ccsdt_lambda1_21_2_1_1.F \
ccsdt_lambda1_21_2_1.F \
ccsdt_lambda1_21_2.F \
ccsdt_lambda1_21.F \
ccsdt_lambda1_2_2_2.F \
ccsdt_lambda1_2_2.F \
ccsdt_lambda1_2_3.F \
ccsdt_lambda1_2_4.F \
ccsdt_lambda1_2.F \
ccsdt_lambda1_3_2.F \
ccsdt_lambda1_3_3_1.F \
ccsdt_lambda1_3_3.F \
ccsdt_lambda1_3.F \
ccsdt_lambda1_4.F \
ccsdt_lambda1_5_2_2_2.F \
ccsdt_lambda1_5_2_2.F \
ccsdt_lambda1_5_2_3.F \
ccsdt_lambda1_5_2_4.F \
ccsdt_lambda1_5_2.F \
ccsdt_lambda1_5_3_2.F \
ccsdt_lambda1_5_3.F \
ccsdt_lambda1_5_4.F \
ccsdt_lambda1_5_5_2.F \
ccsdt_lambda1_5_5.F \
ccsdt_lambda1_5_6_2.F \
ccsdt_lambda1_5_6.F \
ccsdt_lambda1_5_7.F \
ccsdt_lambda1_5_8.F \
ccsdt_lambda1_5.F \
ccsdt_lambda1_6_2_2_2.F \
ccsdt_lambda1_6_2_2.F \
ccsdt_lambda1_6_2_3.F \
ccsdt_lambda1_6_2.F \
ccsdt_lambda1_6_3_2.F \
ccsdt_lambda1_6_3.F \
ccsdt_lambda1_6_4_2.F \
ccsdt_lambda1_6_4.F \
ccsdt_lambda1_6_5_2.F \
ccsdt_lambda1_6_5.F \
ccsdt_lambda1_6_6.F \
ccsdt_lambda1_6_7.F \
ccsdt_lambda1_6.F \
ccsdt_lambda1_7_2.F \
ccsdt_lambda1_7.F \
ccsdt_lambda1_8_10_2.F \
ccsdt_lambda1_8_10.F \
ccsdt_lambda1_8_11.F \
ccsdt_lambda1_8_12_1.F \
ccsdt_lambda1_8_12_2.F \
ccsdt_lambda1_8_12_3.F \
ccsdt_lambda1_8_12.F \
ccsdt_lambda1_8_13_1.F \
ccsdt_lambda1_8_13_2.F \
ccsdt_lambda1_8_13_3.F \
ccsdt_lambda1_8_13.F \
ccsdt_lambda1_8_14_1.F \
ccsdt_lambda1_8_14_2.F \
ccsdt_lambda1_8_14.F \
ccsdt_lambda1_8_2_2_2_2.F \
ccsdt_lambda1_8_2_2_2.F \
ccsdt_lambda1_8_2_2_3.F \
ccsdt_lambda1_8_2_2.F \
ccsdt_lambda1_8_2_3_2.F \
ccsdt_lambda1_8_2_3.F \
ccsdt_lambda1_8_2_4.F \
ccsdt_lambda1_8_2_5_1.F \
ccsdt_lambda1_8_2_5.F \
ccsdt_lambda1_8_2.F \
ccsdt_lambda1_8_3_2.F \
ccsdt_lambda1_8_3.F \
ccsdt_lambda1_8_4_2_1.F \
ccsdt_lambda1_8_4_2.F \
ccsdt_lambda1_8_4.F \
ccsdt_lambda1_8_5_2_1.F \
ccsdt_lambda1_8_5_2.F \
ccsdt_lambda1_8_5.F \
ccsdt_lambda1_8_6_2_2.F \
ccsdt_lambda1_8_6_2.F \
ccsdt_lambda1_8_6_3.F \
ccsdt_lambda1_8_6.F \
ccsdt_lambda1_8_7_2.F \
ccsdt_lambda1_8_7_3.F \
ccsdt_lambda1_8_7.F \
ccsdt_lambda1_8_8.F \
ccsdt_lambda1_8_9_2.F \
ccsdt_lambda1_8_9.F \
ccsdt_lambda1_8.F \
ccsdt_lambda1_9_2.F \
ccsdt_lambda1_9_3.F \
ccsdt_lambda1_9_4_1.F \
ccsdt_lambda1_9_4_2.F \
ccsdt_lambda1_9_4_3.F \
ccsdt_lambda1_9_4.F \
ccsdt_lambda1_9_5_1.F \
ccsdt_lambda1_9_5_2.F \
ccsdt_lambda1_9_5.F \
ccsdt_lambda1_9_6_1.F \
ccsdt_lambda1_9_6.F \
ccsdt_lambda1_9.F \
ccsdt_lambda2_10_2_2_2.F \
ccsdt_lambda2_10_2_2.F \
ccsdt_lambda2_10_2_3.F \
ccsdt_lambda2_10_2_4.F \
ccsdt_lambda2_10_2.F \
ccsdt_lambda2_10_3_2.F \
ccsdt_lambda2_10_3_3.F \
ccsdt_lambda2_10_3.F \
ccsdt_lambda2_10_4.F \
ccsdt_lambda2_10_5_2.F \
ccsdt_lambda2_10_5.F \
ccsdt_lambda2_10_6.F \
ccsdt_lambda2_10_7.F \
ccsdt_lambda2_10_8.F \
ccsdt_lambda2_10.F \
ccsdt_lambda2_11_2_2_2.F \
ccsdt_lambda2_11_2_2.F \
ccsdt_lambda2_11_2_3.F \
ccsdt_lambda2_11_2.F \
ccsdt_lambda2_11_3_2.F \
ccsdt_lambda2_11_3.F \
ccsdt_lambda2_11_4_2.F \
ccsdt_lambda2_11_4.F \
ccsdt_lambda2_11_5_2.F \
ccsdt_lambda2_11_5.F \
ccsdt_lambda2_11_6.F \
ccsdt_lambda2_11_7.F \
ccsdt_lambda2_11.F \
ccsdt_lambda2_12_2.F \
ccsdt_lambda2_12_3_2.F \
ccsdt_lambda2_12_3.F \
ccsdt_lambda2_12_4.F \
ccsdt_lambda2_12_5.F \
ccsdt_lambda2_12_6_1.F \
ccsdt_lambda2_12_6.F \
ccsdt_lambda2_12_7_1.F \
ccsdt_lambda2_12_7.F \
ccsdt_lambda2_12.F \
ccsdt_lambda2_13_1.F \
ccsdt_lambda2_13_2.F \
ccsdt_lambda2_13_3.F \
ccsdt_lambda2_13.F \
ccsdt_lambda2_14_1.F \
ccsdt_lambda2_14_2.F \
ccsdt_lambda2_14.F \
ccsdt_lambda2_15_1.F \
ccsdt_lambda2_15_2.F \
ccsdt_lambda2_15.F \
ccsdt_lambda2_16_1.F \
ccsdt_lambda2_16_2.F \
ccsdt_lambda2_16.F \
ccsdt_lambda2_17_1.F \
ccsdt_lambda2_17.F \
ccsdt_lambda2_18_1.F \
ccsdt_lambda2_18_2.F \
ccsdt_lambda2_18.F \
ccsdt_lambda2_19_1.F \
ccsdt_lambda2_19_2.F \
ccsdt_lambda2_19_3_1.F \
ccsdt_lambda2_19_3.F \
ccsdt_lambda2_19_4_1.F \
ccsdt_lambda2_19_4.F \
ccsdt_lambda2_19.F \
ccsdt_lambda2_20_1.F \
ccsdt_lambda2_20.F \
ccsdt_lambda2_21_1.F \
ccsdt_lambda2_21.F \
ccsdt_lambda2_22_1.F \
ccsdt_lambda2_2_2.F \
ccsdt_lambda2_22.F \
ccsdt_lambda2_23_1.F \
ccsdt_lambda2_23_2_1.F \
ccsdt_lambda2_23_2_2.F \
ccsdt_lambda2_23_2.F \
ccsdt_lambda2_23_3_1.F \
ccsdt_lambda2_23_3.F \
ccsdt_lambda2_23.F \
ccsdt_lambda2_24_1_1.F \
ccsdt_lambda2_24_1.F \
ccsdt_lambda2_24.F \
ccsdt_lambda2_25_1_1.F \
ccsdt_lambda2_25_1.F \
ccsdt_lambda2_25.F \
ccsdt_lambda2_26_1_1.F \
ccsdt_lambda2_26_1.F \
ccsdt_lambda2_26_2_1_1.F \
ccsdt_lambda2_26_2_1.F \
ccsdt_lambda2_26_2.F \
ccsdt_lambda2_26.F \
ccsdt_lambda2_2.F \
ccsdt_lambda2_3_2.F \
ccsdt_lambda2_3.F \
ccsdt_lambda2_4.F \
ccsdt_lambda2_5_2_2.F \
ccsdt_lambda2_5_2.F \
ccsdt_lambda2_5_3.F \
ccsdt_lambda2_5_4.F \
ccsdt_lambda2_5.F \
ccsdt_lambda2_6_2.F \
ccsdt_lambda2_6_3.F \
ccsdt_lambda2_6_4_1.F \
ccsdt_lambda2_6_4.F \
ccsdt_lambda2_6.F \
ccsdt_lambda2_7_2_2.F \
ccsdt_lambda2_7_2.F \
ccsdt_lambda2_7_3.F \
ccsdt_lambda2_7.F \
ccsdt_lambda2_8_2.F \
ccsdt_lambda2_8_3.F \
ccsdt_lambda2_8.F \
ccsdt_lambda2_9.F \
ccsdt_lambda3.F


LIB_DEFINES = -DDEBUG_PRINT
#
# Possible #defines
#
#              -DDEBUG_PRINT          /* Debug printing routines */
#	       -DNOCOMMS              /* Turn off ALL communication calls */
#              -DBLOCK_TRANSF         /* Use block-transfer for comms calls */
#              -DOLD_AOBLOCK          /* Recover original AO blocking scheme */
#

HEADERS = 

include ../../config/makefile.h
include ../../config/makelib.h

