#$Id: GNUmakefile,v 1.7 2008-10-10 19:35:05 niri Exp $

OBJ =

OBJ_OPTIMIZE = 

LIBRARY = libnwdft.a

USES_BLAS =

LIB_DEFINES = -DDEBUG_PRINT

HEADERS = 

include ../../config/makefile.h
include ../../config/makelib.h

