# $Id: GNUmakefile,v 1.8 1997-02-17 20:52:45 d3g681 Exp $
       HEADERS = 
  OBJ_OPTIMIZE = vib_callg.o
           OBJ = vib_bcalc.o \
                 vib_bdiha5.o \
                 vib_bend.o \
                 vib_bmat.o \
                 vib_bstr.o \
                 vib_cebdab.o \
                 vib_chkhess.o \
                 vib_clean.o \
                 vib_cross.o \
                 vib_dsquar.o \
                 vib_dtrngl.o \
                 vib_eckart.o \
                 vib_gtors.o \
                 vib_hmass.o \
                 vib_libe.o \
                 vib_nmass.o \
                 vib_opla.o \
                 vib_prdata.o \
                 vib_prntpd.o \
                 vib_przdat.o \
                 vib_rdinp.o \
                 vib_setup.o \
                 vib_tors.o \
                 vib_transp.o \
                 vib_vib.o \
                 vib_wmatrix.o \
                 vib_wrtfreq.o \
                 vib_zmatin.o

       LIBRARY = libvib.a
   LIB_TARGETS = 

     USES_BLAS = vib_hmass.F vib_wrtfreq.F vib_tors.F

include ../config/makefile.h
include ../config/makelib.h





