# $Id: GNUmakefile,v 1.10 1994-10-20 23:31:52 d3e129 Exp $

   OBJ_OPTIMIZE = int_normalize.o nmcoef.o nmcoef2c.o int_norm_2c.o int_chk_sum.o 
            OBJ = do_int_chk_sum.o 
LIBRARY = libnwints.a

include ../../config/makefile.h
include ../../config/makelib.h
