#
# $Id: GNUmakefile,v 1.1 2001-08-30 17:41:40 bylaska Exp $
#
# intf and aux break on IBM SP xlhpf with optimization ... why? 

 OBJ_OPTIMIZE = \
            D3dB-new.o


	  OBJ = 

      LIBRARY = libnwpwlib.a

    USES_BLAS = D3dB-new.F

  LIB_DEFINES = 


include ../../../config/makefile.h
include ../../../config/makelib.h

