#
# $Id: GNUmakefile,v 1.1 2002-07-12 21:15:32 marat Exp $
#

          OBJ = paw_kin_matrix.o paw_ion_matrix.o


      LIBRARY =	libpaw.a

   USES_BLAS = 

  LIB_INCLUDES = -I../include/

  LIB_DEFINES = 




include ../../../config/makefile.h
include ../../../config/makelib.h
include ../makefile.h












