#
# $Id: GNUmakefile,v 1.3 2002-08-06 19:11:18 marat Exp $
#

          OBJ = paw_kin_matrix.o paw_ion_matrix.o paw_vloc_matrix.o paw_core_matrix.o \
                paw_hartree_matrix.o


      LIBRARY =	libpaw.a

   USES_BLAS = 

  LIB_INCLUDES = -I../include/

  LIB_DEFINES = 




include ../../../config/makefile.h
include ../../../config/makelib.h
include ../makefile.h












