#
# $Id: GNUmakefile,v 1.33 2008-04-22 17:41:42 marat Exp $
#

#       SUBDIRS = smd-subgroups
       SUBDIRS = smd-new smd-rtdb
#       SUBDIRS = smd-parallel




include ../config/makefile.h
include ../config/makelib.h









