#
# $Id: GNUmakefile,v 1.3 2008-01-12 00:44:39 marat Exp $
#

       SUBDIRS = 

          OBJ = task_smd.o smd_input.o \
		chg_case.o ewald_self.o frce_shel.o \
		list_const.o md_inpt.o scle_velo.o \
		com_motion.o ewald_setp.o frce_shrt.o \
		list_excld.o  md_scle.o shll_qnch.o \
		erfc.o extrct_char.o init_velo.o \
		list_shell.o print_final.o tool_invrt.o \
		ewald_excl.o extrct_inte.o inte_leapf.o  \
		list_verlt.o print_output.o tool_rebox.o \
		ewald_real.o extrct_real.o inte_shake.o  \
		md_frce.o tool_randm.o tool_volme.o \
		ewald_recp.o frce_bond.o list_bonds.o  \
		md_init.o read_line.o verlt_test.o  \
                smd_init.o smd_res_data.o \
                smd_pdb.o smd_atom_data.o

      LIBRARY = libsmd.a


  LIB_DEFINES =




include ../config/makefile.h
include ../config/makelib.h









