#
# $Id$
#

 OBJ_OPTIMIZE = \
            c_ewald.o



	  OBJ = 

      LIBRARY = libband.a

    USES_BLAS = c_ewald.F

  LIB_DEFINES = 


include ../../../../config/makefile.h
include ../../../../config/makelib.h

