#
# $Id: GNUmakefile,v 1.1 2001-12-13 03:53:31 bylaska Exp $
#

 OBJ_OPTIMIZE = \
            c_ewald.o



	  OBJ = 

      LIBRARY = libband.a

    USES_BLAS = c_ewald.F

  LIB_DEFINES = 


include ../../../../config/makefile.h
include ../../../../config/makelib.h

