#
# $Id: GNUmakefile,v 1.4 2002-02-11 18:27:11 edo Exp $
#

 OBJ_OPTIMIZE = \
			cpsi.o \
		 	c_geodesic.o \
			cpsi_lmbda.o \
			Stiefel.o \
			check.o \
			cpsi_read.o \
			cpsi_write.o \
			cpsi_new.o



	  OBJ = 

      LIBRARY = libband.a

    USES_BLAS = cpsi.F c_geodesic.F cpsi_lmbda.F Stiefel.F cpsi_lmbda.F

  LIB_DEFINES = 


include ../../../../config/makefile.h
include ../../../../config/makelib.h

