#
# $Id: GNUmakefile,v 1.2 2001-12-15 03:11:01 bylaska Exp $
#

 OBJ_OPTIMIZE = \
			cpsi.o \
			Stiefel.o \
			check.o \
			cpsi_read.o \
			cpsi_write.o \
			cpsi_new.o



	  OBJ = 

      LIBRARY = libband.a

    USES_BLAS = cpsi.F

  LIB_DEFINES = 


include ../../../../config/makefile.h
include ../../../../config/makelib.h

