#
# $Id: GNUmakefile,v 1.2 2004-10-15 01:59:40 edo Exp $
#

  LIBRARY = libperfm.a
  
  OBJ = perfm_start.o perfm_end.o perfm_flop.o

USES_BLAS = 

include ../config/makefile.h
include ../config/makelib.h

