#$Id: GNUmakefile,v 1.6 1995-02-02 23:12:35 d3g681 Exp $
       OBJ = rjhtest.o raktest.o debtest.o
   LIBRARY = libtest.a

USES_BLAS =     raktest.F rjhtest.F

include ../config/makefile.h
include ../config/makelib.h
