#$Id$

       OBJ = rjhtest.o raktest.o raktest_semi.o debtest.o raktestc.o \
             rak18.o rak19.o rak20.o rak21.o rak22.o rak23.o rak24.o \
             rak25.o rak26.o rak27.o rak28.o rak29.o rak30.o rak31.o\
             kgdtest.o  \
             jvltest.o gaussq_netlib.o rjhtrans.o cct_UHF.o  

#  OBJ += 
  OBJ_OPTIMIZE = jantest.o uccsdtest.o

   LIBRARY = libtest.a

USES_BLAS =     raktest.F rak20.F rak21.F rak22.F rak23.F jvltest.F rjhtrans.F cct_UHF.F rak25.F rak26.F rak27.F rak29.F rak30.F

include ../config/makefile.h
include ../config/makelib.h

