#$Id: GNUmakefile,v 1.31 1998-11-16 02:46:53 jhvan Exp $

       OBJ = rjhtest.o raktest.o raktest_semi.o debtest.o raktestc.o \
             rak18.o rak19.o rak20.o rak21.o rak22.o rak23.o kgdtest.o \
             jvltest.o gaussq_netlib.o 

   LIBRARY = libtest.a

USES_BLAS =     raktest.F rak20.F rak21.F rak22.F rak23.F

include ../config/makefile.h
include ../config/makelib.h

