# $Id: GNUmakefile,v 1.1 1994-10-20 23:50:49 pg511 Exp $

      OBJ_OPTIMIZE = \
	banner_dft.o			   inpana.o \
	rdbasis.o				    \
	rdcalc.o			   \
	rdinput.o			   rdprop.o \
	rdquad.o			   setbasis.o \
	setquad.o

     LIBRARY = libnwdft.a

#   USES_BLAS =

include ../../config/makefile.h
include ../../config/makelib.h


