#$Id$

#ifndef CCSDTQ
#OBJ_OPTIMIZE = \
#ccsdtq_e.o\
#ccsdtq_t1.o\
#ccsdtq_t2.o\
#ccsdtq_t3.o\
#ccsdtq_t4.o
#else
OBJ_OPTIMIZE = \
ccsdtq_e.o\
ccsdtq_t1.o\
ccsdtq_t2.o\
ccsdtq_t3.o\
ccsdtq_t4.o\
ccsdtq_t3_1.o\
ccsdtq_t3_1_1.o\
OFFSET_ccsdtq_t3_1_1.o\
ccsdtq_t3_1_2.o\
ccsdtq_t3_1_2_1.o\
OFFSET_ccsdtq_t3_1_2_1.o\
ccsdtq_t3_1_2_2.o\
ccsdtq_t3_1_2_2_1.o\
OFFSET_ccsdtq_t3_1_2_2_1.o\
ccsdtq_t3_1_2_2_2.o\
ccsdtq_t3_1_2_3.o\
ccsdtq_t3_1_3.o\
ccsdtq_t3_1_3_1.o\
OFFSET_ccsdtq_t3_1_3_1.o\
ccsdtq_t3_1_3_2.o\
ccsdtq_t3_1_4.o\
ccsdtq_t3_1_4_1.o\
OFFSET_ccsdtq_t3_1_4_1.o\
ccsdtq_t3_1_4_2.o\
ccsdtq_t3_1_5.o\
ccsdtq_t3_1_5_1.o\
OFFSET_ccsdtq_t3_1_5_1.o\
ccsdtq_t3_1_5_2.o\
ccsdtq_t3_1_6.o\
ccsdtq_t3_1_7.o\
ccsdtq_t3_2.o\
ccsdtq_t3_2_1.o\
OFFSET_ccsdtq_t3_2_1.o\
ccsdtq_t3_2_2.o\
ccsdtq_t3_2_3.o\
ccsdtq_t3_2_3_1.o\
OFFSET_ccsdtq_t3_2_3_1.o\
ccsdtq_t3_2_3_2.o\
ccsdtq_t3_2_4.o\
ccsdtq_t3_2_5.o\
ccsdtq_t3_3.o\
ccsdtq_t3_3_1.o\
OFFSET_ccsdtq_t3_3_1.o\
ccsdtq_t3_3_2.o\
ccsdtq_t3_3_2_1.o\
OFFSET_ccsdtq_t3_3_2_1.o\
ccsdtq_t3_3_2_2.o\
ccsdtq_t3_3_3.o\
ccsdtq_t3_3_4.o\
ccsdtq_t3_4.o\
ccsdtq_t3_4_1.o\
OFFSET_ccsdtq_t3_4_1.o\
ccsdtq_t3_4_2.o\
ccsdtq_t3_4_3.o\
ccsdtq_t3_5.o\
ccsdtq_t3_5_1.o\
OFFSET_ccsdtq_t3_5_1.o\
ccsdtq_t3_5_2.o\
ccsdtq_t3_5_2_1.o\
OFFSET_ccsdtq_t3_5_2_1.o\
ccsdtq_t3_5_2_2.o\
ccsdtq_t3_5_3.o\
ccsdtq_t3_6.o\
ccsdtq_t3_6_1.o\
OFFSET_ccsdtq_t3_6_1.o\
ccsdtq_t3_6_2.o\
ccsdtq_t3_6_3.o\
ccsdtq_t3_7.o\
ccsdtq_t3_8.o\
ccsdtq_t3_8_1.o\
OFFSET_ccsdtq_t3_8_1.o\
ccsdtq_t3_8_2.o\
ccsdtq_t3_9.o\
ccsdtq_t3_9_1.o\
OFFSET_ccsdtq_t3_9_1.o\
ccsdtq_t3_9_2.o\
ccsdtq_t3_10.o\
ccsdtq_t3_11.o\
ccsdtq_t3_11_1.o\
OFFSET_ccsdtq_t3_11_1.o\
ccsdtq_t3_11_1_1.o\
OFFSET_ccsdtq_t3_11_1_1.o\
ccsdtq_t3_11_1_2.o\
ccsdtq_t3_11_1_2_1.o\
OFFSET_ccsdtq_t3_11_1_2_1.o\
ccsdtq_t3_11_1_2_2.o\
ccsdtq_t3_11_1_3.o\
ccsdtq_t3_11_1_4.o\
ccsdtq_t3_11_2.o\
ccsdtq_t3_11_2_1.o\
OFFSET_ccsdtq_t3_11_2_1.o\
ccsdtq_t3_11_2_2.o\
ccsdtq_t3_11_3.o\
ccsdtq_t3_11_3_1.o\
OFFSET_ccsdtq_t3_11_3_1.o\
ccsdtq_t3_11_3_2.o\
ccsdtq_t3_11_4.o\
ccsdtq_t3_11_5.o\
ccsdtq_t3_11_6.o\
ccsdtq_t3_11_6_1.o\
OFFSET_ccsdtq_t3_11_6_1.o\
ccsdtq_t3_12.o\
ccsdtq_t3_12_1.o\
OFFSET_ccsdtq_t3_12_1.o\
ccsdtq_t4_1.o\
ccsdtq_t4_1_1.o\
OFFSET_ccsdtq_t4_1_1.o\
ccsdtq_t4_1_2.o\
ccsdtq_t4_1_2_1.o\
OFFSET_ccsdtq_t4_1_2_1.o\
ccsdtq_t4_1_2_2.o\
ccsdtq_t4_1_2_2_1.o\
OFFSET_ccsdtq_t4_1_2_2_1.o\
ccsdtq_t4_1_2_2_2.o\
ccsdtq_t4_1_2_3.o\
ccsdtq_t4_1_3.o\
ccsdtq_t4_1_3_1.o\
OFFSET_ccsdtq_t4_1_3_1.o\
ccsdtq_t4_1_3_2.o\
ccsdtq_t4_1_4.o\
ccsdtq_t4_1_4_1.o\
OFFSET_ccsdtq_t4_1_4_1.o\
ccsdtq_t4_1_4_2.o\
ccsdtq_t4_1_5.o\
ccsdtq_t4_1_5_1.o\
OFFSET_ccsdtq_t4_1_5_1.o\
ccsdtq_t4_1_5_2.o\
ccsdtq_t4_1_6.o\
ccsdtq_t4_1_7.o\
ccsdtq_t4_2.o\
ccsdtq_t4_2_1.o\
OFFSET_ccsdtq_t4_2_1.o\
ccsdtq_t4_2_2.o\
ccsdtq_t4_2_3.o\
ccsdtq_t4_2_3_1.o\
OFFSET_ccsdtq_t4_2_3_1.o\
ccsdtq_t4_2_3_2.o\
ccsdtq_t4_2_4.o\
ccsdtq_t4_2_5.o\
ccsdtq_t4_3.o\
ccsdtq_t4_3_1.o\
OFFSET_ccsdtq_t4_3_1.o\
ccsdtq_t4_3_2.o\
ccsdtq_t4_3_2_1.o\
OFFSET_ccsdtq_t4_3_2_1.o\
ccsdtq_t4_3_2_2.o\
ccsdtq_t4_3_3.o\
ccsdtq_t4_3_4.o\
ccsdtq_t4_4.o\
ccsdtq_t4_4_1.o\
OFFSET_ccsdtq_t4_4_1.o\
ccsdtq_t4_4_2.o\
ccsdtq_t4_4_3.o\
ccsdtq_t4_5.o\
ccsdtq_t4_5_1.o\
OFFSET_ccsdtq_t4_5_1.o\
ccsdtq_t4_5_2.o\
ccsdtq_t4_5_2_1.o\
OFFSET_ccsdtq_t4_5_2_1.o\
ccsdtq_t4_5_2_2.o\
ccsdtq_t4_5_3.o\
ccsdtq_t4_6.o\
ccsdtq_t4_6_1.o\
OFFSET_ccsdtq_t4_6_1.o\
ccsdtq_t4_6_2.o\
ccsdtq_t4_6_3.o\
ccsdtq_t4_7.o\
ccsdtq_t4_8.o\
ccsdtq_t4_8_1.o\
OFFSET_ccsdtq_t4_8_1.o\
ccsdtq_t4_8_1_1.o\
OFFSET_ccsdtq_t4_8_1_1.o\
ccsdtq_t4_8_1_2.o\
ccsdtq_t4_8_1_2_1.o\
OFFSET_ccsdtq_t4_8_1_2_1.o\
ccsdtq_t4_8_1_2_2.o\
ccsdtq_t4_8_1_3.o\
ccsdtq_t4_8_1_4.o\
ccsdtq_t4_8_2.o\
ccsdtq_t4_8_2_1.o\
OFFSET_ccsdtq_t4_8_2_1.o\
ccsdtq_t4_8_2_2.o\
ccsdtq_t4_8_3.o\
ccsdtq_t4_8_3_1.o\
OFFSET_ccsdtq_t4_8_3_1.o\
ccsdtq_t4_8_3_2.o\
ccsdtq_t4_8_4.o\
ccsdtq_t4_8_5.o\
ccsdtq_t4_8_5_1.o\
OFFSET_ccsdtq_t4_8_5_1.o\
ccsdtq_t4_8_6.o\
ccsdtq_t4_8_6_1.o\
OFFSET_ccsdtq_t4_8_6_1.o\
ccsdtq_t4_8_6_1_1.o\
OFFSET_ccsdtq_t4_8_6_1_1.o\
ccsdtq_t4_8_6_1_2.o\
ccsdtq_t4_8_6_2.o\
ccsdtq_t4_9.o\
ccsdtq_t4_9_1.o\
OFFSET_ccsdtq_t4_9_1.o\
ccsdtq_t4_9_1_1.o\
OFFSET_ccsdtq_t4_9_1_1.o\
ccsdtq_t4_9_1_2.o\
ccsdtq_t4_9_1_2_1.o\
OFFSET_ccsdtq_t4_9_1_2_1.o\
ccsdtq_t4_9_1_2_2.o\
ccsdtq_t4_9_1_3.o\
ccsdtq_t4_9_2.o\
ccsdtq_t4_9_2_1.o\
OFFSET_ccsdtq_t4_9_2_1.o\
ccsdtq_t4_9_2_2.o\
ccsdtq_t4_9_2_2_1.o\
OFFSET_ccsdtq_t4_9_2_2_1.o\
ccsdtq_t4_9_2_2_2.o\
ccsdtq_t4_9_2_3.o\
ccsdtq_t4_9_2_4.o\
ccsdtq_t4_9_3.o\
ccsdtq_t4_9_3_1.o\
OFFSET_ccsdtq_t4_9_3_1.o\
ccsdtq_t4_9_3_2.o\
ccsdtq_t4_9_4.o\
ccsdtq_t4_9_4_1.o\
OFFSET_ccsdtq_t4_9_4_1.o\
ccsdtq_t4_9_4_2.o\
ccsdtq_t4_9_5.o\
ccsdtq_t4_9_5_1.o\
OFFSET_ccsdtq_t4_9_5_1.o\
ccsdtq_t4_9_5_2.o\
ccsdtq_t4_9_6.o\
ccsdtq_t4_10.o\
ccsdtq_t4_10_1.o\
OFFSET_ccsdtq_t4_10_1.o\
ccsdtq_t4_10_1_1.o\
OFFSET_ccsdtq_t4_10_1_1.o\
ccsdtq_t4_10_1_2.o\
ccsdtq_t4_10_2.o\
ccsdtq_t4_10_2_1.o\
OFFSET_ccsdtq_t4_10_2_1.o\
ccsdtq_t4_10_2_2.o\
ccsdtq_t4_10_3.o\
ccsdtq_t4_10_4.o\
ccsdtq_t4_11.o\
ccsdtq_t4_11_1.o\
OFFSET_ccsdtq_t4_11_1.o\
ccsdtq_t4_12.o\
ccsdtq_t4_12_1.o\
OFFSET_ccsdtq_t4_12_1.o\
ccsdtq_t4_13.o\
ccsdtq_t4_13_1.o\
OFFSET_ccsdtq_t4_13_1.o

USES_BLAS = ccsdtq_e.F \
ccsdtq_t1.F \
ccsdtq_t2.F \
ccsdtq_t3_10.F \
ccsdtq_t3_11_1_2_2.F \
ccsdtq_t3_11_1_2.F \
ccsdtq_t3_11_1_3.F \
ccsdtq_t3_11_1_4.F \
ccsdtq_t3_11_1.F \
ccsdtq_t3_11_2_2.F \
ccsdtq_t3_11_2.F \
ccsdtq_t3_11_3_2.F \
ccsdtq_t3_11_3.F \
ccsdtq_t3_11_4.F \
ccsdtq_t3_11_5.F \
ccsdtq_t3_11_6_1.F \
ccsdtq_t3_11_6.F \
ccsdtq_t3_11.F \
ccsdtq_t3_12_1.F \
ccsdtq_t3_1_2_2_2.F \
ccsdtq_t3_1_2_2.F \
ccsdtq_t3_1_2_3.F \
ccsdtq_t3_1_2.F \
ccsdtq_t3_12.F \
ccsdtq_t3_1_3_2.F \
ccsdtq_t3_1_3.F \
ccsdtq_t3_1_4_2.F \
ccsdtq_t3_1_4.F \
ccsdtq_t3_1_5_2.F \
ccsdtq_t3_1_5.F \
ccsdtq_t3_1_6.F \
ccsdtq_t3_1_7.F \
ccsdtq_t3_1.F \
ccsdtq_t3_2_2.F \
ccsdtq_t3_2_3_2.F \
ccsdtq_t3_2_3.F \
ccsdtq_t3_2_4.F \
ccsdtq_t3_2_5.F \
ccsdtq_t3_2.F \
ccsdtq_t3_3_2_2.F \
ccsdtq_t3_3_2.F \
ccsdtq_t3_3_3.F \
ccsdtq_t3_3_4.F \
ccsdtq_t3_3.F \
ccsdtq_t3_4_2.F \
ccsdtq_t3_4_3.F \
ccsdtq_t3_4.F \
ccsdtq_t3_5_2_2.F \
ccsdtq_t3_5_2.F \
ccsdtq_t3_5_3.F \
ccsdtq_t3_5.F \
ccsdtq_t3_6_2.F \
ccsdtq_t3_6_3.F \
ccsdtq_t3_6.F \
ccsdtq_t3_7.F \
ccsdtq_t3_8_2.F \
ccsdtq_t3_8.F \
ccsdtq_t3_9_2.F \
ccsdtq_t3_9.F \
ccsdtq_t4_10_1_2.F \
ccsdtq_t4_10_1.F \
ccsdtq_t4_10_2_2.F \
ccsdtq_t4_10_2.F \
ccsdtq_t4_10_3.F \
ccsdtq_t4_10_4.F \
ccsdtq_t4_10.F \
ccsdtq_t4_11_1.F \
ccsdtq_t4_11.F \
ccsdtq_t4_12_1.F \
ccsdtq_t4_1_2_2_2.F \
ccsdtq_t4_1_2_2.F \
ccsdtq_t4_1_2_3.F \
ccsdtq_t4_1_2.F \
ccsdtq_t4_12.F \
ccsdtq_t4_13_1.F \
ccsdtq_t4_1_3_2.F \
ccsdtq_t4_1_3.F \
ccsdtq_t4_13.F \
ccsdtq_t4_1_4_2.F \
ccsdtq_t4_1_4.F \
ccsdtq_t4_1_5_2.F \
ccsdtq_t4_1_5.F \
ccsdtq_t4_1_6.F \
ccsdtq_t4_1_7.F \
ccsdtq_t4_1.F \
ccsdtq_t4_2_2.F \
ccsdtq_t4_2_3_2.F \
ccsdtq_t4_2_3.F \
ccsdtq_t4_2_4.F \
ccsdtq_t4_2_5.F \
ccsdtq_t4_2.F \
ccsdtq_t4_3_2_2.F \
ccsdtq_t4_3_2.F \
ccsdtq_t4_3_3.F \
ccsdtq_t4_3_4.F \
ccsdtq_t4_3.F \
ccsdtq_t4_4_2.F \
ccsdtq_t4_4_3.F \
ccsdtq_t4_4.F \
ccsdtq_t4_5_2_2.F \
ccsdtq_t4_5_2.F \
ccsdtq_t4_5_3.F \
ccsdtq_t4_5.F \
ccsdtq_t4_6_2.F \
ccsdtq_t4_6_3.F \
ccsdtq_t4_6.F \
ccsdtq_t4_7.F \
ccsdtq_t4_8_1_2_2.F \
ccsdtq_t4_8_1_2.F \
ccsdtq_t4_8_1_3.F \
ccsdtq_t4_8_1_4.F \
ccsdtq_t4_8_1.F \
ccsdtq_t4_8_2_2.F \
ccsdtq_t4_8_2.F \
ccsdtq_t4_8_3_2.F \
ccsdtq_t4_8_3.F \
ccsdtq_t4_8_4.F \
ccsdtq_t4_8_5_1.F \
ccsdtq_t4_8_5.F \
ccsdtq_t4_8_6_1_2.F \
ccsdtq_t4_8_6_1.F \
ccsdtq_t4_8_6_2.F \
ccsdtq_t4_8_6.F \
ccsdtq_t4_8.F \
ccsdtq_t4_9_1_2_2.F \
ccsdtq_t4_9_1_2.F \
ccsdtq_t4_9_1_3.F \
ccsdtq_t4_9_1.F \
ccsdtq_t4_9_2_2_2.F \
ccsdtq_t4_9_2_2.F \
ccsdtq_t4_9_2_3.F \
ccsdtq_t4_9_2_4.F \
ccsdtq_t4_9_2.F \
ccsdtq_t4_9_3_2.F \
ccsdtq_t4_9_3.F \
ccsdtq_t4_9_4_2.F \
ccsdtq_t4_9_4.F \
ccsdtq_t4_9_5_2.F \
ccsdtq_t4_9_5.F \
ccsdtq_t4_9_6.F \
ccsdtq_t4_9.F

#endif

LIB_INCLUDES = -I../include

LIBRARY = libtce.a



#ifndef CCSDTQ
#LIB_DEFINES = -DDEBUG_PRINT
#else
#LIB_DEFINES = -DDEBUG_PRINT -DCCSDTQ
#endif

#
# Possible #defines
#
#              -DDEBUG_PRINT          /* Debug printing routines */
#	       -DNOCOMMS              /* Turn off ALL communication calls */
#              -DBLOCK_TRANSF         /* Use block-transfer for comms calls */
#              -DOLD_AOBLOCK          /* Recover original AO blocking scheme */
#

HEADERS = 

include ../../config/makefile.h
include ../../config/makelib.h

