#
# $Id$
#
 OBJ_OPTIMIZE = \
				band_stress_numerical.o \
				band_stress_fd.o \
				band_cell_optimize.o \
				band_update_unitcell.o
                
	  OBJ = 



      LIBRARY = libband.a

    USES_BLAS = band_stress_fd.F band_update_unitcell.F
                

  LIB_DEFINES =


include ../../../config/makefile.h
include ../../../config/makelib.h

