#
# $Id: GNUmakefile,v 1.1 2004-11-29 16:05:16 bylaska Exp $
#
 OBJ_OPTIMIZE = \
				band_stress_numerical.o \
				band_stress_fd.o \
				band_cell_optimize.o \
				band_update_unitcell.o
                
	  OBJ = 



      LIBRARY = libband.a

    USES_BLAS = 
                

  LIB_DEFINES =


include ../../../config/makefile.h
include ../../../config/makelib.h

