#
# $Id: GNUmakefile,v 1.1 2001-12-13 03:49:54 bylaska Exp $
#

 OBJ_OPTIMIZE = \
            ion.o



	  OBJ = 

      LIBRARY = libpspw.a

    USES_BLAS = 

  LIB_DEFINES = 


include ../../../../config/makefile.h
include ../../../../config/makelib.h

