#
# $Id$
#

 OBJ_OPTIMIZE = \
            ion_ion.o



	  OBJ = 

      LIBRARY = libpspw.a

    USES_BLAS = 

  LIB_DEFINES = 


include ../../../../config/makefile.h
include ../../../../config/makelib.h

