#
# $Id$
#

          OBJ_OPTIMIZE = paw_matrix_hartree.o paw_pot_hartree.o \
                          paw_energy_hartree_atom.o
          HEADERS = paw_energy_hartree_atom.fh


      LIBRARY =	libpaw.a

   USES_BLAS =  paw_pot_hartree.F paw_matrix_hartree.F

  LIB_INCLUDES = -I../include/

  LIB_DEFINES = 




include ../../../config/makefile.h
include ../../../config/makelib.h


