#
# $Id: GNUmakefile,v 1.3 2004-03-04 15:12:22 bylaska Exp $
#

          OBJ_OPTIMIZE = paw_matrix_hartree.o paw_pot_hartree.o \
                          paw_energy_hartree_atom.o
          HEADERS = paw_energy_hartree_atom.fh


      LIBRARY =	libpaw.a

   USES_BLAS = 

  LIB_INCLUDES = -I../include/

  LIB_DEFINES = 




include ../../../config/makefile.h
include ../../../config/makelib.h


