#
# $Id: GNUmakefile,v 1.1 2003-02-13 20:23:03 marat Exp $
#

          OBJ = paw_matrix_hartree.o paw_pot_hartree.o
          HEADERS = 


      LIBRARY =	libpaw.a

   USES_BLAS = 

  LIB_INCLUDES = -I../include/

  LIB_DEFINES = 




include ../../../config/makefile.h
include ../../../config/makelib.h


