#
# $Id: GNUmakefile 25011 2013-12-19 17:45:25Z d3y133 $
#

 OBJ_OPTIMIZE = \
		md_xs_input.o \
		md_xs.o

	  OBJ = 

      LIBRARY = libnwpwlib.a

    USES_BLAS = 

  LIB_DEFINES = 


include ../../../config/makefile.h
include ../../../config/makelib.h


ifeq ($(USE_FEFF),y)
  LIB_DEFINES += -DFEFF
endif

