#
# $Id: GNUmakefile,v 1.9 2003-02-19 01:11:22 marat Exp $
#


          OBJ = paw_utils.o integrate.o io_utils.o error.o double_factorial.o bessel_transform.o \
                paw_gauss_weights.o paw_spher_grid.o

          HEADERS = bessel_transform.fh integrate.fh paw_utils.fh paw_params.fh


      LIBRARY =	libpaw.a

   USES_BLAS = integrate.F

  LIB_INCLUDES = -I../include/

  LIB_DEFINES = 




include ../../../config/makefile.h
include ../../../config/makelib.h
include ../makefile.h












