#
# $Id: GNUmakefile,v 1.2 2002-08-07 22:10:31 marat Exp $
#

          OBJ = paw_utils.o \
                integrate.o io_utils.o error.o double_factorial.o


      LIBRARY =	libpaw.a

   USES_BLAS = 

  LIB_INCLUDES = -I../include

  LIB_DEFINES = 




include ../../../config/makefile.h
include ../../../config/makelib.h
include ../makefile.h










