#
# $Id: GNUmakefile,v 1.6 2003-01-31 02:01:12 bylaska Exp $
#


          OBJ = paw_utils.o integrate.o io_utils.o error.o double_factorial.o bessel_transform.o

          HEADERS = bessel_transform.fh integrate.fh paw_utils.fh paw_params.fh


      LIBRARY =	libpaw.a

   USES_BLAS = 

  LIB_INCLUDES = -I../include/

  LIB_DEFINES = 




include ../../../config/makefile.h
include ../../../config/makelib.h
include ../makefile.h












