#
# $Id$
#

 OBJ_OPTIMIZE = \
            	cpsp.o \
            	cpsp_relativistic.o \
            	cpsp_projector.o \
            	cpsp_stress.o \
		c_semicore.o \
		c_semicore_force.o 



	  OBJ = 

      LIBRARY = libband.a

    USES_BLAS = cpsp.F cpsp_stress.F c_semicore.F cpsp_projector.F c_semicore_force_a.F c_semicore_force_b.F cpsp_relativistic.F cpsp_U.F


  LIB_DEFINES = 


include ../../../../config/makefile.h
include ../../../../config/makelib.h

