#
# $Id: GNUmakefile,v 1.1 2001-12-13 03:53:31 bylaska Exp $
#

 OBJ_OPTIMIZE = \
            cpsp.o \
			c_semicore.o \
			c_semicore_force.o 



	  OBJ = 

      LIBRARY = libband.a

    USES_BLAS = cpsp.F

  LIB_DEFINES = 


include ../../../../config/makefile.h
include ../../../../config/makelib.h

