#
# $Id: GNUmakefile,v 1.3 2005-09-07 23:55:03 bylaska Exp $
#

 OBJ_OPTIMIZE = \
            	cpsp.o \
            	cpsp_stress.o \
		c_semicore.o \
		c_semicore_force.o 



	  OBJ = 

      LIBRARY = libband.a

    USES_BLAS = cpsp.F cpsp_stress.F c_semicore.F

  LIB_DEFINES = 


include ../../../../config/makefile.h
include ../../../../config/makelib.h

