#
# $Id: GNUmakefile,v 1.1 2003-02-11 22:42:43 marat Exp $
#

          OBJ = paw_energy_core_atom.o paw_matrix_core.o
          HEADERS = paw_energy_core_atom.fh 


      LIBRARY =	libpaw.a

   USES_BLAS = 

  LIB_INCLUDES = -I../include/

  LIB_DEFINES = 




include ../../../config/makefile.h
include ../../../config/makelib.h
include ../makefile.h


