#
# $Id: GNUmakefile,v 1.2 2004-03-04 15:12:22 bylaska Exp $
#

          OBJ_OPTIMIZE = paw_energy_core_atom.o paw_matrix_core.o
          HEADERS = paw_energy_core_atom.fh 


      LIBRARY =	libpaw.a

   USES_BLAS = 

  LIB_INCLUDES = -I../include/

  LIB_DEFINES = 




include ../../../config/makefile.h
include ../../../config/makelib.h
include ../makefile.h


