LIBRARY = libccsd.a

LIB_DEFINES = -DLONGINTEGER=integer

OBJ_OPTIMIZE = moints_shpair.o soints.o triples_kernels.o moscreen.o uccsdt.o amplitudes.o draftt2s.o

#ga_long1d.o 


include ../config/makefile.h
include ../config/makelib.h
