LIBRARY = libccsd.a

LIB_DEFINES = -DLONGINTEGER=integer

OBJ = uccsdt.o amplitudes.o
OBJ_OPTIMIZE = moints_shpair.o soints.o triples_kernels.o

#ga_long1d.o 


include ../config/makefile.h
include ../config/makelib.h
