#
# $Id$
#

 OBJ_OPTIMIZE = \
            band_hfx.o


	  OBJ = 

      LIBRARY = libband.a

    USES_BLAS = band_hfx.F

  LIB_DEFINES = 



include ../../../../config/makefile.h
include ../../../../config/makelib.h

