#
# $Id: GNUmakefile,v 1.2 2001-12-17 23:31:11 bylaska Exp $
#

 OBJ_OPTIMIZE = \
            band_hfx.o


	  OBJ = 

      LIBRARY = libband.a

    USES_BLAS = band_hfx.F

  LIB_DEFINES = 



include ../../../../config/makefile.h
include ../../../../config/makelib.h

