#
# $Id: GNUmakefile,v 1.2 2003-02-15 00:24:29 marat Exp $
#

          OBJ = paw_matrix_comp_pot.o paw_pot_comp.o
          



      LIBRARY =	libpaw.a

   USES_BLAS = 

  LIB_INCLUDES = 

  LIB_DEFINES = 

  HEADERS = 
           





include ../../../config/makefile.h
include ../../../config/makelib.h












