#
# $Id: GNUmakefile,v 1.3 2003-02-21 22:36:33 bylaska Exp $
#

          OBJ = paw_matrix_comp_pot.o paw_pot_comp.o
          HEADERS = paw_matrix_comp_pot.fh paw_pot_comp_data.fh
          

      LIBRARY =	libpaw.a

   USES_BLAS = 

  LIB_INCLUDES = 

  LIB_DEFINES = 

  HEADERS = 
           





include ../../../config/makefile.h
include ../../../config/makelib.h












