#
# $Id: GNUmakefile,v 1.1 2003-02-14 19:55:07 marat Exp $
#

          OBJ = paw_matrix_comp_pot.o 
          



      LIBRARY =	libpaw.a

   USES_BLAS = 

  LIB_INCLUDES = 

  LIB_DEFINES = 

  HEADERS = 
           





include ../../../config/makefile.h
include ../../../config/makelib.h












