# $Id: GNUmakefile,v 1.5 2004-11-29 16:05:19 bylaska Exp $
#
 OBJ_OPTIMIZE = \
		paw_energy.o \
		paw_noit_energy.o \
		paw_gradient.o \
		paw_stress.o \
		paw_minimizer.o \
		paw_cgsd_energy.o \
		paw_cgminimize.o \
		paw_bfgsminimize.o \
		paw_nominimize.o \
		paw_cgsd_noit_energy.o


	  OBJ = 



      LIBRARY = libpaw.a

    USES_BLAS =  paw_bfgsminimize.F
                

  LIB_DEFINES =
  LIB_INCLUDES = -I../../nwpwlib/include



include ../../../config/makefile.h
include ../../../config/makelib.h
include ../makefile.h
