# $Id: GNUmakefile,v 1.4 2004-09-05 02:18:25 bylaska Exp $
#
 OBJ_OPTIMIZE = \
		paw_energy.o \
		paw_gradient.o \
		paw_minimizer.o \
		paw_cgsd_energy.o \
		paw_cgminimize.o \
		paw_bfgsminimize.o


	  OBJ = 



      LIBRARY = libpaw.a

    USES_BLAS =  paw_bfgsminimize.F
                

  LIB_DEFINES =
  LIB_INCLUDES = -I../../nwpwlib/include



include ../../../config/makefile.h
include ../../../config/makelib.h
include ../makefile.h
