
#OBJ          = 

OBJ_OPTIMIZE = tce_mrcc_q3vnt1.o  tce_mrcc_q3vnt2.o \
               tce_mrcc_q3fnt2.o tce_mrcc_ccsdpt.o \
               tce_mrcc_ccsdpt_subg.o tce_mrcc_q3vnt1_subg.o \
               tce_mrcc_q3fnt2_subg.o 

LIB_INCLUDES = -I../../include -I../include

LIBRARY = libtce.a

USES_BLAS = tce_mrcc_q3vnt1.F  tce_mrcc_q3vnt2.F \
            tce_mrcc_q3fnt2.F tce_mrcc_ccsdpt.F \
            tce_mrcc_ccsdpt_subg.F tce_mrcc_q3vnt1_subg.F \
            tce_mrcc_q3fnt2_subg.F 

HEADERS = 

include ../../../config/makefile.h
include ../../../config/makelib.h

