
# $Id: GNUmakefile,v 1.3 2002-01-14 21:06:30 bylaska Exp $
#
 OBJ_OPTIMIZE = \
                pspw_LJ.o

	  OBJ = 


      LIBRARY = libpspw.a

    USES_BLAS = pspw_LJ.F
                
  LIB_DEFINES =


include ../../../../config/makefile.h
include ../../../../config/makelib.h

