
# $Id: GNUmakefile,v 1.2 2001-11-11 01:29:09 bylaska Exp $
#
 OBJ_OPTIMIZE = \
                pspw_LJ.o

	  OBJ = 


      LIBRARY = libnwpwlib.a

    USES_BLAS = pspw_LJ.F
                
  LIB_DEFINES =


include ../../../../config/makefile.h
include ../../../../config/makelib.h

