#
# $Id: GNUmakefile,v 1.2 2003-01-30 21:12:33 bylaska Exp $
#

          OBJ =  paw_comp_charge.o
          HEADERS = 


      LIBRARY =	libpaw.a

   USES_BLAS = 

  LIB_INCLUDES =

  LIB_DEFINES = 




include ../../../config/makefile.h
include ../../../config/makelib.h
include ../makefile.h


