#
#	$Id: MakeFile,v 1.5 2000-01-25 19:45:02 mg201 Exp $	
#

OBJ_ENERGY =   $(OBJDIR)\rel_onel.obj \
               $(OBJDIR)\rel_mpole.obj \
               $(OBJDIR)\rel_pot.obj \
               $(OBJDIR)\rel_pot2.obj \
               $(OBJDIR)\rel_2e4c_sf.obj \
               $(OBJDIR)\rel_LLSS.obj \
               $(OBJDIR)\rel_SSLL.obj \
               $(OBJDIR)\rel_SSSS.obj \
               $(OBJDIR)\rel_init_con.obj \
               $(OBJDIR)\rel_oneld.obj \
               $(OBJDIR)\rel_pvp.obj \
               $(OBJDIR)\int_rel_init.obj \
               $(OBJDIR)\dmd_input.obj

!IFDEF NWCHEM_DEBUG
OBJ = $(OBJ_ENERGY)
!ELSE
OBJ_OPTIMIZE = $(OBJ_ENERGY)
!ENDIF

HEADERS =      rel_consts.fh \
               rel_nwc.fh

LIBRARY = nwints.lib

!INCLUDE ..\..\config\NTmakefile.h
!INCLUDE ..\..\config\NTmakelib.h
