# $Id: GNUmakefile,v 1.13 2003-02-20 17:50:26 d3k958 Exp $
  LIBRARY = libetrans.a
  
  OBJ = et_calc.o et_input.o et_det.o et_2e.o et_dgefa.o  \
 et_movecs_read.o et_vectors_inp.o et_fock.o \
 et_dens_prod.o et_omega2_mult.o 
 
 


include ../config/makefile.h
include ../config/makelib.h

