# $Id: GNUmakefile,v 1.6 2002-01-04 18:11:22 d3k958 Exp $
  LIBRARY = libetrans.a
  
  OBJ = et_calc.o et_input.o et_det.o et_2e.o et_dgefa.o  \
 et_movecs_read.o

include ../config/makefile.h
include ../config/makelib.h

