#
# $Id: GNUmakefile,v 1.1 2002-02-27 02:16:00 bylaska Exp $
#
 SUBDIRS = 
 OBJ_OPTIMIZE = \
                switching_charge.o

      OBJ =


      LIBRARY = libpspw.a

    USES_BLAS = 
  LIB_DEFINES =
  LIB_INCLUDES = 

include ../../../../config/makefile.h
include ../../../../config/makelib.h

