#
# $Id$
#
 SUBDIRS = 
 OBJ_OPTIMIZE = \
                switching_charge.o

      OBJ =


      LIBRARY = libpspw.a

    USES_BLAS = 
  LIB_DEFINES =
  LIB_INCLUDES = 

include ../../../../config/makefile.h
include ../../../../config/makelib.h

