#
# $Id$
#
 OBJ_OPTIMIZE = \
				band_sd.o \
				band_cpmd.o \
				band_inner_loop.o \
				band_inner_loop_md.o
                
	  OBJ = 


      LIBRARY = libband.a

    USES_BLAS = band_sd.F band_cpmd.F band_inner_loop.F band_inner_loop_md.F
                

  LIB_DEFINES =


include ../../../config/makefile.h
include ../../../config/makelib.h

