#
# $Id: GNUmakefile,v 1.14 1998-11-23 17:12:10 mdupuis Exp $
#


   OBJ = prop.o wnbofile.o prop_input.o hnd_property.o prp.o giao.o gia2.o gia3.o prp2.o

   LIBRARY = libproperty.a
   LIB_DEFINES = 
   LIB_INCLUDES = -I../include

USES_BLAS = wnbofile.F

include ../config/makefile.h
include ../config/makelib.h


