#
# $Id: GNUmakefile,v 1.19 2003-01-30 01:00:16 bert Exp $
#


   OBJ = prop.o wnbofile.o prop_input.o hnd_property.o prp.o giao.o gia2.o gia3.o prp2.o hnd_util.o dft_hnd.o

   LIBRARY = libproperty.a
   LIB_DEFINES = 
   LIB_INCLUDES = -I../nwdft/include

USES_BLAS = wnbofile.F gia3.F

HEADERS = prop.fh

include ../config/makefile.h
include ../config/makelib.h


