#
# $Id: GNUmakefile,v 1.8 1997-04-02 19:02:10 d3e129 Exp $
#
   OBJ = prop.o wnbofile.o prop_input.o scf_property.o prp.o

   LIBRARY = libproperty.a
   LIB_DEFINES = 
   LIB_INCLUDES = -I../include

USES_BLAS = wnbofile.F

include ../config/makefile.h
include ../config/makelib.h


