#
# $Id$
#
 OBJ_OPTIMIZE = \
				pspw_APC.o \
				pspw_Efield.o 

	  OBJ = 

      LIBRARY = libpspw.a

    USES_BLAS =  pspw_APC.F pspw_Efield.F

  LIB_DEFINES = 


include ../../../../config/makefile.h
include ../../../../config/makelib.h

