#
# $Id: GNUmakefile,v 1.3 2004-03-02 00:09:59 bylaska Exp $
#
 OBJ_OPTIMIZE = \
				pspw_APC.o \
				pspw_Efield.o 

	  OBJ = 

      LIBRARY = libpspw.a

    USES_BLAS =  pspw_APC.F pspw_Efield.o

  LIB_DEFINES = 


include ../../../../config/makefile.h
include ../../../../config/makelib.h

