#$Id: GNUmakefile,v 1.1 2006-12-01 22:41:17 edo Exp $

#   OBJ_OPTIMIZE =  transport.o transp_input.o

   LIBRARY = libtransport.a
 USES_BLAS = transport.F

include ../config/makefile.h
include ../config/makelib.h


