#$Id: GNUmakefile,v 1.2 2006-12-05 13:50:33 edo Exp $

#   OBJ_OPTIMIZE =  transport.o 
   OBJ_OPTIMIZE =   transp_input.o

   LIBRARY = libtransport.a
 USES_BLAS = transport.F

include ../config/makefile.h
include ../config/makelib.h


