# 
# $Id: GNUmakefile,v 1.7 2004-05-14 16:38:41 edo Exp $
#

          OBJ_OPTIMIZE =  paw_proj.o
          HEADERS =  paw_proj.fh


      LIBRARY =	libpaw.a

   USES_BLAS =  paw_proj.F

  LIB_INCLUDES = 

  LIB_DEFINES = 




include ../../../config/makefile.h
include ../../../config/makelib.h
include ../makefile.h


