#
# $Id: GNUmakefile,v 1.3 2002-09-10 23:23:14 marat Exp $
#

#          OBJ = bessel_transform.o \
#		paw_proj.o
          OBJ =  paw_proj.o


      LIBRARY =	libpaw.a

   USES_BLAS = 

  LIB_INCLUDES = -I../include/

  LIB_DEFINES = 




include ../../../config/makefile.h
include ../../../config/makelib.h
include ../makefile.h


