
# $Id: GNUmakefile,v 1.1 2001-11-13 01:37:16 bylaska Exp $
#
 OBJ_OPTIMIZE = \
                fractional.o

	  OBJ = 

      LIBRARY = libnwpwlib.a

    USES_BLAS = fractional.F
                

  LIB_DEFINES =


include ../../../config/makefile.h
include ../../../config/makelib.h

