
# $Id: GNUmakefile,v 1.2 2004-03-04 15:12:21 bylaska Exp $
#
 OBJ_OPTIMIZE = \
                fractional.o \
		frac_occ_input.o \
		frac_occ.o
 HEADERS = frac_occ.fh

	  OBJ = 

      LIBRARY = libnwpwlib.a

    USES_BLAS = fractional.F frac_occ.F
                

  LIB_DEFINES =


include ../../../config/makefile.h
include ../../../config/makelib.h

