#
# $Id: GNUmakefile,v 1.3 2001-08-30 16:58:41 bylaska Exp $
#
# intf and aux break on IBM SP xlhpf with optimization ... why? 
 SUBDIRS = D3dB psi electron ion-psp lattice ke coulomb exchange-correlation control utilities thermostats sic

 OBJ_OPTIMIZE = \
	      	dsum.o \
			matrix.o


	  OBJ = 

      LIBRARY = libpspw.a

    USES_BLAS = matrix.f

  LIB_DEFINES = 


include ../../../config/makefile.h
include ../../../config/makelib.h

