#
# $Id: GNUmakefile,v 1.12 2004-11-05 23:15:01 bylaska Exp $
#
 SUBDIRS = psi electron ke coulomb exchange-correlation thermostats sic hfx ion ewald psp Grsm_list aorbs truncating_function

include ../../../config/makefile.h
include ../../../config/makelib.h

