
# $Id$
#
 OBJ_OPTIMIZE = \
		paw_sd.o \
		paw_cpmd.o \
		paw_inner_loop.o \
		paw_inner_loop_md.o \
		psi_marat_write.o paw_output.o



	  OBJ = 



      LIBRARY = libpaw.a

    USES_BLAS = paw_sd.F paw_inner_loop.F paw_cpmd.F paw_inner_loop_md.F
                

  LIB_DEFINES =


include ../../../config/makefile.h
include ../../../config/makelib.h
include ../makefile.h
