
# $Id: GNUmakefile,v 1.2 2002-08-07 19:16:35 marat Exp $
#
 OBJ_OPTIMIZE = \
		paw_sd.o



	  OBJ = 



      LIBRARY = libpaw.a

    USES_BLAS = paw_sd.F 
                

  LIB_DEFINES =


include ../../../config/makefile.h
include ../../../config/makelib.h
include ../makefile.h
