
# $Id: GNUmakefile,v 1.3 2002-08-16 01:13:05 bylaska Exp $
#
 OBJ_OPTIMIZE = \
		paw_sd.o \
		psi_marat_write.o



	  OBJ = 



      LIBRARY = libpaw.a

    USES_BLAS = paw_sd.F 
                

  LIB_DEFINES =


include ../../../config/makefile.h
include ../../../config/makelib.h
include ../makefile.h
