#
# $Id: GNUmakefile,v 1.1 2007-06-21 02:08:15 bylaska Exp $
#

 OBJ_OPTIMIZE = \
            chi_H.o \
            chi_Hv4.o



	  OBJ = 

      LIBRARY = libofpw.a

    USES_BLAS = psi_H.F psi_Hv4.F

  LIB_DEFINES = 


include ../../../../config/makefile.h
include ../../../../config/makelib.h

