#
# $Id: GNUmakefile,v 1.2 2001-09-29 00:28:07 bylaska Exp $
#
# intf and aux break on IBM SP xlhpf with optimization ... why? 

 OBJ_OPTIMIZE = \
			v_exc.o \
            v_bwexc.o \
            pbe96.o

#            vdirac.o \

	  OBJ = 

      LIBRARY = libpspw.a

    USES_BLAS = 

  LIB_DEFINES = 


include ../../../../config/makefile.h
include ../../../../config/makelib.h

