#
# $Id$
#

 OBJ_OPTIMIZE = \
		v_exc.o \
            	v_bwexc.o \
            	v_bwexc_euv.o \
            	pbe96.o \
            	pbesol.o \
            	revpbe.o \
            	blyp.o \
		bnl2007_x.o\
		hsepbe.o

#            vdirac.o \

	  OBJ = 

      LIBRARY = libpspw.a

    USES_BLAS = v_bwexc_euv.F v_bwexc.F


  LIB_DEFINES = 


include ../../../../config/makefile.h
include ../../../../config/makelib.h

