#
# $Id: GNUmakefile,v 1.4 2005-02-09 02:19:35 bylaska Exp $
#

 OBJ_OPTIMIZE = \
		v_exc.o \
            	v_bwexc.o \
            	v_bwexc_euv.o \
            	pbe96.o \
            	blyp.o

#            vdirac.o \

	  OBJ = 

      LIBRARY = libpspw.a

    USES_BLAS = 

  LIB_DEFINES = 


include ../../../../config/makefile.h
include ../../../../config/makelib.h

