#
# $Id: GNUmakefile,v 1.1 2001-11-19 17:54:01 bylaska Exp $
#
 OBJ_OPTIMIZE = \
				band_minimizer.o
                


	  OBJ = 



      LIBRARY = libband.a

    USES_BLAS = band_minimizer.F
                

  LIB_DEFINES =


include ../../../config/makefile.h
include ../../../config/makelib.h

