#
# $Id: GNUmakefile,v 1.6 2004-11-29 16:05:17 bylaska Exp $
#
 OBJ_OPTIMIZE = \
				band_minimizer.o \
				c_cgsd_energy.o \
				c_cgsd_noit_energy.o \
				c_cgsd_energy_gradient.o \
				c_cgsd_energy_stress.o \
				c_cgminimize.o \
				c_bfgsminimize.o \
				c_bybminimize.o \
				c_sdminimize.o \
				c_nominimize.o
                
	  OBJ = 



      LIBRARY = libband.a

    USES_BLAS = band_minimizer.F c_cgsd_energy.F c_cgsd_energy_gradient.F
                

  LIB_DEFINES =


include ../../../config/makefile.h
include ../../../config/makelib.h

