#
# $Id: GNUmakefile,v 1.8 2006-06-05 18:03:48 edo Exp $
#
 OBJ_OPTIMIZE = \
				band_minimizer.o \
				c_cgsd_energy.o \
				c_cgsd_noit_energy.o \
				c_cgsd_energy_gradient.o \
				c_cgsd_energy_stress.o \
				c_cgminimize.o \
				c_bfgsminimize.o \
				c_bybminimize.o \
				c_sdminimize.o \
				c_nominimize.o
                
	  OBJ = 



      LIBRARY = libband.a

    USES_BLAS = band_minimizer.F c_cgsd_energy.F c_cgsd_energy_gradient.F c_bybminimize.F c_cgsd_energy_stress.F
                

  LIB_DEFINES =


include ../../../config/makefile.h
include ../../../config/makelib.h

