#
# $Id: GNUmakefile,v 1.5 2003-03-10 05:43:27 marat Exp $
#

          OBJ = paw_ovlp.o paw_overlap_matrix.o


      LIBRARY =	libpaw.a

   USES_BLAS = paw_overlap_matrix.F

  LIB_INCLUDES = 

  LIB_DEFINES = 
  HEADERS = paw_ovlp_data.fh paw_ovlp.fh




include ../../../config/makefile.h
include ../../../config/makelib.h
include ../makefile.h


