#
# $Id: GNUmakefile,v 1.4 2003-02-10 22:34:06 bylaska Exp $
#

          OBJ = paw_ovlp.o paw_overlap_matrix.o


      LIBRARY =	libpaw.a

   USES_BLAS = paw_overlap_matrix.F

  LIB_INCLUDES = 

  LIB_DEFINES = 
  HEADERS = paw_ovlp_data.fh 




include ../../../config/makefile.h
include ../../../config/makelib.h
include ../makefile.h


