#
# $Id$
#

 OBJ_OPTIMIZE = \
            truncating_function.o



	  OBJ = 

      LIBRARY = libpspw.a

    USES_BLAS = truncating_function.F

  LIB_DEFINES = 


include ../../../../config/makefile.h
include ../../../../config/makelib.h

