#
# $Id: GNUmakefile,v 1.1 2002-01-14 21:06:28 bylaska Exp $
#
 SUBDIRS =

 OBJ_OPTIMIZE = \
            ewald.o


	  OBJ = 

      LIBRARY = libpspw.a

    USES_BLAS = ewald.F

  LIB_DEFINES = 


include ../../../../config/makefile.h
include ../../../../config/makelib.h

