#
# $Id$
#
 SUBDIRS =

 OBJ_OPTIMIZE = \
            ewald.o


	  OBJ = 

      LIBRARY = libpspw.a

    USES_BLAS = ewald.F

  LIB_DEFINES = 


include ../../../../config/makefile.h
include ../../../../config/makelib.h

