#
# $Id$
#

 OBJ_OPTIMIZE = \
            brillioun.o



	  OBJ = 

      LIBRARY = libband.a

    USES_BLAS = 

  LIB_DEFINES = 


include ../../../../config/makefile.h
include ../../../../config/makelib.h

