#
# $Id: GNUmakefile,v 1.1 2001-12-13 03:49:51 bylaska Exp $
#

 OBJ_OPTIMIZE = \
            brillioun.o



	  OBJ = 

      LIBRARY = libband.a

    USES_BLAS = 

  LIB_DEFINES = 


include ../../../../config/makefile.h
include ../../../../config/makelib.h

