#
# $Id$
#

 OBJ_OPTIMIZE = ofpwsd.o \
		inner_loop_ofpw.o \
		chi_lmbda.o

	  OBJ = 


      LIBRARY = libofpw.a

    USES_BLAS = ofpwsd.F inner_loop_ofpw.F chi_lmbda.f

  LIB_DEFINES =


include ../../../config/makefile.h
include ../../../config/makelib.h

