
# $Id$
#
 OBJ_OPTIMIZE = \
                ofpwsd.o \
		inner_loop_ofpw.o

	  OBJ = 


      LIBRARY = libofpw.a

    USES_BLAS = ofpwsd.F inner_loop_ofpw.F

  LIB_DEFINES =


include ../../../config/makefile.h
include ../../../config/makelib.h

