#
#	$id: MakeFile,v 1.5 2000/08/08 23:38:58 bjohnson Exp $
#

!INCLUDE config\nwchem_config_win32.h
!INCLUDE config\NTmakefile.h

SUBDIRS = $(NW_CORE_SUBDIRS) $(NW_MODULE_SUBDIRS)

all: pre_build
	@nmake -nologo foreach_subdir
	nmake -nologo link

build:
	@nmake -nologo foreach_subdir
	nmake -nologo link

OBJ =          $(OBJDIR)\nwchem.obj \
               $(OBJDIR)\stubs_win32.obj

COMPILATION_DATE = (unknown)
CODE_BRANCH = (unknown)
!IFDEF PYTHONHOME
WITHPYTHON = -DWITHPYTHON
!ENDIF
LIB_DEFINES = -DCOMPILATION_DATE="'$(COMPILATION_DATE)'" \
              -DCOMPILATION_DIR="'$(TOPDIR)'" \
              -DNWCHEM_BRANCH="'$(CODE_BRANCH)'" $(WITHPYTHON)


WIN32_EXE_NAME = nw32
WIN32_EXE = $(BINDIR)\$(WIN32_EXE_NAME).exe

realclean: clean
	@if exist "$(LIBDIR)\*" erase /q "$(LIBDIR)\*"
	@if exist "$(LIBDIR)" rmdir "$(LIBDIR)"
	@if exist "$(WIN32_EXE)" erase /q "$(WIN32_EXE)"
	@if exist "$(BINDIR)" rmdir "$(BINDIR)"
	@nmake -nologo LVL=src clean_MakeFiles
	@nmake -nologo TARGET_DIR=tools SUBDIR_TARGET=clean subdir_target
	@nmake -nologo TARGET_DIR=config\win32 SUBDIR_TARGET=clean subdir_target

!INCLUDE config\NTmakelib.h

pre_build:
	@nmake -nologo TARGET_DIR=config\win32 subdir_target
	@nmake -nologo MakeFiles VS_wrappers VS_projects
	@nmake -nologo SUBDIR_TARGET=WIN32.stamp foreach_subdir
	-@nmake -nologo TARGET_DIR=tools subdir_target

link: $(BINDIR) $(OBJDIR) $(OBJ)
	$(FC) /Fe"$(WIN32_EXE)" $(OBJ) /link /stack:20000000 \
	/debug:full /debugtype:cv /pdb:none /libpath:"$(LIB_DISTRIB)" \
	/libpath:"$(SRCDIR)\tools\lib\win32" /libpath:"$(MPI_LIB)" \
        $(LIBS) $(PYTHON_SYSLIB)

	@echo $(WIN32_EXE) is built

VS_wrappers:
	@nmake -nologo TEMPLATE=$(CNFDIR)\win32\wrap.dsp \
	SUBDIR_TARGET=VS_project foreach_subdir

VS_projects:
	@nmake -nologo TEMPLATE=$(CNFDIR)\win32\lib.dsp \
	SUBDIR_TARGET=VS_project foreach_subdir

#
# For convenience
#
$(WIN32_EXE_NAME).pg:
	echo local 0 > $(WIN32_EXE_NAME).pg
