#
#	$Id: MakeFile,v 1.2 1999-11-17 18:31:30 bjohnson Exp $
#

!INCLUDE config\nwchem_config_win32.h
!INCLUDE config\NTmakefile.h

SUBDIRS = $(NW_CORE_SUBDIRS) $(NW_MODULE_SUBDIRS)

all: config\file_exists.exe
	@nmake -nologo TARGET_DIR=tools subdir_target
	@nmake -nologo SUBDIR_TARGET=WIN32.stamp foreach_subdir
	@nmake -nologo foreach_subdir
	nmake -nologo link

config\file_exists.exe: config\file_exists.cpp
	cl -nologo /GX /Fe"config\file_exists.exe" config\file_exists.cpp
	@erase file_exists.obj

OBJ =          $(OBJDIR)\nwchem.obj \
               $(OBJDIR)\stubs_win32.obj

COMPILATION_DATE = (unknown)
CODE_BRANCH = (unknown)
LIB_DEFINES = -DCOMPILATION_DATE="'$(COMPILATION_DATE)'" \
              -DCOMPILATION_DIR="'$(TOPDIR)'" \
              -DNWCHEM_BRANCH="'$(CODE_BRANCH)'"

realclean: clean
	@nmake -nologo SUBDIR_TARGET=realclean foreach_subdir

!INCLUDE config\NTmakelib.h

link: $(OBJDIR) $(OBJ)
	$(FC) /Fenw32.exe $(OBJ) /link /debug:full /debugtype:cv /pdb:none /libpath:"..\lib\win32" \
	/libpath:".\tools\lib\win32" /libpath:"$(MPI_LIB)" $(LIBS)
	@echo nw32.exe is built

!IF 0
	@if exist WIN32.stamp erase WIN32.stamp
	@if exist "*.i" erase "*.i"
#	@if exist "*.exe" erase "*.exe"
#	@if exist "*.ilk" erase "*.ilk"
#	@if exist "*.pdb" erase "*.pdb"
	@if exist $(LIBRARY_PATH) erase $(LIBRARY_PATH)
	@if exist "$(OBJDIR)\*" erase /q "$(OBJDIR)\*"
	@if exist "$(OBJDIR)" rmdir "$(OBJDIR)"
!ENDIF
