#
# $Id: GNUmakefile,v 1.1 2001-10-21 14:42:38 bylaska Exp $
#
 SUBDIRS = 
 OBJ_OPTIMIZE = \
                pspw_qmmm.o

      OBJ =


      LIBRARY = libpspw.a

    USES_BLAS = 
  LIB_DEFINES =
  LIB_INCLUDES = 

include ../../../config/makefile.h
include ../../../config/makelib.h

