#
# $Id: GNUmakefile,v 1.8 2007-03-27 02:02:50 bylaska Exp $
#
 SUBDIRS = pspw_LJ pspw_Q 
 OBJ_OPTIMIZE = \
                pspw_qmmm_input.o \
                pspw_qmmm.o

      OBJ =


      LIBRARY = libpspw.a

    USES_BLAS = pspw_qmmm.F
  LIB_DEFINES =
  LIB_INCLUDES = 

include ../../../config/makefile.h
include ../../../config/makelib.h

