#
# $Id: GNUmakefile,v 1.7 2002-02-27 19:05:22 bylaska Exp $
#
 SUBDIRS = pspw_LJ pspw_Q model_potential switching_charge
 OBJ_OPTIMIZE = \
                pspw_qmmm_input.o \
                pspw_qmmm.o

      OBJ =


      LIBRARY = libpspw.a

    USES_BLAS = pspw_qmmm.F
  LIB_DEFINES =
  LIB_INCLUDES = 

include ../../../config/makefile.h
include ../../../config/makelib.h

