#
# $Id$
#

 OBJ_OPTIMIZE = \
		band_Grsm_list.o \
		band_lmbfgs.o 



	  OBJ = 

      LIBRARY = libband.a

    USES_BLAS = band_Grsm_list.F band_lmbfgs.F

  LIB_DEFINES = 


include ../../../../config/makefile.h
include ../../../../config/makelib.h

