#
# $Id: GNUmakefile,v 1.1 2003-03-31 23:16:56 windus Exp $
#

  LIBRARY = libgeninterface.a
  
  OBJ = geninterface.o

  HEADERS = geninterface.fh

include ../config/makefile.h
include ../config/makelib.h

