#
# $Id: GNUmakefile,v 1.2 2003-09-19 14:15:32 windus Exp $
#

  LIBRARY = libgeninterface.a
  
  OBJ = geninterface.o NWChemWrap.o

  HEADERS = geninterface.fh

include ../config/makefile.h
include ../config/makelib.h

