
# $Id$
#
 OBJ_OPTIMIZE = \
                pspw_Three.o

	  OBJ = 


      LIBRARY = libpspw.a

    USES_BLAS = pspw_Three.F
                
  LIB_DEFINES =


include ../../../../config/makefile.h
include ../../../../config/makelib.h

