#
# $Id: GNUmakefile,v 1.2 2001-08-30 17:00:13 bylaska Exp $
#
# intf and aux break on IBM SP xlhpf with optimization ... why? 

 OBJ_OPTIMIZE = \
            Parallel.o


	  OBJ = 

      LIBRARY = libpspw.a

    USES_BLAS = 

  LIB_DEFINES = 


include ../../../config/makefile.h
include ../../../config/makelib.h

