#
# $Id: GNUmakefile,v 1.4 2006-03-16 18:38:28 bylaska Exp $
#


 OBJ_OPTIMIZE = \
            Parallel.o


	  OBJ = 

      LIBRARY = libnwpwlib.a

    USES_BLAS = 

  LIB_DEFINES = 


include ../../../config/makefile.h
include ../../../config/makelib.h

