#
# $Id$
#
 OBJ_OPTIMIZE = \
				band_dplot_input.o \
				band_dplot.o \
				band_dplot_iteration.o 


	  OBJ = 

      LIBRARY = libband.a

    USES_BLAS = band_dplot.F

  LIB_DEFINES = 


include ../../../config/makefile.h
include ../../../config/makelib.h

