#
# $Id: GNUmakefile,v 1.1 2005-08-05 20:39:35 bylaska Exp $
#
 OBJ_OPTIMIZE = \
				band_dplot_input.o \
				band_dplot.o 


	  OBJ = 

      LIBRARY = libband.a

    USES_BLAS = band_dplot.F

  LIB_DEFINES = 


include ../../../config/makefile.h
include ../../../config/makelib.h

