#$Id$
# makefile,v 1.8 1994/12/05 20:37:08 og845 Exp

OBJ =

LIBRARY = liboptim.a

LIB_DEFINES =

SUBDIRS = deloc mepgs tropt neb string
LIB_INCLUDES =

include ../config/makefile.h
include ../config/makelib.h
