#
# $Id: GNUmakefile,v 1.1 2007-06-19 23:32:00 bylaska Exp $
#
 OBJ_OPTIMIZE = \
		ofpw_minimizer.o \
		ofpw_cgsd_energy.o \
		ofpw_cgminimize.o
                
	  OBJ = 

      LIBRARY = libofpw.a

    USES_BLAS = ofpw_minimizer.F ofpw_cgsd_energy.F ofpw_cgminimize.F

  LIB_DEFINES =
  LIB_INCLUDES = -I../../nwpwlib/include




include ../../../config/makefile.h
include ../../../config/makelib.h

