
# $Id$
#
 OBJ_OPTIMIZE = \
                mmq.o

	  OBJ = 


      LIBRARY = libpspw.a

    USES_BLAS = mmq.F
                
  LIB_DEFINES =


include ../../../../config/makefile.h
include ../../../../config/makelib.h

