#$Id: GNUmakefile,v 1.3 2008-07-17 22:53:00 marat Exp $
   OBJ_OPTIMIZE = leps_energy.o leps_gradient.o

   OBJ = leps_energy.o leps_gradient.o md_driver.o

   LIBRARY = libleps.a

include ../config/makefile.h
include ../config/makelib.h


