#$Id: GNUmakefile,v 1.4 2008-07-22 23:47:49 bojana Exp $
   OBJ_OPTIMIZE = leps_energy.o leps_gradient.o

   OBJ = leps_energy.o leps_gradient.o md_driver.o md_data.o

   LIBRARY = libleps.a

include ../config/makefile.h
include ../config/makelib.h


