#$Id: GNUmakefile,v 1.7 2009-01-19 18:05:03 bojana Exp $
   OBJ_OPTIMIZE = leps_energy.o leps_gradient.o mc_driver.o mymc_input.o mc_data.o

   OBJ = leps_energy.o leps_gradient.o md_driver.o md_data.o mymd_input.o mc_driver.o mymc_input.o mc_data.o gasdev.o md_init.o crossing.o mc_main.o md_set.o mc_init.o  urand.o
   LIBRARY = libleps.a

include ../config/makefile.h
include ../config/makelib.h


