#
# $Id$
#

          OBJ = task_smd.o smd_input.o smd_rdinp.o\
                smd_coordfile.o smd_pdb.o \
                smd_rtdb_data.o smd_init.o smd_end.o \
                smd_atom.o task_smd_energy.o smd_srtdb.o \
                task_smd_dynamics.o smd_util.o smd_data.o \
                smd_message.o smd_param.o \
                smd_paramfile.o
#                smd_param.o \
#                smd_atom.o smd_pot.o \
#                smd_res.o smd_data.o smd_paramfile.o \
#                task_smd_energy.o smd_rdinp.o smd_lat.o \
#                smd_type.o smd_vel.o smd_force.o \
#                smd_charge.o smd_coords.o smd_exlist.o \
#                smd_system.o smd_ewald_data.o smd_ewald.o \
#                smd_ewald_generic.o smd_cutoff_data.o \
#                smd_vlist.o smd_pot_generic.o smd_energy.o \
#                smd_shake.o smd_bond.o smd_shakelist.o \
#                smd_bondlist.o smd_coulomb.o smd_rtdb_data.o \
#                smd_coordfile.o smd_system_data.o \
#                smd_temper_data.o smd_mass.o smd_leapf.o \
#                smd_leapf_shake.o smd_geom.o 

      LIBRARY = libsmd.a

        SMD_DEBUG = 1

ifdef SMD_DEBUG
     LIB_DEFINES = -DSMD_DEBUG
endif




include ../../config/makefile.h
include ../../config/makelib.h









