#
# $Id: GNUmakefile,v 1.3 2004-05-14 16:13:37 edo Exp $
#

          OBJ_OPTIMIZE =  paw_nonlocal.o 
          HEADERS = 


      LIBRARY =	libpaw.a

   USES_BLAS =  paw_nonlocal.F

  LIB_INCLUDES =

  LIB_DEFINES = 




include ../../../config/makefile.h
include ../../../config/makelib.h


