#
# $Id: GNUmakefile,v 1.2 2004-03-04 15:12:23 bylaska Exp $
#

          OBJ_OPTIMIZE =  paw_nonlocal.o 
          HEADERS = 


      LIBRARY =	libpaw.a

   USES_BLAS = 

  LIB_INCLUDES =

  LIB_DEFINES = 




include ../../../config/makefile.h
include ../../../config/makelib.h


