#
# $Id: GNUmakefile,v 1.1 2007-06-21 02:08:13 bylaska Exp $
#

 OBJ_OPTIMIZE = \
		chi_read.o \
		chi_write.o \
		chi_new.o \
		chi_expander.o

      LIBRARY = libofpw.a

    USES_BLAS = 

  LIB_DEFINES = 


include ../../../../config/makefile.h
include ../../../../config/makelib.h


