

all:	; texi2pdf peigs.texi

.EXPORT_ALL_VARIABLES:

.PHONY :	clean

clean:		
		-rm -f peigs.dvi
		-rm -f peigs.aux
		-rm -f peigs.cp
		-rm -f peigs.cps
		-rm -f peigs.fn
		-rm -f peigs.ky
		-rm -f peigs.log
		-rm -f peigs.pg
		-rm -f peigs.toc
		-rm -f peigs.tp
		-rm -f peigs.vr
		-rm -f dvips-out.ps


