#
# $Id$
#

 OBJ_OPTIMIZE = \
		paw_atom_driver.o \
		paw_atom.o \
		paw_basis.o \
		paw_scattering.o \
		paw_schrodin.o \
		paw_pauli.o \
		paw_orbitals.o \
		paw_kinetic_energy.o \
		paw_potential.o \
		paw_dirac_exchange.o \
		paw_vosko.o \
		paw_hartree.o \
		paw_core.o \
		paw_comp_charge.o \
		paw_ion.o \
		paw_matrix_elements.o \
		paw_pred_cor.o \
		paw_loggrid.o \
		paw_bisect.o \
		paw_error_function.o \
		paw_get_inverse.o \
		paw_my_constants.o \
		paw_utilities.o \
		paw_output.o \
		paw_sdir.o \
		paw_my_memory.o
       

	  OBJ = 

      LIBRARY = libnwpwlib.a

    USES_BLAS = 

  LIB_DEFINES = 


include ../../../../config/makefile.h
include ../../../../config/makelib.h

