#
# $Id$
#

          OBJ_OPTIMIZE = paw_force.o


      LIBRARY =	libpaw.a

   USES_BLAS = paw_force.F

  LIB_INCLUDES = 

  LIB_DEFINES = 
  HEADERS = paw_force_data.fh 




include ../../../config/makefile.h
include ../../../config/makelib.h


