#
# $Id: GNUmakefile,v 1.1 2003-03-10 05:45:24 marat Exp $
#

          OBJ = paw_force.o


      LIBRARY =	libpaw.a

   USES_BLAS = 

  LIB_INCLUDES = 

  LIB_DEFINES = 
  HEADERS = paw_force_data.fh 




include ../../../config/makefile.h
include ../../../config/makelib.h


