#
# $Id: GNUmakefile 21430 2011-11-07 21:59:54Z d3p852 $
#

  OBJ_OPTIMIZE = dgemm_omp.o \
		 dgamm_omp.o \
		 daxpy_omp.o \
		 dscal_omp.o \
		 ffm_multiply_omp_group.o \
		 zgemm_omp.o \
		 ffw_multiply_omp_group.o 
  OBJ = 



      LIBRARY = libnwpwlib.a

    USES_BLAS = dgemm_omp.F ffm_multiply_omp_group.F zgemm_omp.F ffw_multiply_omp_group.F

  LIB_DEFINES = 


include ../../../config/makefile.h
include ../../../config/makelib.h





