#
# $Id: GNUmakefile 21430 2011-11-07 21:59:54Z d3p852 $
#

  OBJ_OPTIMIZE = dgemm_omp.o \
		 daxpy_omp.o
  OBJ = 



      LIBRARY = libnwpwlib.a

    USES_BLAS = 

  LIB_DEFINES = 


include ../../../config/makefile.h
include ../../../config/makelib.h





