#
# $Id$
#
     SUBDIRS =


 OBJ_OPTIMIZE = \
		band_APC.o 


      LIBRARY = libband.a

    USES_BLAS =  band_APC.F


  LIB_DEFINES = 


include ../../../../config/makefile.h
include ../../../../config/makelib.h

