# $Id: GNUmakefile,v 1.3 1998-10-05 21:02:43 windus Exp $

include ../../config/makefile.h

  OBJ_OPTIMIZE = hnd_whermt.o \
                 hnd_rt123.o  \
                 hnd_root4.o  \
                 hnd_root5.o  \
                 hnd_droot.o

       HEADERS = hnd_whermt.fh \
                 hnd_rys.fh \
                 hnd_tol.fh

       LIBRARY = libnwints.a

include ../../config/makelib.h

