# $Id: GNUmakefile,v 1.1 1998-10-01 18:50:44 windus Exp $

include ../../config/makefile.h

  OBJ_OPTIMIZE = hnd_whermt.o \
                 hnd_rt123.o  \
                 hnd_root4.o  \
                 hnd_root5.o

       HEADERS = hnd_whermt.fh \
                 hnd_rys.fh

       LIBRARY = libnwints.a

include ../../config/makelib.h

