#
# $Id: GNUmakefile,v 1.2 2001-12-15 03:11:01 bylaska Exp $
#

 OBJ_OPTIMIZE = \
			c_electron.o \
            cpsi_H.o 



	  OBJ = 

      LIBRARY = libband.a

    USES_BLAS = c_electron.F

  LIB_DEFINES = 


include ../../../../config/makefile.h
include ../../../../config/makelib.h

