#
# $Id: GNUmakefile,v 1.1 2001-12-14 20:02:43 bylaska Exp $
#

 OBJ_OPTIMIZE = \
            cpsi_H.o 



	  OBJ = 

      LIBRARY = libband.a

    USES_BLAS = 

  LIB_DEFINES = 


include ../../../../config/makefile.h
include ../../../../config/makelib.h

