#
# $Id$
#

 OBJ_OPTIMIZE = \
		nwpw_gaunt.o \
		nwpw_compcharge.o\
		nwpw_xc.o\
		nwpw_vosko.o\
		nwpw_gga.o\
		nwpw_hartree.o\
		nwpw_SpecialKummer.o \
		nwpw_GausBessel.o \
		nwpw_WGaussian.o

	  OBJ = 

      LIBRARY = libnwpwlib.a

    USES_BLAS = nwpw_gaunt.F nwpw_compcharge.F nwpw_xc.F nwpw_hartree.F

  LIB_DEFINES = 


include ../../../../config/makefile.h
include ../../../../config/makelib.h

