#
# $Id: GNUmakefile 21267 2011-10-21 15:26:14Z bylaska $
#

 OBJ_OPTIMIZE = \
		nwpw_gaunt.o \
		nwpw_compcharge.o\
		nwpw_hypergeom1F1.o

	  OBJ = 

      LIBRARY = libnwpwlib.a

    USES_BLAS = nwpw_gaunt.F nwpw_compcharge.F

  LIB_DEFINES = 


include ../../../../config/makefile.h
include ../../../../config/makelib.h

