#
# $Id$
#

 OBJ_OPTIMIZE = \
		nwpw_gaunt.o \
		nwpw_compcharge.o\
		nwpw_gintegrals3.o \
		nwpw_xc.o\
		nwpw_vosko.o\
		nwpw_gga.o\
		nwpw_SpecialKummer.o \
		nwpw_GaussBessel.o \
		nwpw_WGaussian.o \
		nwpw_gauss_weights.o 

	  OBJ = 

      LIBRARY = libnwpwlib.a

    USES_BLAS = nwpw_gaunt.F nwpw_compcharge.F nwpw_xc.F nwpw_gintegrals.F nwpw_gintegrals2.F nwpw_gintegrals3.F

  LIB_DEFINES = 


include ../../../../config/makefile.h
include ../../../../config/makelib.h

