name: nwchem_docker

on:
  release:
  schedule:
    - cron: '0 2 * * *'
  repository_dispatch:
    types: [backend_automation]
  workflow_dispatch:

jobs:
  reuse-docker-cross:
    uses: nwchemgit/nwchem-dockerfiles/.github/workflows/cross_compile.yml@master
