# $Id: GNUmakefile,v 1.7 1995-06-27 21:01:05 d3e129 Exp $

      OBJ_OPTIMIZE = hf1d.o      hf2d.o     hfd2oi.o \
                     hfderi.o    hfdkei.o   hfdnai.o \
                     hfefi.o     hf2d_2a.o  hf2d_2b.o \
                     hf2d_2a2b.o hf2d_3a.o  hf2d_3a2b.o \
                     hf1PRtoAB.o hf2PRtoAB.o hf2QStoCD.o 

     LIBRARY = libnwints.a

   USES_BLAS = hf1d.F hf2d.F hf2d_2a.F hf2d_2b.F hf2d_2a2b.F hf2d_3a.F hf2d_3a2b.F

include ../../config/makefile.h
include ../../config/makelib.h

