#
# $Id: GNUmakefile,v 1.1 2006-11-29 02:35:04 d3p708 Exp $
#

 OBJ_OPTIMIZE = Pneb.o
 OBJ = 



      LIBRARY = libnwpwlib.a

    USES_BLAS = Pneb.F

  LIB_DEFINES = 

include ../../../config/makefile.h
include ../../../config/makelib.h







