#!/bin/csh
#
# $Id: doqmtests,v 1.42 2004-05-03 18:46:39 sohirata Exp $
#
#---   small tests
./runtests.unix auh2o autosym dft_he2+ h2mp2 h2o hess_h2o prop_h2o pyqa
./runtests.unix rimp2_ne  scf_feco5 small_intchk tagcheck testtab
./runtests.unix h2o_dk u_sodft cosmo_h2o ch5n_nbo h2s_finite startag
./runtests.unix cosmo_trichloroethene esp esp_uhf dft_bsse
./runtests.unix dplot neda_nbo  dft_meta
./runtests.unix et_zn_dimer vectors_rotate sad_ch3hf

#---   small tests that should fail!
echo ' '
echo 'The oh2 test is testing the perl parsing script and SHOULD fail'
./runtests.unix oh2
#---   medium tests
./runtests.unix dft_feco5 
./runtests.unix dft_siosi3
./runtests.unix dft_x
./runtests.unix dft_mpw1k dft_li2freq
echo 'The intermediate values for this test may cause some differences.'
echo 'Please check the final values for the last optimized structure.'
./runtests.unix dielsalder
echo 'The intermediate energy values for the numerical gradient '
echo 'test may cause some differences.'
echo 'Please check the final gradient values for correctness.'
./runtests.unix grad_ozone
./runtests.unix dft_ozone 
./runtests.unix hess_c6h6
./runtests.unix intchk
echo 'The intermediate values for this test may cause some differences.'
echo 'Please check the final values for the last optimized structure.'
./runtests.unix sadsmall
#./runtests.unix sadbig
./runtests.unix br2_dk
./runtests.unix uo2_sodft
./runtests.unix uo2_sodft_grad
./runtests.unix si2cl6_gc
./runtests.unix pspw
./runtests.unix pspw_SiC
./runtests.unix pspw_md
./runtests.unix paw
./runtests.unix pspw_polarizability
./runtests.unix band
./runtests.unix tddft_h2o
./runtests.unix tddft_n2+
./runtests.unix tddft_ac_co
./runtests.unix tce_h2o
./runtests.unix tce_h2o_dipole
./runtests.unix tce_h2o_eomcc
./runtests.unix tce_uhf_uccsd
./runtests.unix tce_rohf_uccsd
./runtests.unix oniom1
./runtests.unix c60_ecp
#---   long  may not run on workstations
./runtests.unix aump2 
./runtests.unix n2_ccsd 
./runtests.unix uoverlap
./runtests.unix grad_nh3_trimer 
./runtests.unix hess_nh3
./runtests.unix hess_nh3_dimer
./runtests.unix mp2_si2h6
./runtests.unix pbo_nesc1e
./runtests.unix bf_cis
./runtests.unix oniom3
./runtests.unix cytosine_ccsd
./runtests.unix h2o_selci
