#!/bin/csh
#
# $Id: doqmtests,v 1.19 2002-02-08 23:47:35 windus Exp $
#
#---   small tests
runtests.unix auh2o autosym dft_he2+ h2mp2 h2o hess_h2o prop_h2o pyqa
runtests.unix rimp2_ne sadsmall scf_feco5 small_intchk tagcheck testtab
runtests.unix h2o_dk u_sodft cosmo_h2o ch5n_nbo h2s_finite startag
runtests.unix cosmo_trichloroethene
runtests.unix dplot neda_nbo

#---   small tests that should fail!
echo ' '
echo 'The oh2 test is testing the perl parsing script and SHOULD fail'
runtests.unix oh2
#---   medium tests
runtests.unix dft_feco5 
runtests.unix dft_ozone 
runtests.unix dft_siosi3
echo 'The intermediate values for this test may cause some differences.'
echo 'Please check the final values for the last optimized structure.'
runtests.unix dielsalder
echo 'The intermediate energy values for the numerical gradient '
echo 'test may cause some differences.'
echo 'Please check the final gradient values for correctness.'
runtests.unix grad_ozone
runtests.unix hess_c6h6
runtests.unix intchk
echo 'The intermediate values for this test may cause some differences.'
echo 'Please check the final values for the last optimized structure.'
runtests.unix sadbig
runtests.unix br2_dk
runtests.unix uo2_sodft
runtests.unix uo2_sodft_grad
runtests.unix si2cl6_gc
runtests.unix pspw
runtests.unix pspw_SiC
runtests.unix pspw_md
runtests.unix pspw_polarizability
#---   long  may not run on workstations
runtests.unix aump2 
runtests.unix uoverlap
runtests.unix grad_nh3_trimer 
runtests.unix hess_nh3
runtests.unix hess_nh3_dimer
runtests.unix mp2_si2h6
runtests.unix pbo_nesc1e
