#!/bin/bash
#
# $Id$
#
if [ -z "$1" ]; then
    let np=1
else
  let np=$1
fi
./runtests.mpi.unix procs $np tce_h2o
./runtests.mpi.unix procs $np tce_ccsd_t_h2o
./runtests.mpi.unix procs $np tce_uhf_uccsd
./runtests.mpi.unix procs $np tce_ozone_2eorb
./runtests.mpi.unix procs $np tce_h2o_dipole
./runtests.mpi.unix procs $np tce_h2o_eomcc
exit
./runtests.mpi.unix procs $np tce_polar_ccsd_small
./runtests.mpi.unix procs $np tce_hyperpolar_ccsd_small
./runtests.mpi.unix procs $np tce_rohf_uccsd
./runtests.mpi.unix procs $np tce_active_ccsdt
./runtests.mpi.unix procs $np tce_lr_ccsd_t
./runtests.mpi.unix procs $np tce_lr_ccsd_tq
./runtests.mpi.unix procs $np tce_eomsd_eomsol1
./runtests.mpi.unix procs $np tce_eomsd_eomsol2
./runtests.mpi.unix procs $np tce_cr_eom_t_ch_rohf
./runtests.mpi.unix procs $np tce_cr_eom_t_ozone
./runtests.mpi.unix procs $np tce_uracil_creomact

