#
# $Id: GNUmakefile,v 1.31 2009-03-30 14:16:05 bylaska Exp $
#

 OBJ_OPTIMIZE = \
		metadynamics_input.o \
		metadynamics.o

	  OBJ = 

      LIBRARY = libnwpwlib.a

    USES_BLAS = 

  LIB_DEFINES = 


include ../../../config/makefile.h
include ../../../config/makelib.h

