#
# $Id: GNUmakefile,v 1.1 2001-11-11 01:27:53 bylaska Exp $
#

 OBJ_OPTIMIZE = \
            nwpw_ilist.o


	  OBJ = 

      LIBRARY = libnwpwlib.a

    USES_BLAS = 

  LIB_DEFINES = 


include ../../../config/makefile.h
include ../../../config/makelib.h

