
OBJ_OPTIMIZE = tce_mrcc_input.o

LIB_INCLUDES = -I../include -I./include

LIBRARY = libtce.a

USES_BLAS = 

LIB_DEFINES = 

#              -DDEBUG_PRINT

HEADERS = 

include ../../config/makefile.h
include ../../config/makelib.h

