#
# $Id$
#

 OBJ_OPTIMIZE = \
            linesearch.o \
			Order_Values.o

	  OBJ = 

      LIBRARY = libnwpwlib.a

    USES_BLAS = 

  LIB_DEFINES = 


include ../../../config/makefile.h
include ../../../config/makelib.h

