#!/bin/csh
#
# $Id: get-tools,v 1.11 2008-01-16 18:54:58 d3p307 Exp $
#

svn checkout https://svn.pnl.gov/svn/hpctools/trunk/ga
cd ga
rm -f README
rm -f license.txt
rm -f INSTALL
rm -f NOTES
mv * ..
cd ..
rm -rf ga

